-- Catalog content from AdventureArena e7805e87, sorted by title.
-- Artwork paths are local; descriptions and reviews preserve the source text.
return {
	{
		id = "infocom.planetfall",
		title = "Planetfall",
		shortDescription = "Survive a crash landing on an alien world.",
		description = "Ensign Seventh Class of the Stellar Patrol — that's you. Your ship, the S.P.S. Feinstein, has been destroyed. You escaped in a life pod and crash-landed on a strange, seemingly abandoned planet. Explore the ruins of a lost civilization, befriend an unforgettable robot named Floyd, and unravel the mystery of what happened here. A landmark in interactive storytelling with genuine emotional depth.",
		author = "Infocom",
		year = 1983,
		rating = 4.7,
		reviewCount = 2104,
		startFile = "planetfall.zil",
		reviews = {
			{
				author = "floyd_fan",
				rating = 5,
				title = "Floyd is unforgettable",
				body = "Planetfall is charming, funny, and surprisingly moving. Floyd the robot is one of the greatest NPCs in gaming history.",
			},
			{
				author = "scifi_explorer",
				rating = 5,
				title = "Meretzky's masterpiece",
				body = "Steve Meretzky's debut game is a triumph. The writing is witty, the world is richly described, and the puzzles are fair.",
			},
		},
		genres = {
			"Sci-Fi Adventure",
		},
		cover = "examples/adventure-arena/assets/planetfall.jpg",
	},
	{
		id = "books.blackwood-horror",
		title = "Sanitarium",
		shortDescription = "A psychological horror adventure.",
		description = "Something is very wrong. You wake up in a place that shouldn't exist, surrounded by people who seem to know you — but you don't remember them. Navigate through fractured realities, solve deeply unsettling puzzles, and piece together the truth about who you really are.\n\nSanitarium is a slow-burn psychological horror experience where the most terrifying thing isn't what lurks in the shadows — it's what you might discover about yourself.",
		author = "Studio Null",
		year = 2024,
		rating = 4.5,
		reviewCount = 183,
		startFile = "blackwood-horror.zil",
		base = "infocom/zork1",
		reviews = {
			{
				author = "horrorFan99",
				rating = 5,
				title = "Genuinely unsettling",
				body = "I had to stop playing at night. The atmosphere is so thick you can feel it. One of the best horror text adventures I've played.",
			},
			{
				author = "interactive_fiction_nerd",
				rating = 4,
				title = "Slow start, incredible payoff",
				body = "Give it an hour before judging. The first chapter is setting up something deeply twisted, and when it all clicks, it's unforgettable.",
			},
		},
		genres = {
			"Psychological Horror",
		},
		cover = "examples/adventure-arena/assets/sanitarium.jpg",
	},
	{
		id = "infocom.spellbreaker",
		title = "Spellbreaker",
		shortDescription = "Magic itself is failing — save it.",
		description = "Ten years after the events of Enchanter, the very foundations of magic itself seem to be failing. As leader of the Circle of Enchanters, you must uncover the cause of this paralyzing chaos. Journey through the black foundation of magic itself in a perilous quest to save your world. Spellbreaker is the riveting conclusion to the Enchanter trilogy, and Infocom's most challenging game.",
		author = "Infocom",
		year = 1985,
		rating = 4.4,
		reviewCount = 891,
		startFile = "z6.zil",
		reviews = {
			{
				author = "mage_master",
				rating = 5,
				title = "Brutally difficult, deeply rewarding",
				body = "This is Infocom at its hardest. Every puzzle requires careful thought and creative spellcasting. Not for the faint of heart.",
			},
			{
				author = "enchanter_trilogy",
				rating = 4,
				title = "A satisfying finale",
				body = "The Enchanter trilogy ends on a high note. The spell system is ingenious and the puzzles are well-crafted, if extremely tough.",
			},
		},
		genres = {
			"Fantasy Adventure",
		},
		cover = "examples/adventure-arena/assets/spellbreaker.jpg",
	},
	{
		id = "books.wondertown",
		title = "The Last Toymaker's Apprentice",
		shortDescription = "Save a toy workshop's magic before dawn.",
		description = "You are Pip, a wind-up apprentice no taller than a teacup, working for Grandfather Tolliver, the last toymaker in Wrenfold. Every night after the shop closes, the toys wake up, and Pip keeps the workshop running until morning.\n\nTonight, Tolliver is missing and the workshop key has stopped ticking on its hook. Without it, the toys will fall silent by sunrise. Find out what happened, recover the key, and rewind the town's heart before dawn.",
		author = "Studio Null",
		year = 2024,
		rating = 4.7,
		reviewCount = 286,
		startFile = "wondertown.zil",
		base = "infocom/zork1",
		reviews = {
			{
				author = "ClockworkReader",
				rating = 5,
				title = "Whimsical with real heart",
				body = "The toy workshop is charming from the first room, but the story has more emotional weight than I expected. Pip is a wonderful protagonist.",
			},
			{
				author = "ParserFan",
				rating = 5,
				title = "A warm modern Infocom homage",
				body = "The WIND and OIL puzzles are clever, fair, and perfectly matched to the setting. It feels nostalgic without being stuck in the past.",
			},
			{
				author = "ToyboxTactician",
				rating = 4,
				title = "Cozy, clever, and bittersweet",
				body = "The puzzles are approachable, but the ending choices still made me pause. A lovely all-ages adventure.",
			},
		},
		genres = {
			"Whimsical Adventure",
		},
		cover = "examples/adventure-arena/assets/wondertown.jpg",
	},
	{
		id = "books.limehouse-killings",
		title = "The Limehouse Killings",
		shortDescription = "Solve a Victorian murder in fog-shrouded London.",
		description = "The year is 1888. Lord Ashworth, a wealthy industrialist, has been found dead in his locked study at Ashworth Manor in the Limehouse district. Scotland Yard is baffled. Lady Ashworth has hired you to investigate before the press gets wind of the scandal.\n\nAs a private detective in Victorian London, you must explore the manor, gather evidence, and interrogate three suspects: the nervous butler Mr. Hudson, the cold Lady Ashworth, and the arrogant Dr. Moriarty. Five key pieces of evidence point to the killer, but can you connect the clues before they escape?",
		author = "Studio Null",
		year = 2024,
		rating = 4.6,
		reviewCount = 342,
		startFile = "limehouse-killings.zil",
		base = "infocom/zork1",
		reviews = {
			{
				author = "IF_Weekly",
				rating = 5,
				title = "A masterclass in interactive mystery",
				body = "The Limehouse Killings is a triumph of interactive fiction. The atmospheric writing transports you to Victorian London, the puzzles are challenging but fair, and the story keeps you guessing until the very end.",
			},
			{
				author = "TextAdventureFan",
				rating = 5,
				title = "Victorian London has never felt so real",
				body = "The writing in this game is exceptional. You can smell the coal smoke and river damp, feel the fog on your face. The manor house is full of character, and the NPCs feel like real people.",
			},
			{
				author = "PuzzleMaster",
				rating = 4,
				title = "Challenging but fair",
				body = "I got stuck on the cipher puzzle for an hour, but when I figured it out, I felt like a genius. The game gives you all the clues you need — you just have to find them.",
			},
		},
		genres = {
			"Victorian Mystery",
		},
		cover = "examples/adventure-arena/assets/limehouse.jpg",
	},
	{
		id = "infocom.lurkinghorror",
		title = "The Lurking Horror",
		shortDescription = "Something ancient stirs beneath the campus.",
		description = "A blizzard rages outside G.U.E. Tech. You brave the storm to reach the computer lab and finish your term paper, but your file has been corrupted — partially overwritten by the Department of Alchemy's files. As you investigate, you descend into steam tunnels and ancient chambers where something ancient and malevolent stirs. Infocom's only horror game, inspired by the works of H.P. Lovecraft.",
		author = "Infocom",
		year = 1987,
		rating = 4.3,
		reviewCount = 723,
		startFile = "h1.zil",
		reviews = {
			{
				author = "lovecraft_reader",
				rating = 5,
				title = "Lovecraftian perfection",
				body = "Dave Lebling captures the cosmic horror atmosphere perfectly. The descriptions are chilling, and the sense of dread is palpable.",
			},
			{
				author = "crawler_tunnels",
				rating = 4,
				title = "Atmospheric and tense",
				body = "The best-written Infocom game I've played. The blizzard setting, the creepy campus, the ancient evil — it all works beautifully.",
			},
		},
		genres = {
			"Psychological Horror",
		},
		cover = "examples/adventure-arena/assets/lurkinghorror.jpg",
	},
	{
		id = "infocom.zork1",
		title = "Zork I: The Great Underground Empire",
		shortDescription = "Explore the Great Underground Empire.",
		description = "You are standing in an open field west of a white house, with a boarded front door. You are about to begin a legendary adventure that started it all — a journey into the Great Underground Empire. Navigate treacherous mazes, collect treasures, and outwit the fearsome Grues that lurk in the dark.\n\nOriginally created at MIT in the late 1970s, Zork pioneered the text adventure genre and established many of the conventions still used in interactive fiction today.",
		author = "Infocom",
		year = 1980,
		rating = 4.8,
		reviewCount = 2341,
		startFile = "zork1.zil",
		reviews = {
			{
				author = "dungeon_crawler",
				rating = 5,
				title = "A timeless classic",
				body = "Still holds up decades later. The writing is sharp, the puzzles are fair, and exploring the dungeon never gets old. This is where it all began.",
			},
			{
				author = "text_adventurer",
				rating = 5,
				title = "The gold standard",
				body = "If you've never played a text adventure, start here. Zork set the bar so high that most games since have been playing catch-up.",
			},
			{
				author = "pixel_nostalgia",
				rating = 4,
				title = "Great but brutal",
				body = "Zork rewards patience and lateral thinking. A few puzzles are obtuse by modern standards, but the atmosphere and writing more than make up for it.",
			},
		},
		genres = {
			"Classic Adventure",
		},
		cover = "examples/adventure-arena/assets/zork1.jpg",
	},
	{
		id = "infocom.zork2",
		title = "Zork II: The Wizard of Frobozz",
		shortDescription = "Confront the capricious Wizard of Frobozz.",
		description = "The Wizard appears, floating nonchalantly in the air beside you. He grins sideways at you. As you explore deeper into the Great Underground Empire, you'll face the Wizard's unpredictable magic, navigate treacherous new mazes, and uncover secrets even darker than those of Zork I. The sequel that expanded the legend.",
		author = "Infocom",
		year = 1981,
		rating = 4.6,
		reviewCount = 1872,
		startFile = "zork2.zil",
		reviews = {
			{
				author = "wizard_watcher",
				rating = 5,
				title = "A worthy successor",
				body = "The Wizard of Frobozz is one of gaming's great characters. Unpredictable, hilarious, and occasionally helpful — he makes this game unforgettable.",
			},
			{
				author = "dungeon_diver",
				rating = 4,
				title = "Tougher than Zork I",
				body = "The puzzles here are harder and more abstract. The Carousel Room alone is a rite of passage for any text adventure fan.",
			},
		},
		genres = {
			"Classic Adventure",
		},
		cover = "examples/adventure-arena/assets/zork2.jpg",
	},
	{
		id = "infocom.zork3",
		title = "Zork III: The Dungeon Master",
		shortDescription = "The final chapter of the Zork trilogy.",
		description = "You have reached the final test. The deepest and most mysterious reaches of the Great Underground Empire await. Nothing is as it seems, and the one responsible for the shadow and darkness — the Dungeon Master — embodies the greatest mystery of all. In this test of wisdom and courage, you will face countless dangers. But what awaits you at the culmination of your odyssey is well worth risking all.",
		author = "Infocom",
		year = 1982,
		rating = 4.5,
		reviewCount = 1567,
		startFile = "zork3.zil",
		reviews = {
			{
				author = "trilogy_complete",
				rating = 5,
				title = "A profound conclusion",
				body = "Zork III is different — more atmospheric, more philosophical. It rewards exploration and patience over brute-force puzzle solving.",
			},
			{
				author = "retro_gamer",
				rating = 4,
				title = "A fitting end",
				body = "Not as iconic as Zork I, but the somber, mysterious tone sets it apart. The ending is genuinely satisfying.",
			},
		},
		genres = {
			"Classic Adventure",
		},
		cover = "examples/adventure-arena/assets/zork3.jpg",
	},
}
