local D = require("apps.diskmap.catalog.Definitions")
local item, group, cache, ownerCache, xcode, system, assets = D.item, D.group, D.cache, D.ownerCache, D.xcode, D.system, D.assets
return function()
	return group("developer", "Developer", "Xcode, package managers, editors and environments", "hammer.fill", "systemPurple", {
	item("projects", "Developer projects", "Source repositories and local build outputs", "~/Developer"),
	item("usr-local", "Local development tools", "Locally installed command-line tools and packages", "/usr/local"),
	group("xcode", "Xcode", "Simulators, SDKs, device support and build history", "hammer.fill", "systemBlue", {
		group("runtimes", "Simulator runtimes", "Keep installed operating systems required for simulator development", "iphone", "systemBlue", {
			item("runtime-images", "Runtime disk images", "CoreSimulator image storage", "/Library/Developer/CoreSimulator/Images", {policy = "Essential", action = "finder"}),
			item("runtime-bundles", "Runtime bundles", "Registered simulator operating systems", "/Library/Developer/CoreSimulator/Profiles/Runtimes", {policy = "Essential"}),
			item("runtime-assets", "iOS runtime downloads", "System-managed iOSSimulatorRuntime assets; retained by default", "/System/Library/AssetsV2/com_apple_MobileAsset_iOSSimulatorRuntime", {policy = "Essential", action = "finder"}),
		}),
		item("simulators", "Simulator devices", "Installed test apps, settings and device data — manage without Xcode", "~/Library/Developer/CoreSimulator/Devices", {action = "simulators", consequence = "Erase removes installed test apps, accounts and device data. Delete also removes the device. Installed runtimes are preserved. Shut down a running device first."}),
		item("derived", "Xcode DerivedData", "Rebuildable build products, indexes and logs", "~/Library/Developer/Xcode/DerivedData", cache),
		item("devices", "Device support", "Symbols used when debugging connected devices", "~/Library/Developer/Xcode/iOS DeviceSupport", xcode),
		item("watch-devices", "watchOS device support", "Symbols copied from paired Apple Watches", "~/Library/Developer/Xcode/watchOS DeviceSupport", xcode),
		item("device-logs", "Device logs", "Crash and diagnostic logs copied from connected devices", "~/Library/Developer/Xcode/iOS Device Logs", xcode),
		item("sim-caches", "Simulator caches", "Shared dyld and runtime caches CoreSimulator rebuilds on demand", "~/Library/Developer/CoreSimulator/Caches", cache),
		item("xcode-previews", "SwiftUI preview devices", "Simulators Xcode creates for previews; recreated by the next preview", "~/Library/Developer/Xcode/UserData/Previews", {policy = "Rebuildable", action = "ownerCleanup", commandId = "xcode-previews", consequence = "Diskmap asks simctl to delete Xcode's preview devices. Xcode recreates them the next time a preview runs, so that preview starts more slowly. Quit Xcode first."}),
		item("archives", "Archives", "Release builds and debug symbols — review before removing", "~/Library/Developer/Xcode/Archives", xcode),
		item("xcode-app", "Xcode & bundled SDKs", "SDKs belong to this installation; do not remove them individually", "/Applications/Xcode.app", {action = "sdks", consequence = "These SDKs belong to this Xcode installation. Removing one individually can break builds. Reinstalling Xcode restores them."}),
		item("clt", "Command Line Tools", "Compilers, SDKs and development utilities", "/Library/Developer/CommandLineTools", {action = "sdks", consequence = "These SDKs belong to the Command Line Tools. Removing one individually can break command-line builds. Reinstalling the tools restores them."}),
		assets("developer-assets", "Downloaded developer assets", "Documentation, simulator runtimes and optional toolchains", "hammer.fill", "systemBlue", {"MetalToolchain", "SourceEditorAssets"}),
		item("documentation", "Offline developer documentation", "Downloaded reference documentation; online documentation remains available", "~/Library/Developer/Shared/Documentation", {action = "trash", policy = "Rebuildable", consequence = "Quit developer tools first. Removes offline documentation; download it again when needed. Moving to Trash does not free space until Finder empties it."}),
		item("documentation-assets", "Offline Apple documentation", "AppleDeveloperDocumentation downloaded by macOS", "/System/Library/AssetsV2/com_apple_MobileAsset_AppleDeveloperDocumentation", {action = "settings", settingsSection = "storage", consequence = "Review Developer storage in System Settings to remove optional offline documentation where offered. Online documentation remains available. Protected asset files are managed by macOS."}),
	}),
	group("packages", "Package managers", "Downloaded packages are separate from installed environments", "shippingbox", "systemOrange", {
		item("npm", "npm downloads", "Content-addressed package download cache", "~/.npm/_cacache", {policy = ownerCache.policy, action = ownerCache.action, commandId = "npm-cache", consequence = ownerCache.consequence}),
		item("pip", "Python package downloads", "Cached wheels and downloaded packages", "~/Library/Caches/pip", {policy = ownerCache.policy, action = ownerCache.action, commandId = "pip-cache", consequence = ownerCache.consequence}),
		item("brew", "Homebrew downloads", "Cached bottles; installed packages are preserved", "~/Library/Caches/Homebrew", cache),
		item("pnpm-store", "pnpm store", "Content-addressed packages shared across projects", "~/Library/pnpm/store", cache),
		item("yarn-cache", "Yarn cache", "Downloaded package archives", "~/Library/Caches/Yarn", cache),
		item("cocoapods-cache", "CocoaPods cache", "Downloaded pod specs and source archives; paths can be changed with CP_HOME_DIR", "~/Library/Caches/CocoaPods"),
		item("cocoapods-repos", "CocoaPods spec repos", "Local spec-repository mirrors; review before removing", "~/.cocoapods/repos"),
		item("swiftpm-cache", "Swift Package Manager cache", "Downloaded package sources and repository data", "~/Library/Caches/org.swift.swiftpm", cache),
		item("conda-packages", "Conda package cache", "Downloaded packages; separate from installed environments", "~/miniconda3/pkgs"),
		item("conda-packages-user", "Conda package cache (Anaconda)", "Downloaded packages; separate from installed environments", "~/anaconda3/pkgs"),
		item("bun-cache", "Bun install cache", "Downloaded packages shared across projects", "~/.bun/install/cache", cache),
		item("uv-cache", "uv cache", "Downloaded Python wheels and built environments", "~/.cache/uv", cache),
		item("go-build", "Go build cache", "Compiled packages; `go clean -cache` removes it too", "~/Library/Caches/go-build", cache),
		item("deno-cache", "Deno cache", "Downloaded modules and compiled code", "~/Library/Caches/deno", cache),
		item("carthage-cache", "Carthage cache", "Downloaded dependency builds", "~/Library/Caches/org.carthage.CarthageKit", cache),
		item("node-gyp", "node-gyp headers", "Node headers downloaded to build native modules", "~/Library/Caches/node-gyp", cache),
		item("brew-install", "Homebrew installation", "Installed packages and environments", "/opt/homebrew"),
		item("brew-logs", "Homebrew service logs", "Logs written by services started with brew services", "/opt/homebrew/var/log", {reviewThreshold = 1e9, consequence = "A runaway service can write logs without limit; one report found a 304 GB log here. Stop or fix the service with brew services, then remove old logs. Keep logs you still need for troubleshooting."}),
	}),
	group("test-browsers", "Test browsers", "Browsers downloaded by test runners, one per version", "safari", "systemTeal", {
		item("playwright", "Playwright browsers", "Chromium, Firefox and WebKit builds; old versions are never removed automatically", "~/Library/Caches/ms-playwright", cache),
		item("puppeteer", "Puppeteer browsers", "Chrome builds downloaded by Puppeteer", "~/.cache/puppeteer", cache),
		item("cypress", "Cypress binaries", "One Cypress app per installed version", "~/Library/Caches/Cypress", cache),
		item("electron-cache", "Electron downloads", "Electron release archives used by builders", "~/Library/Caches/electron", cache),
	}),
	group("toolchains", "Language toolchains", "Installed language versions; remove old ones with their version manager", "chevron.left.forwardslash.chevron.right", "systemIndigo", {
		item("nvm", "Node.js versions (nvm)", "Every Node version installed with nvm, with its global packages", "~/.nvm/versions", {reviewThreshold = 3e9, consequence = "Remove versions you no longer use with nvm uninstall. Global packages installed under a version are removed with it."}),
		item("rustup", "Rust toolchains", "Installed Rust toolchains and targets", "~/.rustup/toolchains", {reviewThreshold = 3e9, consequence = "List toolchains with rustup toolchain list and remove old nightlies with rustup toolchain uninstall."}),
		item("pyenv", "Python versions (pyenv)", "Python interpreters built by pyenv", "~/.pyenv/versions", {reviewThreshold = 3e9, consequence = "Remove versions you no longer use with pyenv uninstall. Virtual environments built on a removed version stop working."}),
		item("sdkman", "SDKMAN candidates", "JDKs, Gradle and other JVM tools installed by SDKMAN", "~/.sdkman/candidates", {reviewThreshold = 3e9, consequence = "Remove old versions with sdk uninstall."}),
		item("cargo", "Rust registry", "Downloaded crates and registry indexes", "~/.cargo/registry"),
		item("gradle", "Gradle", "Build caches and tool distributions", "~/.gradle"),
		item("maven", "Maven repository", "Downloaded and locally published artifacts", "~/.m2/repository"),
		item("go", "Go modules", "Downloaded module sources", "~/go/pkg/mod"),
	}),
	group("mobile-dev", "Cross-platform & mobile", "Android, Flutter and platform package data", "iphone.gen3", "systemGreen", {
		item("android-sdk", "Android SDK", "Platforms, build tools and system images", "~/Library/Android/sdk"),
		item("android-avd", "Android emulators (AVDs)", "Virtual device images, snapshots and user data", "~/.android/avd", {reviewThreshold = 2e9, consequence = "Each virtual device can contain installed apps and personal test data. Review in Android Studio or the device manager before removing."}),
		item("flutter-pub", "Flutter & Dart package cache", "Downloaded packages shared across projects", "~/.pub-cache", cache),
	}),
	group("editors", "Editors & IDEs", "Application data can include settings and unsaved work", "curlybraces", "systemBlue", {
		group("vscode-data", "Visual Studio Code", "Caches separated from settings and unsaved work", "curlybraces", "systemBlue", {
			item("vscode-cache", "VS Code cache", "Rebuildable Chromium cache; review in the owning editor", "~/Library/Application Support/Code/Cache"),
			item("vscode-cached-data", "VS Code compiled code cache", "Generated JavaScript compilation data", "~/Library/Application Support/Code/CachedData"),
			item("vscode-gpu-cache", "VS Code GPU cache", "Generated graphics data", "~/Library/Application Support/Code/GPUCache"),
			item("vscode", "VS Code settings & work", "Settings, databases and recovery data; excludes listed caches", "~/Library/Application Support/Code"),
		}),
		item("vscode-extensions", "VS Code extensions", "Installed editor extensions", "~/.vscode/extensions"),
		item("jetbrains", "JetBrains", "IDE caches and project indexes", "~/Library/Caches/JetBrains"),
	}),
	group("containers", "Containers & virtual machines", "Owner-managed disks may contain databases and personal work", "shippingbox.fill", "systemOrange", {
		item("docker", "Docker Desktop", "Default data location; virtual disk, images, containers, logs and persistent volumes", "~/Library/Containers/com.docker.docker", {action = "docker", consequence = "Review the disk image's current location and actual use in Docker Desktop > Settings > Resources > Advanced; the image can be moved, so Diskmap may not measure a custom location. Docker's log paths belong to its Linux daemon and are not separately measured; review logs in Docker Desktop. Prune only data you identify as unused. Volumes and the virtual disk can contain databases or personal work. Never move or delete the disk image directly in Finder."}),
		item("colima", "Colima", "Virtual machines and container storage", "~/.colima"),
		item("parallels", "Parallels virtual machines", "Guest operating systems and their data", "~/Parallels"),
		item("orbstack", "OrbStack", "Linux machines, containers and volumes", "~/.orbstack", {reviewThreshold = 10e9, consequence = "Prune images and delete machines from OrbStack. Its disk image can contain databases and personal work; never delete it in Finder."}),
		item("utm", "UTM virtual machines", "Guest operating systems created in UTM", "~/Library/Containers/com.utmapp.UTM/Data/Documents", {reviewThreshold = 10e9, consequence = "Delete virtual machines you no longer need from UTM. Each one holds a full guest disk with its own files."}),
		item("vmware", "VMware Fusion virtual machines", "Guest operating systems and snapshots", "~/Virtual Machines.localized", {reviewThreshold = 10e9, consequence = "Delete old snapshots and machines from VMware Fusion. Snapshots can double a machine's size."}),
		item("virtualbox", "VirtualBox virtual machines", "Guest disks and snapshots", "~/VirtualBox VMs", {reviewThreshold = 10e9, consequence = "Delete machines and snapshots from VirtualBox Manager."}),
		item("podman", "Podman machines & storage", "Podman virtual machine and container storage", "~/.local/share/containers", {reviewThreshold = 10e9, consequence = "Prune with podman system prune in the owning tool. Volumes can contain databases."}),
	}),
})
end
