local D = require("apps.diskmap.catalog.Definitions")
local item, group, cache, ownerCache, system, essential, assets, with = D.item, D.group, D.cache, D.ownerCache, D.system, D.essential, D.assets, D.with
-- Browsers test runners download, one full build per version.
local browsers = with(cache, {threshold = 1e9,
	advice = "Test runners download one browser build per version and never remove old ones. The version your project pins downloads again on the next install. Moving to Trash does not free space until you empty it."})
-- Installed language versions, removed with their version manager.
local function versions(advice)
	return {nature = "library", remover = "owner", threshold = 3e9, advice = advice}
end
-- Virtual machines and container stores: pruned in the owning tool, since
-- their disks can hold databases and personal work.
local function machines(advice)
	return {nature = "appData", remover = "owner", threshold = 10e9, advice = advice}
end
return function()
	return group("developer", "Developer", "Xcode, package managers, editors and environments", "hammer.fill", "systemPurple", {
	item("projects", "Developer projects", "Source repositories and local build outputs", "~/Developer", {nature = "personal", remover = "none", page = "projects"}),
	item("usr-local", "Local development tools", "Locally installed command-line tools and packages", "/usr/local"),
	group("xcode", "Xcode", "Simulators, SDKs, device support and build history", "hammer.fill", "systemBlue", {
		group("runtimes", "Simulator runtimes", "Keep installed operating systems required for simulator development", "iphone", "systemBlue", {
			item("runtime-images", "Runtime disk images", "CoreSimulator image storage", "/Library/Developer/CoreSimulator/Images", essential),
			item("runtime-bundles", "Runtime bundles", "Registered simulator operating systems", "/Library/Developer/CoreSimulator/Profiles/Runtimes", essential),
			item("runtime-assets", "iOS runtime downloads", "System-managed iOSSimulatorRuntime assets; retained by default", "/System/Library/AssetsV2/com_apple_MobileAsset_iOSSimulatorRuntime", essential),
		}),
		item("simulators", "Simulator devices", "Installed test apps, settings and device data — manage without Xcode", "~/Library/Developer/CoreSimulator/Devices",
			{nature = "personal", remover = "owner", action = "simulators", page = "simulators", threshold = 5e9,
				advice = "Review unused simulator devices on the Simulators page. Erase removes installed test apps, accounts and device data; Delete also removes the device. Installed runtimes stay. Shut down a running device first."}),
		item("xctest-devices", "Test devices", "Simulators xcodebuild creates for test runs, one per destination, never removed", "~/Library/Developer/XCTestDevices",
			{nature = "cache", remover = "owner", threshold = 2e9,
				advice = "Every xcodebuild test run clones a device here and leaves it. Quit Xcode, then run xcrun simctl --set testing delete all in Terminal; the next test run creates what it needs."}),
		item("derived", "Xcode DerivedData", "Rebuildable build products, indexes and logs", "~/Library/Developer/Xcode/DerivedData",
			with(cache, {page = "xcode", threshold = 1e9,
				advice = "Build products and indexes Xcode regenerates; the next build and indexing take longer. Quit Xcode first. Moving to Trash does not free space until you empty it."})),
		item("devices", "Device support", "Symbols used when debugging connected devices", "~/Library/Developer/Xcode/iOS DeviceSupport",
			{nature = "download", remover = "owner", action = "xcode", page = "xcode", threshold = 2e9,
				advice = "Debug symbols Xcode copied from connected devices, one folder per OS version. Keep the versions you still debug; Xcode copies them again when you connect a device."}),
		item("watch-devices", "watchOS device support", "Symbols copied from paired Apple Watches", "~/Library/Developer/Xcode/watchOS DeviceSupport",
			{nature = "download", remover = "owner", action = "xcode", page = "xcode", threshold = 2e9,
				advice = "Debug symbols Xcode copied from paired watches, one folder per watchOS version. Keep the versions you still debug; Xcode copies them again when you connect a watch."}),
		item("device-logs", "Device logs", "Crash and diagnostic logs copied from connected devices", "~/Library/Developer/Xcode/iOS Device Logs",
			{nature = "log", remover = "owner", action = "xcode", threshold = 2e9,
				advice = "Crash and diagnostic logs copied from connected devices. Review them in Xcode's Devices window and keep logs for devices and OS versions you still debug."}),
		item("sim-caches", "Simulator caches", "Shared dyld and runtime caches CoreSimulator rebuilds on demand", "~/Library/Developer/CoreSimulator/Caches",
			with(cache, {threshold = 1e9, advice = "CoreSimulator rebuilds its shared dyld and runtime caches the next time a simulator boots. Quit Xcode and Simulator first. Moving to Trash does not free space until you empty it."})),
		item("xcode-previews", "SwiftUI preview devices", "Simulators Xcode creates for previews; recreated by the next preview", "~/Library/Developer/Xcode/UserData/Previews",
			{nature = "cache", remover = "ownerCommand", commandId = "xcode-previews", threshold = 1e9,
				advice = "Diskmap asks simctl to delete Xcode's preview devices. Xcode recreates them the next time a preview runs, so that preview starts more slowly. Quit Xcode first."}),
		item("archives", "Archives", "Release builds and debug symbols — review before removing", "~/Library/Developer/Xcode/Archives",
			{nature = "personal", remover = "owner", action = "xcode", page = "xcode", threshold = 5e9,
				advice = "Review old releases in Xcode Organizer. Archives and debug symbols may be irreplaceable; back them up before removing."}),
		item("xcode-app", "Xcode & bundled SDKs", "SDKs belong to this installation; do not remove them individually", "/Applications/Xcode.app",
			{remover = "owner", action = "sdks", sheet = "sdks", advice = "These SDKs belong to this Xcode installation. Removing one individually can break builds. Reinstalling Xcode restores them."}),
		item("clt", "Command Line Tools", "Compilers, SDKs and development utilities", "/Library/Developer/CommandLineTools",
			{remover = "owner", action = "sdks", sheet = "sdks", advice = "These SDKs belong to the Command Line Tools. Removing one individually can break command-line builds. Reinstalling the tools restores them."}),
		assets("developer-assets", "Downloaded developer assets", "Documentation, simulator runtimes and optional toolchains", "hammer.fill", "systemBlue", {"MetalToolchain", "SourceEditorAssets"}),
		item("documentation", "Offline developer documentation", "Downloaded reference documentation; online documentation remains available", "~/Library/Developer/Shared/Documentation",
			with(cache, {advice = "Offline reference documentation. Quit developer tools first; download it again when needed. Moving to Trash does not free space until you empty it."})),
		item("documentation-assets", "Offline Apple documentation", "AppleDeveloperDocumentation downloaded by macOS", "/System/Library/AssetsV2/com_apple_MobileAsset_AppleDeveloperDocumentation",
			{nature = "download", remover = "setting", settingsSection = "storage", threshold = 500e6,
				advice = "Review Developer storage in System Settings to remove optional offline documentation where offered. Online documentation remains available. Protected asset files are managed by macOS."}),
	}),
	group("packages", "Package managers", "Downloaded packages are separate from installed environments", "shippingbox", "systemOrange", {
		item("npm", "npm downloads", "Content-addressed package download cache", "~/.npm/_cacache", with(ownerCache, {commandId = "npm-cache"})),
		item("pip", "Python package downloads", "Cached wheels and downloaded packages", "~/Library/Caches/pip", with(ownerCache, {commandId = "pip-cache"})),
		item("brew", "Homebrew downloads", "Cached bottles; installed packages are preserved", "~/Library/Caches/Homebrew", cache),
		item("pnpm-store", "pnpm store", "Content-addressed packages shared across projects", "~/Library/pnpm/store", cache),
		item("yarn-cache", "Yarn cache", "Downloaded package archives", "~/Library/Caches/Yarn", cache),
		item("cocoapods-cache", "CocoaPods cache", "Downloaded pod specs and source archives; paths can be changed with CP_HOME_DIR", "~/Library/Caches/CocoaPods",
			{nature = "cache", remover = "owner", threshold = 1e9, advice = "Run pod cache clean --all; pod install downloads specs and sources again. CocoaPods can move this folder with CP_HOME_DIR, so only the default location is measured."}),
		item("cocoapods-repos", "CocoaPods spec repos", "Local spec-repository mirrors; review before removing", "~/.cocoapods/repos"),
		item("swiftpm-cache", "Swift Package Manager cache", "Downloaded package sources and repository data", "~/Library/Caches/org.swift.swiftpm", cache),
		item("conda-packages", "Conda package cache", "Downloaded packages; separate from installed environments", "~/miniconda3/pkgs",
			{nature = "cache", remover = "owner", threshold = 2e9, advice = "Run conda clean --packages to remove packages no environment uses; conda downloads them again when an environment needs them."}),
		item("conda-packages-user", "Conda package cache (Anaconda)", "Downloaded packages; separate from installed environments", "~/anaconda3/pkgs",
			{nature = "cache", remover = "owner", threshold = 2e9, advice = "Run conda clean --packages to remove packages no environment uses; conda downloads them again when an environment needs them."}),
		item("bun-cache", "Bun install cache", "Downloaded packages shared across projects", "~/.bun/install/cache", cache),
		item("uv-cache", "uv cache", "Downloaded Python wheels and built environments", "~/.cache/uv", cache),
		item("go-build", "Go build cache", "Compiled packages; `go clean -cache` removes it too", "~/Library/Caches/go-build", cache),
		item("deno-cache", "Deno cache", "Downloaded modules and compiled code", "~/Library/Caches/deno", cache),
		item("carthage-cache", "Carthage cache", "Downloaded dependency builds", "~/Library/Caches/org.carthage.CarthageKit", cache),
		item("node-gyp", "node-gyp headers", "Node headers downloaded to build native modules", "~/Library/Caches/node-gyp", cache),
		item("brew-install", "Homebrew installation", "Installed packages, with the older versions and downloads kept after upgrades", "/opt/homebrew",
			{nature = "appData", remover = "owner", threshold = 10e9,
				advice = "Homebrew keeps older versions of upgraded packages and their downloads. Run brew cleanup to remove them and brew autoremove to drop dependencies nothing needs."}),
		item("brew-logs", "Homebrew service logs", "Logs written by services started with brew services", "/opt/homebrew/var/log",
			{nature = "log", remover = "finder", threshold = 1e9,
				advice = "A runaway service can write logs without limit; one report found a 304 GB log here. Stop or fix the service with brew services, then remove old logs. Keep logs you still need for troubleshooting."}),
	}),
	group("test-browsers", "Test browsers", "Browsers downloaded by test runners, one per version", "safari", "systemTeal", {
		item("playwright", "Playwright browsers", "Chromium, Firefox and WebKit builds; old versions are never removed automatically", "~/Library/Caches/ms-playwright", browsers),
		item("puppeteer", "Puppeteer browsers", "Chrome builds downloaded by Puppeteer", "~/.cache/puppeteer", browsers),
		item("cypress", "Cypress binaries", "One Cypress app per installed version", "~/Library/Caches/Cypress", browsers),
		item("electron-cache", "Electron downloads", "Electron release archives used by builders", "~/Library/Caches/electron", browsers),
	}),
	group("toolchains", "Language toolchains", "Installed language versions; remove old ones with their version manager", "chevron.left.forwardslash.chevron.right", "systemIndigo", {
		item("nvm", "Node.js versions (nvm)", "Every Node version installed with nvm, with its global packages", "~/.nvm/versions",
			versions("Remove versions you no longer use with nvm uninstall. Global packages installed under a version are removed with it.")),
		item("rustup", "Rust toolchains", "Installed Rust toolchains and targets", "~/.rustup/toolchains",
			versions("List toolchains with rustup toolchain list and remove old nightlies with rustup toolchain uninstall.")),
		item("pyenv", "Python versions (pyenv)", "Python interpreters built by pyenv", "~/.pyenv/versions",
			versions("Remove versions you no longer use with pyenv uninstall. Virtual environments built on a removed version stop working.")),
		item("sdkman", "SDKMAN candidates", "JDKs, Gradle and other JVM tools installed by SDKMAN", "~/.sdkman/candidates",
			versions("Remove old versions with sdk uninstall.")),
		item("cargo", "Rust registry", "Downloaded crates and registry indexes", "~/.cargo/registry",
			{nature = "cache", remover = "finder", threshold = 2e9, advice = "Downloaded crates and the registry index. Remove them in Finder while no build runs; cargo downloads what a build needs again."}),
		item("gradle", "Gradle", "Build caches and tool distributions", "~/.gradle",
			{nature = "cache", remover = "finder", threshold = 2e9, advice = "Build caches, wrapper distributions and daemon logs. Remove the caches and wrapper/dists folders in Finder while no build runs; Gradle downloads and rebuilds them."}),
		item("maven", "Maven repository", "Downloaded and locally published artifacts", "~/.m2/repository",
			{nature = "cache", remover = "finder", threshold = 2e9, advice = "Downloaded artifacts. Remove them in Finder while no build runs; mvn downloads what a build needs again."}),
		item("go", "Go modules", "Downloaded module sources", "~/go/pkg/mod",
			{nature = "cache", remover = "owner", threshold = 2e9, advice = "Downloaded module sources. Run go clean -modcache; go downloads what a build needs again."}),
		item("mise-installs", "mise tool versions", "Installed language runtimes and tools", "~/.local/share/mise",
			with(versions("Remove versions you no longer use with mise uninstall or mise prune."), {threshold = 2e9})),
	}),
	group("mobile-dev", "Cross-platform & mobile", "Android, Flutter and platform package data", "iphone.gen3", "systemGreen", {
		item("android-sdk", "Android SDK", "Platforms, build tools and system images", "~/Library/Android/sdk",
			{nature = "library", remover = "owner", threshold = 10e9, advice = "Remove platforms, system images and build tools you no longer target in Android Studio's SDK Manager. A project that needs one asks for it again."}),
		item("android-avd", "Android emulators (AVDs)", "Virtual device images, snapshots and user data", "~/.android/avd",
			{nature = "personal", remover = "owner", threshold = 2e9, advice = "Each virtual device can contain installed apps and personal test data. Review in Android Studio or the device manager before removing."}),
		item("flutter-pub", "Flutter & Dart package cache", "Downloaded packages shared across projects", "~/.pub-cache", cache),
	}),
	group("editors", "Editors & IDEs", "Application data can include settings and unsaved work", "curlybraces", "systemBlue", {
		group("vscode-data", "Visual Studio Code", "Caches separated from settings and unsaved work", "curlybraces", "systemBlue", {
			item("vscode-cache", "VS Code cache", "Rebuildable Chromium cache; review in the owning editor", "~/Library/Application Support/Code/Cache",
				{nature = "cache", remover = "owner", threshold = 1e9, advice = "Review generated editor data using the editor's own storage controls. Preserve settings and recovery data."}),
			item("vscode-cached-data", "VS Code compiled code cache", "Generated JavaScript compilation data", "~/Library/Application Support/Code/CachedData",
				{nature = "cache", remover = "owner", threshold = 1e9, advice = "Review generated editor data using the editor's own storage controls. Preserve settings and recovery data."}),
			item("vscode-gpu-cache", "VS Code GPU cache", "Generated graphics data", "~/Library/Application Support/Code/GPUCache",
				{nature = "cache", remover = "owner", threshold = 1e9, advice = "Review generated editor data using the editor's own storage controls. Preserve settings and recovery data."}),
			item("vscode-workspace-storage", "VS Code workspace storage", "State kept for every folder ever opened, never pruned", "~/Library/Application Support/Code/User/workspaceStorage",
				{nature = "cache", remover = "finder", threshold = 1e9, advice = "VS Code keeps state for every folder you ever opened and never prunes it. Quit VS Code, then remove the folders of workspaces you no longer open; a workspace rebuilds its state the next time it opens."}),
			item("vscode", "VS Code settings & work", "Settings, databases and recovery data; excludes listed caches", "~/Library/Application Support/Code"),
		}),
		item("vscode-extensions", "VS Code extensions", "Installed editor extensions", "~/.vscode/extensions", {remover = "owner"}),
		item("jetbrains", "JetBrains", "IDE caches and project indexes", "~/Library/Caches/JetBrains",
			{nature = "cache", remover = "owner", threshold = 1e9, advice = "Review generated editor data using the editor's own storage controls. Preserve settings and recovery data."}),
	}),
	group("containers", "Containers & virtual machines", "Owner-managed disks may contain databases and personal work", "shippingbox.fill", "systemOrange", {
		item("docker", "Docker Desktop", "Default data location; virtual disk, images, containers, logs and persistent volumes", "~/Library/Containers/com.docker.docker",
			with(machines("Review the disk image's current location and actual use in Docker Desktop > Settings > Resources > Advanced; the image can be moved, so Diskmap may not measure a custom location. Docker's log paths belong to its Linux daemon and are not separately measured; review logs in Docker Desktop. Prune only data you identify as unused. Volumes and the virtual disk can contain databases or personal work. Never move or delete the disk image directly in Finder."),
				{action = "docker"})),
		item("colima", "Colima", "Virtual machines and container storage", "~/.colima",
			machines("Review unused environments in the owning tool. Virtual disks and volumes can contain databases and personal work.")),
		item("parallels", "Parallels virtual machines", "Guest operating systems and their data", "~/Parallels",
			machines("Review unused environments in the owning tool. Virtual disks and volumes can contain databases and personal work.")),
		item("orbstack", "OrbStack", "Linux machines, containers and volumes", "~/.orbstack",
			machines("Prune images and delete machines from OrbStack. Its disk image can contain databases and personal work; never delete it in Finder.")),
		item("utm", "UTM virtual machines", "Guest operating systems created in UTM", "~/Library/Containers/com.utmapp.UTM/Data/Documents",
			machines("Delete virtual machines you no longer need from UTM. Each one holds a full guest disk with its own files.")),
		item("vmware", "VMware Fusion virtual machines", "Guest operating systems and snapshots", "~/Virtual Machines.localized",
			machines("Delete old snapshots and machines from VMware Fusion. Snapshots can double a machine's size.")),
		item("virtualbox", "VirtualBox virtual machines", "Guest disks and snapshots", "~/VirtualBox VMs",
			machines("Delete machines and snapshots from VirtualBox Manager.")),
		item("podman", "Podman machines & storage", "Podman virtual machine and container storage", "~/.local/share/containers",
			machines("Prune with podman system prune in the owning tool. Volumes can contain databases.")),
	}),
})
end
