-- Drum & bass blocks. 16 steps to a bar, a bar is a beat at 87 BPM-ish half
-- time: the two-step kick sits on step 0 and 10 with the snare on 4 and 12;
-- halftime moves the snare to step 8. Pitch is in scale steps (0 root, 2
-- third, 4 fifth, 7 octave), so every line works in minor, dorian and
-- phrygian and under the genre's chord changes.
-- Flavours: liquid anthem jungle tearout neuro rollers minimal halftime
-- jumpup atmospheric. A block with no `flavours` suits all of them.
return {
	-- DRUMS ---------------------------------------------------------------
	-- Quiet, tonal-free loops for the first and last bars of a mix.
	{id = "dnb.drums.001", role = "drums", bars = 2, energy = 0.2, density = 0.2,
		tags = {"twostep", "minimal", "sparse", "mixable"},
		lanes = {{"kick", "X.........x.....|X.........x....."}, {"snare", "....o.......o..."},
			{"hat", "..x...x...x...x.", gain = 0.4}}},
	{id = "dnb.drums.002", role = "drums", bars = 2, energy = 0.28, density = 0.3, flavours = {"liquid", "atmospheric", "halftime"},
		tags = {"twostep", "swung", "warm", "mixable"},
		lanes = {{"kick", "X.........x.....|X.........x....."}, {"rim", "....x.......x...", gain = 0.55},
			{"hat", "..x...x...x...x.", gain = 0.5}, {"shaker", "xoxoxoxoxoxoxoxo", gain = 0.25}}},
	{id = "dnb.drums.003", role = "drums", bars = 1, energy = 0.35, density = 0.3, flavours = {"minimal", "tearout", "neuro", "rollers"},
		tags = {"twostep", "minimal", "straight", "sparse", "mixable"},
		lanes = {{"kick", "X.........X....."}, {"snare", "....X.......X..."}, {"hat", "x.x.x.x.x.x.x.x.", gain = 0.35}}},
	{id = "dnb.drums.004", role = "drums", bars = 2, energy = 0.4, density = 0.45, flavours = {"liquid", "rollers", "atmospheric"},
		tags = {"twostep", "swung", "soulful", "mixable"},
		lanes = {{"kick", "X.........x.....|X.........x....."}, {"snare", "....x.......x..."},
			{"ride", "x.x.x.x.x.x.x.x.", gain = 0.3}, {"hat", ".x.x.x.x.x.x.x.x", gain = 0.25},
			{"ghost", ".......g.g.....g|.......g.g...g.g", when = "complexity"}}},
	{id = "dnb.drums.005", role = "drums", bars = 2, energy = 0.45, density = 0.5, flavours = {"jungle", "atmospheric"},
		tags = {"broken", "swung", "mixable", "hypnotic"},
		lanes = {{"kick", "X.........x.....|X.....x...x....."}, {"snare", "....x.......x..."},
			{"conga", "..x..x.x..x..x.x", gain = 0.5}, {"hat", "x.x.x.x.x.x.x.x.", gain = 0.3},
			{"tomLow", "......x.......x.|......x......xx.", gain = 0.4, when = "complexity"}}},
	{id = "dnb.drums.006", role = "drums", bars = 2, energy = 0.55, density = 0.55,
		tags = {"twostep", "driving"},
		lanes = {{"kick", "X.........x.....|X.........x....."}, {"snare", "....X.......X..."},
			{"hat", "..x...x...x...x.", gain = 0.75}, {"hat", "x...x...x...x...", gain = 0.35, light = false},
			{"openHat", "................|..............x.", gain = 0.5, light = false},
			{"ghost", ".......g.g.....g|.......g.g...g.g", when = "complexity"}}},
	{id = "dnb.drums.007", role = "drums", bars = 2, energy = 0.6, density = 0.6, flavours = {"liquid", "anthem", "jungle", "rollers"},
		tags = {"twostep", "syncopated", "swung"},
		lanes = {{"kick", "X.....x...x.....|X.........x..x.."}, {"snare", "....X.......X..."},
			{"hat", "..x...x...x...x.", gain = 0.7}, {"hat", ".x.x.x.x.x.x.x.x", gain = 0.22, when = "energy"},
			{"openHat", "......x.........|..............x.", gain = 0.4, light = false},
			{"rim", "...........x....|.......x........", gain = 0.5, when = "complexity"}}},
	{id = "dnb.drums.008", role = "drums", bars = 2, energy = 0.65, density = 0.7, flavours = {"rollers", "liquid", "anthem"},
		tags = {"rolling", "driving", "busy"},
		lanes = {{"kick", "X.........x.....|X......x..x....."}, {"snare", "....X.......X..."},
			{"hat", "xoxoxoxoxoxoxoxo", gain = 0.42}, {"ghost", ".g...g.g.g...g.g", gain = 0.9, light = false},
			{"ride", "x...x...x...x...", gain = 0.4, when = "energy"}, {"shaker", "..x...x...x...x.", gain = 0.5, when = "complexity"}}},
	{id = "dnb.drums.009", role = "drums", bars = 2, energy = 0.72, density = 0.65, flavours = {"neuro", "tearout", "rollers", "minimal"},
		tags = {"twostep", "syncopated", "dark", "driving"},
		lanes = {{"kick", "X..x......x.....|X..x......x.x..."}, {"snare", "....X.......X..."},
			{"hat", "x.x.x.x.x.x.x.x.", gain = 0.45}, {"ghost", "..g....g.g....g.", light = false},
			{"ride", "..x...x...x...x.", gain = 0.4, when = "energy"}, {"rim", ".....x.......x..", gain = 0.45, when = "complexity"}}},
	{id = "dnb.drums.010", role = "drums", bars = 2, energy = 0.8, density = 0.7, flavours = {"jumpup", "anthem"},
		tags = {"twostep", "syncopated", "aggressive", "driving"},
		lanes = {{"kick", "X.......x.x.....|X.......x.x..x.."}, {"snare", "....X.......X..."},
			{"clap", "....x.......x...", gain = 0.5, light = false}, {"hat", "x.x.x.x.x.x.x.x.", gain = 0.45},
			{"openHat", "..x...x...x...x.", gain = 0.4, when = "energy"}, {"ghost", ".......g.......g", when = "complexity"}}},
	{id = "dnb.drums.011", role = "drums", bars = 2, energy = 0.85, density = 0.8, flavours = {"neuro", "tearout"},
		tags = {"twostep", "aggressive", "dark", "busy"},
		lanes = {{"kick", "X.........x.....|X.....x...x....."}, {"snare", "....X.......X..."},
			{"clap", "....x.......x...", gain = 0.45}, {"hat", "x.xxx.xxx.xxx.xx", gain = 0.35},
			{"openHat", "..x.......x.....", gain = 0.35, light = false},
			{"ghost", ".......g.g....g.|.......g.....g.g", when = "complexity"}, {"shaker", "xxxxxxxxxxxxxxxx", gain = 0.25, when = "energy"}}},
	{id = "dnb.drums.012", role = "drums", bars = 2, energy = 0.9, density = 0.85, flavours = {"anthem", "jumpup", "rollers"},
		tags = {"twostep", "driving", "euphoric", "busy"},
		lanes = {{"kick", "X.....x...x.....|X.....x...x...x."}, {"snare", "....X.......X..."},
			{"clap", "....x.......x...", gain = 0.5}, {"hat", "x.x.x.x.x.x.x.x.", gain = 0.5},
			{"openHat", "..x...x...x...x.", gain = 0.45}, {"ride", "x...x...x...x...", gain = 0.35, when = "energy"},
			{"ghost", ".g.....g..g.....|.g...g..g.....g.", when = "complexity"}}},
	{id = "dnb.drums.013", role = "drums", bars = 1, energy = 0.5, density = 0.35, flavours = {"neuro", "halftime", "minimal", "tearout"},
		tags = {"halftime", "minimal", "sparse"},
		lanes = {{"kick", "X.........x....."}, {"kick", "...o............", when = "complexity"},
			{"snare", "........X......."}, {"hat", "....x...x...x...", gain = 0.75}}},
	{id = "dnb.drums.014", role = "drums", bars = 2, energy = 0.62, density = 0.55, flavours = {"halftime", "atmospheric", "liquid"},
		tags = {"halftime", "swung", "deep"},
		lanes = {{"kick", "X.....x.........|X.........x....."}, {"snare", "........X......."},
			{"hat", "x..x..x..x..x..x", gain = 0.4}, {"ghost", "..............g.|......g.......g.", light = false},
			{"rim", "....x.......x...", gain = 0.4, when = "complexity"}, {"openHat", "..........x.....", gain = 0.35, when = "energy"}}},
	{id = "dnb.drums.015", role = "drums", bars = 2, energy = 0.78, density = 0.65, flavours = {"halftime", "neuro", "tearout"},
		tags = {"halftime", "aggressive", "driving"},
		lanes = {{"kick", "X..........x....|X..x......x....."}, {"snare", "........X......."},
			{"clap", "........x.......", gain = 0.5}, {"hat", "..x...x...x...x.", gain = 0.5},
			{"shaker", "xoxoxoxoxoxoxoxo", gain = 0.3, when = "energy"}, {"ghost", ".....g.......g..", when = "complexity"}}},
	{id = "dnb.drums.016", role = "drums", bars = 4, energy = 0.95, density = 1.0, flavours = {"neuro", "jumpup", "anthem"},
		tags = {"twostep", "aggressive", "busy", "syncopated"},
		lanes = {{"kick", "X.........x.....|X..x......x.....|X.........x..x..|X..x....x.x.....|"},
			{"snare", "....X.......X...|....X.......X...|....X.......X...|....X.....X.X.XX"},
			{"hat", "x.xxx.xxx.xxx.xx", gain = 0.4}, {"openHat", "..x.......x.....", gain = 0.4},
			{"ghost", ".......g.g....g.|.g.....g.g.....|.......g.g...g.g|.g.g.g.g........."}}},
	{id = "dnb.drums.017", role = "drums", bars = 4, energy = 0.7, density = 0.7, flavours = {"jungle", "tearout"},
		tags = {"broken", "swung", "syncopated", "rolling"},
		lanes = {{"kick", "X.....x...x.....|X.........x.....|X.....x...x.....|X.........x..x.."},
			{"snare", "....X..g....X...|....X.......X.g.|....X..g....X...|....X.g.....X.XX"},
			{"hat", "x.x.x.x.x.x.x.x.", gain = 0.4}, {"tomLow", "................|..............x.|................|............xxx.", gain = 0.5, when = "complexity"}}},
	{id = "dnb.drums.018", role = "drums", bars = 1, energy = 0.3, density = 0.15, flavours = {"minimal", "atmospheric", "liquid"},
		tags = {"minimal", "sparse", "mixable", "straight"},
		lanes = {{"kick", "X.........x....."}, {"snare", "........x.......", gain = 0.4}, {"hat", "..x...x...x...x.", gain = 0.3}}},

	-- TOPS ----------------------------------------------------------------
	-- A second layer: hats, shakers, percussion and records' breaks.
	{id = "dnb.tops.001", role = "tops", bars = 1, energy = 0.3, density = 0.4, brightness = 0.9, tags = {"straight", "minimal", "mixable"},
		lanes = {{"shaker", "xoxoxoxoxoxoxoxo", gain = 0.3}, {"hat", "..x...x...x...x.", gain = 0.3}}},
	{id = "dnb.tops.002", role = "tops", bars = 2, energy = 0.4, density = 0.4, brightness = 0.8, flavours = {"liquid", "rollers", "atmospheric"},
		tags = {"swung", "soulful", "mixable"},
		lanes = {{"ride", "x.x.x.x.x.x.x.x.", gain = 0.35}, {"openHat", "................|..............x.", gain = 0.35},
			{"tambourine", "....x.......x...", gain = 0.3}}},
	{id = "dnb.tops.003", role = "tops", bars = 2, energy = 0.5, density = 0.5, flavours = {"jungle", "atmospheric", "tearout"},
		tags = {"broken", "hypnotic", "mixable"},
		lanes = {{"conga", "x.xo.xo.x.xo.xo.", gain = 0.5}, {"cowbell", "x.......x.......|x.......x.....x.", gain = 0.3},
			{"clave", "...x.....x..x...", gain = 0.3, when = "complexity"}}},
	{id = "dnb.tops.004", role = "tops", bars = 2, energy = 0.6, density = 0.7, brightness = 0.85, flavours = {"neuro", "rollers", "jumpup", "anthem"},
		tags = {"rolling", "busy", "driving"},
		lanes = {{"hat", "xoxoxoxoxoxoxoxo", gain = 0.3}, {"openHat", "..x...x...x...x.", gain = 0.3, when = "energy"},
			{"shaker", "xxxxxxxxxxxxxxxx", gain = 0.2}}},
	{id = "dnb.tops.005", role = "tops", bars = 4, energy = 0.82, density = 0.85, flavours = {"jungle", "tearout", "rollers", "anthem"},
		tags = {"break", "syncopated", "aggressive"}, kit = "break", bpm = 137, -- the Amen, resequenced
		lanes = {{"breakKick", "X.x.......x.....|X.x.......x.....|X.x.......x.....|..........xo...."},
			{"breakSnare", "....X..o.o..X..o|....X..o.o..X..o|....X..o.o....X.|..o.X..o.o....X."},
			{"breakRide", "x...x...x...x...", gain = 0.6}, {"breakRide", "..x...x...x...x.", gain = 0.45}}},
	{id = "dnb.tops.006", role = "tops", bars = 2, energy = 0.6, density = 0.65, flavours = {"liquid", "rollers", "jungle"},
		tags = {"break", "shuffle", "swung"}, kit = "break", bpm = 102,
		lanes = {{"breakKick", "X.x...x...x..x..|X.x...x...x..o.."}, {"breakSnare", "....X..g.g.gX..g|....X..g.g.gX.g."},
			{"breakHat", "XoxoXoxoXoxoXoxo", gain = 0.5}}},
	{id = "dnb.tops.007", role = "tops", bars = 2, energy = 0.55, density = 0.6, flavours = {"jungle", "atmospheric", "liquid"},
		tags = {"break", "playful", "swung"}, kit = "break", bpm = 112,
		lanes = {{"breakKick", "X.....x.x.......|X.....x.x....x.."}, {"breakSnare", "....X.......X...|....X.......X.g."},
			{"conga", "x.xo.xo.x.xo.xo.", gain = 0.6}, {"breakHat", "..x...x...x...x.", gain = 0.45}}},
	{id = "dnb.tops.008", role = "tops", bars = 1, energy = 0.7, density = 0.55, brightness = 0.8, flavours = {"jumpup", "anthem", "neuro"},
		tags = {"offbeat", "driving"},
		lanes = {{"openHat", "..x...x...x...x.", gain = 0.45}, {"hat", "x.x.x.x.x.x.x.x.", gain = 0.3}, {"clap", "....x.......x...", gain = 0.35}}},

	-- BASS ----------------------------------------------------------------
	-- Notes sit between the kicks (steps 0 and 10); long sub notes carry
	-- the quiet blocks, reese and wobble lines the loud ones.
	{id = "dnb.bass.001", role = "bass", bars = 2, energy = 0.2, density = 0.1, brightness = 0.1, octave = 0,
		flavours = {"minimal", "atmospheric", "liquid", "halftime"}, tags = {"sub", "pedal", "minimal", "deep", "sparse"},
		notes = "0:0:16 | 0:0:10 10:0:6"},
	{id = "dnb.bass.002", role = "bass", bars = 2, energy = 0.35, density = 0.25, brightness = 0.15,
		flavours = {"minimal", "atmospheric", "liquid", "rollers"}, tags = {"sub", "deep", "minimal"},
		notes = "0:0:8 10:0:2? 13:6:2 | 0:0:8 10:4:2? 12:2:3"},
	{id = "dnb.bass.003", role = "bass", bars = 2, energy = 0.55, density = 0.55, flavours = {"liquid", "anthem", "rollers"},
		tags = {"sub", "rolling", "soulful", "driving"},
		notes = "0:0:5 6:0:1? 8:7:1 10:6:2 13:4:2? | 0:0:6 8:2:1? 10:3:1 11:4:2 14:0:2+"},
	{id = "dnb.bass.004", role = "bass", bars = 2, energy = 0.5, density = 0.4, flavours = {"liquid", "atmospheric", "rollers"},
		tags = {"sub", "walking", "warm"},
		notes = "0:0:6 6:2:2 8:4:2 10:3:3 14:2:2 | 0:0:6 6:4:2 8:6:2 10:7:3 14:6:2"},
	{id = "dnb.bass.005", role = "bass", bars = 2, energy = 0.6, density = 0.5, flavours = {"liquid", "rollers", "anthem", "minimal"},
		tags = {"sub", "syncopated", "driving"},
		notes = "0:0:3 4:0:2? 7:7:2 10:0:3 14:6:2~? | 0:0:3 4:0:2? 7:4:2 10:6:3~ 14:4:2+"},
	{id = "dnb.bass.006", role = "bass", bars = 2, energy = 0.75, density = 0.6, flavours = {"jumpup", "anthem"},
		tags = {"octave", "driving", "playful", "pluck"},
		notes = "0:0:2 2:0:2 4:7:2! 8:0:2 10:0:1? 11:6:3~ | 0:0:2 2:0:2 4:7:2! 8:4:2 10:2:2? 12:0:4"},
	{id = "dnb.bass.007", role = "bass", bars = 2, energy = 0.85, density = 0.7, flavours = {"neuro", "tearout"},
		tags = {"reese", "dark", "aggressive", "syncopated"},
		notes = "0:0:3 3:0:1+ 4:7:2! 6:0:2 8:6:4~ 12:4:2? 14:1b:2~? | 0:0:3 3:0:1+ 4:7:2! 6:0:2 8:2:4~ 12:0:4"},
	{id = "dnb.bass.008", role = "bass", bars = 2, energy = 0.6, density = 0.3, flavours = {"halftime", "neuro", "tearout", "minimal"},
		tags = {"sub", "pedal", "dark", "sparse", "halftime"},
		notes = "0:0:12 12:6:4~ | 0:0:8 8:2:4? 12:4:4~"},
	{id = "dnb.bass.009", role = "bass", bars = 2, energy = 0.7, density = 0.65, flavours = {"jungle", "neuro", "jumpup", "rollers"},
		tags = {"stab", "syncopated", "tense"},
		notes = "0:0:2 3:0:2 6:0:2 10:7:2? 12:6:2 | 0:0:2 3:0:2 6:0:2 10:4:2? 12:2:2 14:0:2+"},
	{id = "dnb.bass.010", role = "bass", bars = 2, energy = 0.8, density = 0.5, flavours = {"halftime", "jumpup", "neuro"},
		tags = {"wobble", "aggressive", "halftime"},
		notes = "0:0:4w2 4:0:4w4 8:7:4w3? 12:6:4w2 | 0:0:6w2 6:0:2w6 8:4:4w3? 12:0:4w4"},
	{id = "dnb.bass.011", role = "bass", bars = 1, energy = 0.45, density = 0.5, flavours = {"jungle", "minimal", "tearout", "atmospheric"},
		tags = {"sub", "rolling", "pedal", "hypnotic"},
		notes = "0:0:3 4:0:2 7:0:2 10:0:3 14:7:2"},
	{id = "dnb.bass.012", role = "bass", bars = 2, energy = 0.65, density = 0.45, flavours = {"jungle", "tearout", "atmospheric"},
		tags = {"sub", "reggae", "pedal", "dark", "swung"},
		notes = "0:0:7 8:0:2 11:7:2 13:6:3 | 0:0:6 6:0:2 8:0:6 14:6:2"},
	{id = "dnb.bass.013", role = "bass", bars = 2, energy = 0.9, density = 0.8, flavours = {"neuro", "tearout"},
		tags = {"reese", "aggressive", "busy", "dark"},
		notes = "0:0:2 2:0:1 3:0:1+ 4:7:1! 6:0:2 8:1b:2~ 10:0:2 12:6:1 13:7:1 14:0:2 | 0:0:2 2:0:1 3:0:1+ 4:7:2! 6:0:2 8:4:2~ 10:3:1 11:2:1 12:0:4"},
	{id = "dnb.bass.014", role = "bass", bars = 4, energy = 0.7, density = 0.55, flavours = {"anthem", "liquid", "rollers"},
		tags = {"sub", "rolling", "driving", "euphoric"},
		notes = "0:0:4 6:0:2 8:7:2 10:6:2 13:4:3 | 0:0:4 6:0:2 8:7:2 10:9:2 13:7:3 | 0:0:4 6:0:2 8:7:2 10:6:2 13:4:3 | 0:2:4 6:3:2 8:4:2 10:2:2 12:0:4"},
	{id = "dnb.bass.015", role = "bass", bars = 2, energy = 0.4, density = 0.35, flavours = {"liquid", "atmospheric"},
		tags = {"sub", "walking", "soulful", "melancholic"},
		notes = "0:0:8 8:6:2 10:4:2 12:3:4 | 0:0:6 6:2:2 8:3:3 11:4:2 13:2:3"},
	{id = "dnb.bass.016", role = "bass", bars = 2, energy = 1.0, density = 0.9, flavours = {"jumpup", "neuro"},
		tags = {"wobble", "aggressive", "busy", "stab"},
		notes = "0:0:1w4 1:0:1w4 2:0:2w2 4:7:2w3! 6:0:2 8:6:2w4 10:0:1 11:0:1 12:4:2w2 14:2:2w3 | 0:0:1w4 1:0:1w4 2:0:2w2 4:7:2w3! 6:0:2 8:4:2w4 10:6:1 11:7:1 12:9:2w2 14:7:2w3"},

	-- PAD -----------------------------------------------------------------
	{id = "dnb.pad.001", role = "pad", bars = 4, energy = 0.2, density = 0.1, brightness = 0.35, hold = true, tags = {"held", "ambient", "warm", "dreamy"}},
	{id = "dnb.pad.002", role = "pad", bars = 2, energy = 0.35, density = 0.2, hold = true, flavours = {"atmospheric", "liquid", "halftime"}, tags = {"held", "ambient", "deep", "melancholic"}},
	{id = "dnb.pad.003", role = "pad", bars = 2, energy = 0.5, density = 0.3, comp = "0:10 10:6", tags = {"chordal", "warm", "soulful"}, flavours = {"liquid", "rollers", "anthem"}},
	{id = "dnb.pad.004", role = "pad", bars = 2, energy = 0.6, density = 0.4, comp = "0:6! 8:8", tags = {"chordal", "euphoric", "bright"}, flavours = {"anthem", "liquid"}},
	{id = "dnb.pad.005", role = "pad", bars = 1, energy = 0.75, density = 0.5, comp = "0:3 3:3 6:3! 10:6", brightness = 0.7, tags = {"rhythmic", "driving", "euphoric", "syncopated"}, flavours = {"anthem", "rollers"}},
	{id = "dnb.pad.006", role = "pad", bars = 4, energy = 0.3, density = 0.15, hold = true, brightness = 0.2, flavours = {"neuro", "tearout", "jungle", "minimal"}, tags = {"held", "dark", "tense", "ambient"}},
	{id = "dnb.pad.007", role = "pad", bars = 2, energy = 0.8, density = 0.55, comp = "2:4 6:2! 10:4 14:2", tags = {"rhythmic", "tense", "dark"}, flavours = {"neuro", "rollers"}},

	-- KEYS ----------------------------------------------------------------
	{id = "dnb.keys.001", role = "keys", bars = 2, energy = 0.25, density = 0.15, comp = "0:8 10:6", flavours = {"liquid", "atmospheric", "halftime"}, tags = {"chordal", "soulful", "sparse", "warm"}},
	{id = "dnb.keys.002", role = "keys", bars = 2, energy = 0.4, density = 0.3, comp = "0:5 6:3 10:4 14:2", flavours = {"liquid", "rollers"}, tags = {"chordal", "soulful", "warm", "syncopated"}},
	{id = "dnb.keys.003", role = "keys", bars = 2, energy = 0.5, density = 0.4, comp = "3:3 6:2 11:3 14:2", tags = {"offbeat", "syncopated", "playful"}},
	{id = "dnb.keys.004", role = "keys", bars = 1, energy = 0.6, density = 0.5, comp = "0:2 3:2 6:3! 10:2 12:4", flavours = {"liquid", "rollers", "jumpup"}, tags = {"rhythmic", "playful", "bright"}},
	{id = "dnb.keys.005", role = "keys", bars = 2, energy = 0.7, density = 0.6, comp = "0:3! 4:2 6:2 10:3! 14:2", flavours = {"anthem", "rollers", "jumpup"}, tags = {"rhythmic", "driving", "bright", "busy"}},
	{id = "dnb.keys.006", role = "keys", bars = 4, energy = 0.3, density = 0.1, comp = "0:16", flavours = {"atmospheric", "halftime", "minimal"}, tags = {"held", "dreamy", "melancholic", "sparse"}},

	-- STAB ----------------------------------------------------------------
	{id = "dnb.stab.001", role = "stab", bars = 2, energy = 0.3, density = 0.12, comp = "6:2", flavours = {"minimal", "halftime", "atmospheric"}, tags = {"sparse", "minimal", "deep"}},
	{id = "dnb.stab.002", role = "stab", bars = 2, energy = 0.45, density = 0.2, comp = "3:1 11:2?", tags = {"offbeat", "syncopated", "sparse"}},
	{id = "dnb.stab.003", role = "stab", bars = 2, energy = 0.55, density = 0.3, comp = "2:1 6:1 10:1 14:1", flavours = {"anthem", "rollers", "jungle"}, tags = {"offbeat", "rhythmic", "playful"}},
	{id = "dnb.stab.004", role = "stab", bars = 1, energy = 0.65, density = 0.4, comp = "0:1! 3:1 6:2 10:1?", flavours = {"neuro", "jumpup", "tearout"}, tags = {"rhythmic", "tense", "aggressive"}},
	{id = "dnb.stab.005", role = "stab", bars = 2, energy = 0.75, density = 0.45, comp = "0:2! 3:1 6:1 8:2! 11:1 14:1", flavours = {"jumpup", "jungle", "anthem"}, tags = {"rhythmic", "bright", "playful", "driving"}},
	{id = "dnb.stab.006", role = "stab", bars = 4, energy = 0.5, density = 0.25, comp = "10:3", flavours = {"jungle", "tearout", "neuro"}, tags = {"sparse", "dark", "tense"}},
	{id = "dnb.stab.007", role = "stab", bars = 1, energy = 0.9, density = 0.7, comp = "0:1! 2:1 3:1! 6:1 8:1! 10:1 11:1! 14:1", flavours = {"jumpup", "neuro"}, tags = {"busy", "aggressive", "rhythmic"}},

	-- ARP -----------------------------------------------------------------
	{id = "dnb.arp.001", role = "arp", bars = 2, energy = 0.25, density = 0.25, order = {1, 2, 3, 4, 3, 2}, rate = 4, gate = 0.9, octave = 1,
		mask = "XxxxXxxxXxxxXxxx", flavours = {"atmospheric", "halftime", "liquid"}, tags = {"arpeggio", "ambient", "dreamy", "sparse"}},
	{id = "dnb.arp.002", role = "arp", bars = 2, energy = 0.4, density = 0.4, order = {1, 3, 2, 4}, rate = 2, gate = 0.6, octave = 1,
		mask = "XXxxXXxxXXxxXXxx", flavours = {"liquid", "atmospheric"}, tags = {"arpeggio", "stepwise", "warm"}},
	{id = "dnb.arp.003", role = "arp", bars = 1, energy = 0.55, density = 0.6, order = {1, 2, 3, 4, 3, 2, 1, 3}, rate = 2, gate = 0.5, octave = 1,
		mask = "XXXXXXXXXXXXXXXX", tags = {"arpeggio", "driving", "bright"}},
	{id = "dnb.arp.004", role = "arp", bars = 1, energy = 0.7, density = 0.75, order = {1, 3, 5, 3, 4, 2}, rate = 1, gate = 0.45, octave = 2,
		mask = "XXxxXXxxXXxxXXxx", flavours = {"anthem", "neuro", "rollers"}, tags = {"arpeggio", "leap", "euphoric", "busy"}},
	{id = "dnb.arp.005", role = "arp", bars = 2, energy = 0.6, density = 0.5, order = {1, 4, 2, 5, 3, 4}, rate = 2, gate = 0.55, octave = 1,
		mask = "X.XXX.XXX.XXX.XX", flavours = {"neuro", "jumpup", "rollers"}, tags = {"arpeggio", "syncopated", "tense"}},
	{id = "dnb.arp.006", role = "arp", bars = 1, energy = 0.85, density = 0.9, order = {1, 2, 3, 4, 5, 4, 3, 2}, rate = 1, gate = 0.4, octave = 2,
		mask = "XXXXXXXXXXXXXXXX", flavours = {"anthem", "neuro"}, tags = {"arpeggio", "busy", "bright", "aggressive"}},
	{id = "dnb.arp.007", role = "arp", bars = 2, energy = 0.35, density = 0.3, order = {3, 2, 1, 2}, rate = 4, gate = 0.8, octave = 2,
		mask = "XxxxXxxxXxxxXx..", flavours = {"minimal", "atmospheric", "liquid"}, tags = {"arpeggio", "sparse", "dreamy"}},

	-- LEAD ----------------------------------------------------------------
	-- Hooks: a stated idea, repeated, turned and brought home.
	{id = "dnb.lead.001", role = "lead", bars = 4, energy = 0.4, density = 0.2, flavours = {"minimal", "liquid", "atmospheric", "halftime"},
		tags = {"hook", "vocal", "melancholic", "stepwise", "sparse"},
		notes = "0:4:8 8:6:6~ | 0:7:10 12:6:4~ | 0:4:8 8:2:6~ | 0:0:12"},
	{id = "dnb.lead.002", role = "lead", bars = 4, energy = 0.5, density = 0.3, flavours = {"liquid", "atmospheric"},
		tags = {"hook", "dreamy", "soulful", "stepwise"},
		notes = "0:2:6 6:4:2~ 8:2:4 12:0:4 | 0:2:6 6:4:2~ 8:6:8 | 0:7:6 6:6:2~ 8:4:4 12:2:4 | 0:1:4 4:2:4~ 8:0:8"},
	{id = "dnb.lead.003", role = "lead", bars = 4, energy = 0.6, density = 0.35, flavours = {"atmospheric", "liquid", "halftime"},
		tags = {"hook", "melancholic", "stepwise", "held"},
		notes = "0:7:4 4:6:4 8:5:4 12:4:4 | 0:4:8 10:2:2 12:3:4 | 0:6:4 4:5:4 8:4:4 12:2:4 | 0:2:4 4:1:4 8:0:8"},
	{id = "dnb.lead.004", role = "lead", bars = 4, energy = 0.85, density = 0.5, flavours = {"anthem"},
		tags = {"hook", "euphoric", "held", "leap", "bright"},
		notes = "0:4:6 6:5:2 8:4:4 12:2:4 | 0:4:6 6:5:2 8:6:4 12:7:4 | 0:8:6 6:7:2 8:6:4 12:4:4 | 0:4:4 4:2:4 8:0:8~"},
	{id = "dnb.lead.005", role = "lead", bars = 4, energy = 0.75, density = 0.5, flavours = {"anthem", "liquid"},
		tags = {"hook", "arpeggio", "euphoric", "leap"},
		notes = "0:0:2 2:2:2 4:4:2 6:7:2 8:4:2 10:2:2 12:4:4 | 0:0:2 2:2:2 4:4:2 6:7:2 8:9:4 12:7:4 | 0:0:2 2:2:2 4:4:2 6:7:2 8:4:2 10:2:2 12:4:4 | 0:7:2 2:4:2 4:2:2 6:0:2 8:0:8"},
	{id = "dnb.lead.006", role = "lead", bars = 4, energy = 0.7, density = 0.55, follow = "key", flavours = {"jungle", "tearout", "neuro"},
		tags = {"hook", "riff", "dark", "hypnotic", "rhythmic"},
		notes = "0:0:2 3:2:2 6:3:2 10:4:3 14:6:2 | 0:4:3 3:3:2 6:2:2 10:0:4 | 0:0:2 3:2:2 6:3:2 10:4:3 14:6:2 | 0:4:3 3:6:2 6:7:2 10:4:6"},
	{id = "dnb.lead.007", role = "lead", bars = 4, energy = 0.8, density = 0.6, follow = "key", flavours = {"tearout", "jumpup", "jungle"},
		tags = {"hook", "riff", "playful", "rhythmic", "syncopated"},
		notes = "0:4:1 2:4:1 3:4:2 6:6:2 8:4:2 11:2:2 14:4:2 | 0:4:1 2:4:1 3:4:2 6:7:2 8:6:2 11:4:4 | 0:4:1 2:4:1 3:4:2 6:6:2 8:4:2 11:2:2 14:4:2 | 0:2:1 2:2:1 3:2:2 6:3:2 8:0:6"},
	{id = "dnb.lead.008", role = "lead", bars = 4, energy = 0.55, density = 0.3, flavours = {"minimal", "jungle", "rollers"},
		tags = {"hook", "answer", "sparse", "stepwise"},
		notes = "0:7:3 3:6:1 4:4:4 | 8:2:2 10:3:2 12:4:4 | 0:7:3 3:6:1 4:4:4 | 8:4:2 10:2:2 12:0:4"},
	{id = "dnb.lead.009", role = "lead", bars = 2, energy = 0.7, density = 0.5, follow = "key", flavours = {"neuro", "tearout", "jumpup"},
		tags = {"riff", "aggressive", "dark", "rhythmic"},
		notes = "0:7:1 1:7:1 3:7:1 6:7:2 10:6:1 11:6:1 14:4:2 | 0:7:1 1:7:1 3:7:1 6:9:2 10:7:4"},
	{id = "dnb.lead.010", role = "lead", bars = 4, energy = 0.65, density = 0.45, flavours = {"liquid", "anthem", "rollers"},
		tags = {"hook", "vocal", "soulful", "leap"},
		notes = "0:0:2 2:2:2 4:4:3 8:6:6~ | 4:4:2 6:2:2 8:0:6 | 0:0:2 2:2:2 4:4:3 8:7:6~ | 4:6:2 6:4:2 8:2:2+ 10:0:6"},
	{id = "dnb.lead.011", role = "lead", bars = 2, energy = 0.9, density = 0.65, follow = "key", flavours = {"tearout", "jumpup", "neuro"},
		tags = {"riff", "aggressive", "octave", "playful"},
		notes = "0:0:2 2:7:2 4:0:2 6:7:2 8:6:2 10:4:4 | 0:0:2 2:7:2 4:0:2 6:7:2 8:9:2 10:7:4"},
	{id = "dnb.lead.012", role = "lead", bars = 4, energy = 0.3, density = 0.15, flavours = {"atmospheric", "halftime", "minimal"},
		tags = {"hook", "sparse", "ambient", "held", "melancholic"},
		notes = "0:4:6 6:3:2~ 8:2:8 | 0:6:6 6:5:2~ 8:4:8 | 0:4:6 6:3:2~ 8:2:4 12:1:4 | 0:0:12"},
	{id = "dnb.lead.013", role = "lead", bars = 2, energy = 0.5, density = 0.4, follow = "key", flavours = {"minimal", "liquid", "rollers", "jungle"},
		tags = {"riff", "offbeat", "playful", "syncopated"},
		notes = "2:7:2 6:6:2 10:4:2 14:6:2 | 2:7:2 6:9:2 10:7:2 14:4:2"},
	{id = "dnb.lead.014", role = "lead", bars = 4, energy = 0.95, density = 0.7, flavours = {"anthem", "jumpup"},
		tags = {"hook", "euphoric", "bright", "busy", "leap"},
		notes = "0:7:2 2:9:2 4:11:4 8:9:2 10:7:2 12:9:4 | 0:7:2 2:9:2 4:11:4 8:12:2 10:11:2 12:9:4 | 0:7:2 2:9:2 4:11:4 8:9:2 10:7:2 12:4:4 | 0:4:4 4:6:4 8:7:8~"},
	{id = "dnb.lead.015", role = "lead", bars = 2, energy = 0.45, density = 0.25, flavours = {"atmospheric", "liquid", "halftime"},
		tags = {"hook", "answer", "dreamy", "stepwise"},
		notes = "0:4:4 4:6:2 6:7:6~ | 0:6:4 4:4:4 8:2:8"},

	-- COUNTER -------------------------------------------------------------
	{id = "dnb.counter.001", role = "counter", bars = 4, energy = 0.25, density = 0.1, flavours = {"minimal", "atmospheric", "liquid"},
		tags = {"answer", "sparse", "ambient", "dreamy"}, notes = "| 10:4:3 | | 12:2:4"},
	{id = "dnb.counter.002", role = "counter", bars = 2, energy = 0.45, density = 0.25, tags = {"answer", "stepwise", "melancholic"},
		notes = "12:6:2 14:4:2 | 8:2:2 10:3:2 12:0:4"},
	{id = "dnb.counter.003", role = "counter", bars = 2, energy = 0.6, density = 0.4, flavours = {"anthem", "liquid", "jumpup"},
		tags = {"answer", "bright", "playful", "leap"}, notes = "8:7:1 9:9:1 10:7:2 13:4:3 | 8:4:1 9:6:1 10:7:2 13:9:3"},
	{id = "dnb.counter.004", role = "counter", bars = 4, energy = 0.5, density = 0.2, follow = "key", flavours = {"minimal", "jungle", "neuro", "tearout"},
		tags = {"answer", "sparse", "dark", "hypnotic"}, notes = "6:7:1 | 10:6:1 | 6:7:1 14:4:1 | 10:2:2"},
	{id = "dnb.counter.005", role = "counter", bars = 2, energy = 0.75, density = 0.55, flavours = {"anthem", "neuro", "jumpup"},
		tags = {"answer", "arpeggio", "euphoric", "busy"}, notes = "8:4:1 9:7:1 10:9:1 11:7:1 12:11:3 | 8:9:1 9:7:1 10:4:1 11:2:1 12:0:4"},

	-- TEXTURE -------------------------------------------------------------
	{id = "dnb.texture.001", role = "texture", bars = 4, energy = 0.2, density = 0.1, brightness = 0.3, voices = {0, 7}, every = 4, tags = {"ambient", "deep", "dark"}},
	{id = "dnb.texture.002", role = "texture", bars = 4, energy = 0.3, density = 0.15, brightness = 0.7, voices = {7, 12, 16}, every = 4, flavours = {"atmospheric", "liquid", "halftime"}, tags = {"ambient", "dreamy", "bright"}},
	{id = "dnb.texture.003", role = "texture", bars = 8, energy = 0.4, density = 0.2, brightness = 0.4, voices = {0, 3, 7}, every = 8, flavours = {"neuro", "tearout", "minimal"}, tags = {"ambient", "dark", "tense"}},
	{id = "dnb.texture.004", role = "texture", bars = 2, energy = 0.5, density = 0.3, brightness = 0.5, voices = {0, 5}, every = 2, flavours = {"jungle", "tearout"}, tags = {"hypnotic", "dark", "ambient"}},
	{id = "dnb.texture.005", role = "texture", bars = 4, energy = 0.25, density = 0.1, brightness = 0.2, voices = {-12, 0}, every = 4, flavours = {"minimal", "halftime"}, tags = {"deep", "ambient", "sparse"}},

	-- FX ------------------------------------------------------------------
	-- Risers lead into a drop at the start of a phrase; impacts mark it.
	{id = "dnb.fx.001", role = "fx", bars = 8, energy = 0.5, density = 0.4, brightness = 0.9, kind = "riser", tags = {"tense"}},
	{id = "dnb.fx.002", role = "fx", bars = 4, energy = 0.7, density = 0.5, brightness = 0.95, kind = "riser", flavours = {"neuro", "jumpup", "anthem", "tearout"}, tags = {"tense", "aggressive"}},
	{id = "dnb.fx.003", role = "fx", bars = 8, energy = 0.4, density = 0.2, brightness = 0.7, kind = "riser", flavours = {"liquid", "atmospheric", "halftime"}, tags = {"dreamy", "ambient"}},
	{id = "dnb.fx.004", role = "fx", bars = 2, energy = 0.8, density = 0.5, brightness = 0.8, kind = "riser", flavours = {"anthem", "jumpup", "rollers"}, tags = {"euphoric", "bright"}},
	{id = "dnb.fx.005", role = "fx", bars = 1, energy = 0.9, density = 0.6, brightness = 0.3, kind = "impact", tags = {"aggressive", "dark"}},
	{id = "dnb.fx.006", role = "fx", bars = 1, energy = 0.7, density = 0.4, brightness = 0.6, kind = "impact", flavours = {"liquid", "atmospheric", "minimal"}, tags = {"deep", "ambient"}},
	{id = "dnb.fx.007", role = "fx", bars = 2, energy = 0.5, density = 0.3, brightness = 0.5, kind = "downlifter", tags = {"ambient"}},
	{id = "dnb.fx.008", role = "fx", bars = 4, energy = 0.4, density = 0.2, brightness = 0.4, kind = "downlifter", flavours = {"liquid", "atmospheric", "minimal", "halftime"}, tags = {"dreamy", "ambient"}},
	{id = "dnb.fx.009", role = "fx", bars = 1, energy = 0.6, density = 0.3, brightness = 0.9, kind = "crash", tags = {"bright"}},
	{id = "dnb.fx.010", role = "fx", bars = 1, energy = 1.0, density = 0.7, brightness = 0.5, kind = "impact", flavours = {"neuro", "jumpup", "tearout", "anthem"}, tags = {"aggressive", "driving"}},
}
