-- Drum & bass: an endless DJ set at 160–176 BPM. Two-step grooves with
-- ghost notes, breaks layered and chopped over the programmed kit, rolling
-- bass under voice-led extended chords. Its flavours are not shades of one
-- tune but different records: a liquid roller carried by an electric piano,
-- an anthem with a lead and its answer, a jungle tune that opens on the raw
-- Amen, neurofunk with nothing sweet in it, a minimal stepper on five
-- channels, a half-time tune, a jump-up wobbler, and one that is mostly air.

-- Scale degrees, one chord per two bars.
local PROGRESSIONS = {
	{1, 6, 3, 7}, {1, 4, 6, 5}, {1, 7, 6, 7}, {1, 1, 4, 6},
	{6, 7, 1, 1}, {1, 3, 6, 7}, {1, 6, 4, 5}, {4, 6, 1, 7},
	{1, 4, 7, 3}, {6, 4, 1, 5}, {1, 2, 6, 7}, {4, 5, 3, 6},
}
-- A tune that lives on one chord, or two.
local STATIC = {{1, 1, 1, 1}, {1, 1, 6, 6}, {1, 7, 1, 7}, {1, 1, 1, 7}}

local BEATS = {
	{id = "dnb.twostep", name = "Two-Step", bars = 2, lanes = {
		{"kick", "X.........x.....|X.........x....."},
		{"snare", "....X.......X..."},
		{"hat", "..x...x...x...x.", gain = 0.75},
		{"hat", "x...x...x...x...", gain = 0.35, light = false},
		{"hat", ".x.x.x.x.x.x.x.x", gain = 0.22, when = "energy"},
		{"openHat", "................|..............x.", gain = 0.5, light = false},
		{"ride", "..o.o.o.o.o.o.o.", gain = 0.7, light = false},
		{"ghost", ".......g.g.....g|.......g.g...g.g", when = "complexity"},
	}},
	{id = "dnb.skip", name = "Skip", bars = 2, lanes = {
		{"kick", "X.....x...x.....|X.........x..x.."},
		{"snare", "....X.......X..."},
		{"hat", "..x...x...x...x.", gain = 0.7},
		{"hat", "x...x...x...x...", gain = 0.35, light = false},
		{"hat", ".x.x.x.x.x.x.x.x", gain = 0.22, when = "energy"},
		{"openHat", "......x.........|..............x.", gain = 0.4, light = false},
		{"ghost", ".........g.....g|.g.......g......", when = "complexity"},
		{"rim", "...........x....|.......x........", gain = 0.5, when = "complexity"},
	}},
	{id = "dnb.roller", name = "Roller", bars = 2, lanes = {
		{"kick", "X.........x.....|X......x..x....."},
		{"snare", "....X.......X..."},
		{"hat", "xoxoxoxoxoxoxoxo", gain = 0.42},
		{"ghost", ".g...g.g.g...g.g", gain = 0.9, light = false},
		{"ride", "x...x...x...x...", gain = 0.4, when = "energy"},
		{"shaker", "..x...x...x...x.", gain = 0.5, when = "complexity"},
	}},
	{id = "dnb.steppa", name = "Steppa", bars = 1, lanes = {
		{"kick", "X.........X....."},
		{"snare", "....X.......X..."},
		{"hat", "x.x.x.x.x.x.x.x.", gain = 0.4},
		{"rim", "......x......x..", gain = 0.5, when = "complexity"},
		{"openHat", "..............x.", gain = 0.35, when = "energy"},
	}},
	{id = "dnb.jump", name = "Jump-Up", bars = 2, lanes = {
		{"kick", "X.......x.x.....|X.......x.x..x.."},
		{"snare", "....X.......X..."},
		{"clap", "....x.......x...", gain = 0.5, light = false},
		{"hat", "x.x.x.x.x.x.x.x.", gain = 0.45},
		{"openHat", "..x...x...x...x.", gain = 0.4, when = "energy"},
		{"ghost", ".......g.......g", when = "complexity"},
	}},
	{id = "dnb.tech", name = "Techstep", bars = 2, lanes = {
		{"kick", "X..x......x.....|X..x......x.x..."},
		{"snare", "....X.......X..."},
		{"hat", "x.x.x.x.x.x.x.x.", gain = 0.45},
		{"ghost", "..g....g.g....g.", light = false},
		{"ride", "..x...x...x...x.", gain = 0.4, when = "energy"},
		{"rim", ".....x.......x..", gain = 0.45, when = "complexity"},
	}},
	{id = "dnb.neuro", name = "Neuro", bars = 2, lanes = {
		{"kick", "X.........x.....|X.....x...x....."},
		{"snare", "....X.......X..."},
		{"clap", "....x.......x...", gain = 0.45},
		{"hat", "x.xxx.xxx.xxx.xx", gain = 0.35},
		{"openHat", "..x.......x.....", gain = 0.35, light = false},
		{"ghost", ".......g.g....g.|.......g.....g.g", when = "complexity"},
		{"shaker", "xxxxxxxxxxxxxxxx", gain = 0.25, when = "energy"},
	}},
	{id = "dnb.soft", name = "Soft Step", bars = 2, lanes = {
		{"kick", "X.........x.....|X.........x....."},
		{"snare", "....x.......x..."},
		{"rim", "....x.......x...", gain = 0.5},
		{"hat", "..x...x...x...x.", gain = 0.55},
		{"ride", "x.x.x.x.x.x.x.x.", gain = 0.3, light = false},
		{"shaker", "xoxoxoxoxoxoxoxo", gain = 0.3, when = "energy"},
		{"ghost", ".........g.....g|.......g.g......", when = "complexity"},
	}},
	{id = "dnb.tribal", name = "Tribal", bars = 2, lanes = {
		{"kick", "X.........x.....|X.....x...x....."},
		{"snare", "....X.......X..."},
		{"conga", "..x..x.x..x..x.x", gain = 0.55},
		{"hat", "x.x.x.x.x.x.x.x.", gain = 0.35},
		{"tomLow", "......x.......x.|......x......xx.", gain = 0.5, when = "complexity"},
		{"cowbell", "x.......x.......", gain = 0.35, when = "energy"},
	}},
	-- The switch-up inside a drop: the snare moves to beat three.
	{id = "dnb.half", name = "Half-Time", bars = 1, lanes = {
		{"kick", "X.........x....."},
		{"kick", "...o............", when = "complexity"},
		{"snare", "........X......."},
		{"hat", "....x...x...x...", gain = 0.75},
	}},
	{id = "dnb.halfstep", name = "Halfstep", bars = 2, lanes = {
		{"kick", "X.....x.........|X.........x....."},
		{"snare", "........X......."},
		{"hat", "x..x..x..x..x..x", gain = 0.4},
		{"ghost", "..............g.|......g.......g.", light = false},
		{"rim", "....x.......x...", gain = 0.4, when = "complexity"},
		{"openHat", "..........x.....", gain = 0.35, when = "energy"},
	}},
	{id = "dnb.halfswing", name = "Half Swing", bars = 2, lanes = {
		{"kick", "X..........x....|X..x......x....."},
		{"snare", "........X......."},
		{"clap", "........x.......", gain = 0.5},
		{"hat", "..x...x...x...x.", gain = 0.5},
		{"shaker", "xoxoxoxoxoxoxoxo", gain = 0.3, when = "energy"},
		{"ghost", ".....g.......g..", when = "complexity"},
	}},
}

local LINES = {
	{id = "dnb.roll", name = "Roll", notes = "0:0:5 6:0:1? 8:7:1 10:6:2 13:4:2? | 0:0:6 8:2:1? 10:3:1 11:4:2 14:0:2+"},
	{id = "dnb.deep", name = "Deep", notes = "0:0:8 10:0:2? 13:6:2 | 0:0:8 10:4:2? 12:2:3"},
	{id = "dnb.step", name = "Step", notes = "0:0:3 4:0:2? 7:7:2 10:0:3 14:6:2~? | 0:0:3 4:0:2? 7:4:2 10:6:3~ 14:4:2+"},
	{id = "dnb.jump", name = "Jump", notes = "0:0:2 2:0:2 4:7:2! 8:0:2 10:0:1? 11:6:3~ | 0:0:2 2:0:2 4:7:2! 8:4:2 10:2:2? 12:0:4"},
	{id = "dnb.neuro", name = "Neuro", notes = "0:0:3 3:0:1+ 4:7:2! 6:0:2 8:6:4~ 12:4:2? 14:1b:2~? | 0:0:3 3:0:1+ 4:7:2! 6:0:2 8:2:4~ 12:0:4"},
	{id = "dnb.half", name = "Half", notes = "0:0:12 12:6:4~ | 0:0:8 8:2:4? 12:4:4~"},
	{id = "dnb.stab", name = "Stab", notes = "0:0:2 3:0:2 6:0:2 10:7:2? 12:6:2 | 0:0:2 3:0:2 6:0:2 10:4:2? 12:2:2 14:0:2+"},
	{id = "dnb.wob", name = "Wob", notes = "0:0:4w2 4:0:4w4 8:7:4w3? 12:6:4w2 | 0:0:6w2 6:0:2w6 8:4:4w3? 12:0:4w4"},
}

local FILLS = {"fill.roll", "fill.toms", "fill.stutter", "fill.snares", "@stutter", "@cut", "@reverse", "@retrig"}
local BREAKS = {"break.amen", "break.funk", "break.shuffle", "break.tambourine"}

local FLAVOURS = {
	-- Carried by the electric piano; the break arrives with the second drop.
	{id = "liquid", name = "Liquid", tempo = {170, 175}, swing = {0.08, 0.16}, halftime = 0.25,
		snares = {"roomy", "tight", "layered", "vintage"},
		channels = {
			{role = "drums", beats = {"dnb.soft", "dnb.twostep", "dnb.skip"}},
			{role = "tops", beats = BREAKS, gain = 0.45, chops = true, chance = 0.7},
			{role = "bass", patches = {"bass.round", "bass.sub", "bass.reese", "bass.upright"},
				lines = {"@roll", "dnb.roll", "dnb.deep", "line.walk"}},
			{role = "pad", patches = {"pad.warm", "pad.saw", "pad.strings", "pad.glass"}},
			{role = "keys", patches = {"keys.rhodes", "keys.wurli", "keys.vibes", "keys.harp"}},
			{role = "arp", patches = {"pluck.bell", "pluck.glass", "pluck.saw"}, chance = 0.6},
			{role = "lead", patches = {"lead.sine", "lead.flute", "lead.vox", "lead.saw"}, chance = 0.7,
				hooks = {"hook.voice", "hook.lullaby", "hook.sigh", "hook.question", "@motif", "@motif"}},
			{role = "fx", patches = {"fx.riser", "fx.wind"}},
		},
		plan = {drop = {tops = {"tops.loop", cycle = 1}}, outro = {tops = {"tops.loop", cycle = 1}},
			intro = {keys = {"keys.comp", from = "blend"}}}},
	-- A lead, the voice that answers it, and a wall of pads.
	{id = "anthem", name = "Anthem", tempo = {172, 176}, swing = {0.04, 0.1}, halftime = 0.2,
		snares = {"tight", "layered", "fat", "roomy"},
		channels = {
			{role = "drums", beats = {"dnb.twostep", "dnb.skip", "dnb.roller"}},
			{role = "bass", patches = {"bass.reese", "bass.pluck", "bass.moog"}, lines = {"@roll", "dnb.roll", "dnb.step", "@cell"}},
			{role = "pad", patches = {"pad.supersaw", "pad.strings", "pad.pwm"}},
			{role = "stab", patches = {"stab.saw", "stab.piano", "stab.pizzicato"}, chance = 0.5},
			{role = "arp", patches = {"pluck.trance", "pluck.saw", "pluck.chip"}, arp = {rates = {1, 2}}},
			{role = "lead", patches = {"lead.supersaw", "lead.saw", "lead.square", "lead.fm"},
				hooks = {"hook.anthem", "hook.ascent", "hook.leap", "hook.arpeggio", "hook.circle", "@motif"}},
			{role = "counter", patches = {"pluck.bell", "pluck.glass", "keys.vibes"}, chance = 0.7},
			{role = "fx", patches = {"fx.riser", "fx.siren"}},
		},
		plan = {drop = {lead = {{"lead.hook", from = 16, last = 0}, {"lead.hook", cycle = 1}}}}},
	-- Opens on the raw break; the programmed kit joins halfway.
	{id = "jungle", name = "Jungle", tempo = {160, 170}, swing = {0.1, 0.2}, halftime = 0.2,
		snares = {"vintage", "rimshot", "roomy", "fat"},
		harmony = {progressions = {{1, 6, 3, 7}, {1, 7, 6, 7}, {1, 1, 4, 6}, {1, 1, 6, 6}, {1, 4, 1, 7}}},
		channels = {
			{role = "drums", beats = {"dnb.twostep", "dnb.skip", "dnb.tribal"}, gain = 0.85},
			{role = "tops", beats = {"break.amen", "break.amen", "break.funk", "break.bongo"}, gain = 0.8, chops = true},
			{role = "bass", patches = {"bass.sub", "bass.808", "bass.reese", "bass.hoover"},
				lines = {"@roll", "dnb.deep", "dnb.step", "line.push"}},
			{role = "pad", patches = {"pad.dark", "pad.choir", "pad.strings"}, chance = 0.6},
			{role = "stab", patches = {"stab.rave", "stab.piano", "stab.organ", "stab.brass"}, chance = 0.8},
			{role = "lead", patches = {"lead.hoover", "lead.square", "lead.flute"}, chance = 0.5,
				hooks = {"hook.riff", "hook.morse", "hook.insist", "hook.call", "@motif"}},
			{role = "texture", patches = {"texture.tape", "texture.air"}, chance = 0.6},
			{role = "fx", patches = {"fx.siren", "fx.riser"}},
		},
		plan = {intro = {tops = {"tops.loop", keep = true}, drums = {"drums.light", from = "half"}},
			build = {tops = {"tops.loop", from = "half"}}, drop = {tops = {"tops.loop", keep = true}}}},
	-- The break is the tune: little else plays.
	{id = "tearout", name = "Amen Tearout", tempo = {164, 172}, swing = {0.08, 0.16},
		snares = {"vintage", "crunchy", "fat"},
		harmony = {progressions = STATIC, change = 0.2},
		channels = {
			{role = "drums", beats = {"dnb.steppa", "dnb.twostep"}, gain = 0.7},
			{role = "tops", beats = {"break.amen", "break.stomp", "break.funk"}, gain = 0.95, chops = true},
			{role = "bass", patches = {"bass.reeseWide", "bass.808", "bass.hoover"}, lines = {"dnb.deep", "dnb.half", "line.push", "@cell"}},
			{role = "stab", patches = {"stab.rave", "stab.fm"}, chance = 0.6},
			{role = "texture", patches = {"texture.drone", "texture.tape"}, chance = 0.5},
			{role = "fx", patches = {"fx.siren", "fx.wind"}},
		},
		plan = {intro = {tops = {"tops.loop", keep = true}}, drop = {tops = {"tops.loop", keep = true}},
			breakdown = {tops = {"tops.light", from = "half"}}}},
	-- Nothing sweet: a bass that growls, stabs of metal, a kit that snaps.
	{id = "neuro", name = "Neurofunk", tempo = {172, 176}, swing = {0, 0.08}, halftime = 0.7,
		snares = {"crunchy", "tight", "layered", "fat"},
		harmony = {progressions = {{1, 1, 6, 7}, {1, 1, 1, 7}, {1, 2, 1, 7}, {1, 6, 1, 5}, {1, 1, 4, 6}}, voicing = {0, 2, 4, 6}},
		channels = {
			{role = "drums", beats = {"dnb.neuro", "dnb.tech", "dnb.jump"}, half = "dnb.half"},
			{role = "bass", patches = {"bass.growl", "bass.reeseWide", "bass.yoi", "bass.reese"},
				lines = {"dnb.neuro", "dnb.stab", "@roll", "@cell"}},
			{role = "pad", patches = {"pad.dark", "pad.pwm"}, chance = 0.5},
			{role = "stab", patches = {"stab.fm", "stab.saw", "stab.rave"}},
			{role = "arp", patches = {"pluck.acid", "pluck.chip", "pluck.saw"}, chance = 0.5, arp = {rates = {1}}},
			{role = "lead", patches = {"lead.fm", "lead.square"}, chance = 0.35,
				hooks = {"hook.morse", "hook.insist", "hook.dotted", "@motif"}},
			{role = "texture", patches = {"texture.drone", "texture.air"}, chance = 0.6},
			{role = "fx", patches = {"fx.riser", "fx.siren", "fx.wind"}},
		}},
	-- A bass line that never stops and a break tucked under the kit.
	{id = "rollers", name = "Rollers", tempo = {172, 175}, swing = {0.06, 0.14}, halftime = 0.35,
		snares = {"tight", "fat", "layered", "rimshot", "crunchy"},
		channels = {
			{role = "drums", beats = {"dnb.roller", "dnb.twostep", "dnb.tech"}},
			{role = "tops", beats = {"break.funk", "break.shuffle", "break.amen"}, gain = 0.5, chops = true, chance = 0.6},
			{role = "bass", patches = {"bass.reese", "bass.sub", "bass.moog", "bass.round"},
				lines = {"@roll", "@roll", "dnb.roll", "dnb.step", "line.tresillo"}},
			{role = "pad", patches = {"pad.saw", "pad.warm", "pad.dark"}, chance = 0.7},
			{role = "keys", patches = {"keys.rhodes", "keys.clav", "keys.organ"}, chance = 0.4},
			{role = "stab", patches = {"stab.saw", "stab.dub", "stab.organ"}, chance = 0.6},
			{role = "arp", patches = {"pluck.saw", "pluck.marimba", "pluck.string"}, chance = 0.6},
			{role = "fx", patches = {"fx.riser", "fx.wind"}},
		}},
	-- Five channels: a kick, a snare, a sub and what is left out.
	{id = "minimal", name = "Minimal", tempo = {170, 174}, swing = {0, 0.1}, halftime = 0.3,
		snares = {"tight", "rimshot", "roomy"},
		harmony = {progressions = STATIC, change = 0.15, voicing = {0, 2, 4, 6}},
		form = {openings = {"cold", "cold", "build"}, builds = {"rise", "sweep", "stomp"},
			links = {"build", "double", "breakdown", "breakdown build"}},
		channels = {
			{role = "drums", beats = {"dnb.steppa", "dnb.soft", "dnb.halfswing"}},
			{role = "bass", patches = {"bass.sub", "bass.808", "bass.round"}, lines = {"dnb.deep", "dnb.half", "line.root", "line.push"}},
			{role = "stab", patches = {"stab.dub", "stab.pizzicato"}, chance = 0.6},
			{role = "counter", patches = {"pluck.bell", "pluck.marimba", "keys.vibes"}, chance = 0.7,
				hooks = {"hook.space", "hook.echo", "hook.call", "@motif"}},
			{role = "texture", patches = {"texture.air", "texture.drone", "texture.tape"}},
			{role = "fx", patches = {"fx.wind"}, chance = 0.6},
		},
		plan = {drop = {counter = {"counter.answer", from = "phrase"}}, breakdown = {counter = "counter.answer"}}},
	-- 170 felt as 85: the snare on three throughout.
	{id = "halftime", name = "Halftime", tempo = {166, 172}, swing = {0.1, 0.2},
		snares = {"fat", "roomy", "layered", "crunchy"},
		harmony = {progressions = {{1, 1, 6, 6}, {1, 6, 4, 5}, {1, 7, 6, 7}, {1, 1, 4, 4}}, barsPerChord = 4},
		channels = {
			{role = "drums", beats = {"dnb.halfstep", "dnb.halfswing"}},
			{role = "bass", patches = {"bass.808", "bass.growl", "bass.wobble", "bass.sub"}, lines = {"dnb.half", "dnb.wob", "dnb.deep", "@cell"}},
			{role = "pad", patches = {"pad.dark", "pad.air", "pad.choir", "pad.glass"}},
			{role = "keys", patches = {"keys.vibes", "keys.rhodes", "keys.harp"}, chance = 0.5},
			{role = "arp", patches = {"pluck.glass", "pluck.string", "pluck.bell"}, chance = 0.5, arp = {rates = {2, 4}}},
			{role = "lead", patches = {"lead.vox", "lead.sine", "lead.pluck"}, chance = 0.7,
				hooks = {"hook.voice", "hook.space", "hook.sigh", "hook.lament", "@motif"}},
			{role = "texture", patches = {"texture.shimmer", "texture.tape", "texture.air"}, chance = 0.7},
			{role = "fx", patches = {"fx.wind", "fx.riser"}},
		}},
	-- Made for the dance floor: a wobbling bass that calls and answers itself.
	{id = "jumpup", name = "Jump-Up", tempo = {172, 176}, swing = {0.04, 0.12},
		snares = {"fat", "crunchy", "layered"},
		harmony = {progressions = STATIC, change = 0.3, voicing = {0, 2, 4, 6}},
		channels = {
			{role = "drums", beats = {"dnb.jump", "dnb.twostep", "dnb.tech"}},
			{role = "bass", patches = {"bass.yoi", "bass.wobble", "bass.hoover", "bass.donk"}, lines = {"dnb.jump", "dnb.wob", "dnb.stab", "@cell"}},
			{role = "stab", patches = {"stab.brass", "stab.rave", "stab.organ"}, chance = 0.7},
			{role = "lead", patches = {"lead.hoover", "lead.square"}, chance = 0.4,
				hooks = {"hook.jack", "hook.bounce", "hook.skank", "hook.octaves"}},
			{role = "texture", patches = {"texture.tape"}, chance = 0.4},
			{role = "fx", patches = {"fx.siren", "fx.riser"}},
		}},
	-- Mostly air: pads, a flute, the break far away.
	{id = "atmospheric", name = "Atmospheric", tempo = {162, 172}, swing = {0.08, 0.18}, halftime = 0.15,
		snares = {"roomy", "vintage", "rimshot"},
		form = {openings = {"melodic", "melodic", "build"}, intro = {2}, breakdown = {1, 2}},
		channels = {
			{role = "drums", beats = {"dnb.soft", "dnb.tribal", "dnb.skip"}, gain = 0.85},
			{role = "tops", beats = {"break.amen", "break.bongo", "break.tambourine"}, gain = 0.5, chops = true, chance = 0.8},
			{role = "bass", patches = {"bass.sub", "bass.round", "bass.upright"}, lines = {"dnb.deep", "line.walk", "@roll", "line.push"}},
			{role = "pad", patches = {"pad.air", "pad.glass", "pad.choir", "pad.strings"}},
			{role = "arp", patches = {"pluck.glass", "pluck.string", "keys.harp"}, chance = 0.7, arp = {rates = {2, 4}}},
			{role = "lead", patches = {"lead.flute", "lead.sine", "lead.pluck"}, chance = 0.7,
				hooks = {"hook.lament", "hook.cascade", "hook.voice", "hook.circle", "@motif"}},
			{role = "texture", patches = {"texture.shimmer", "texture.air"}},
			{role = "fx", patches = {"fx.wind"}},
		},
		plan = {intro = {pad = "pad.chords", arp = {"arp.run", from = "half"}}}},
}

return {
	api = 3,
	title = "Drum & Bass",
	symbol = "waveform.path",
	summary = "Liquid, Jungle, Neurofunk, Rollers and more at 174",
	defaults = {energy = 0.65, complexity = 0.5, humanize = 0.35, space = 0.35},
	set = {modes = {"minor", "dorian", "phrygian"}, modulations = {5, -2, 3, 2},
		arrangement = {introBars = 8, buildBars = 8, dropBars = 32, breakdownBars = 16, rebuildBars = 8, outroBars = 16,
			blendBars = 8, phraseBars = 8, minCycles = 2, maxCycles = 3}},
	harmony = {progressions = PROGRESSIONS, voicing = {2, 4, 6, 8}, barsPerChord = 2},
	roles = {drums = {fills = FILLS, half = "dnb.half"}},
	flavours = FLAVOURS,
	library = {beats = BEATS, lines = LINES},
}
