_G.__headless = true
local t = require("TestKit")
local ns = require("AppKit")
local Model = require("examples.adventure-arena.Model")
local controller = require("examples.adventure-arena.Controller").new()
controller.model = Model.new(function()
	return { start = function() return { resume = function(_, command) return "Response to " .. command end }, "Opening" end }
end)
local home = controller:home()
home.frameSize = ns.Size(640, 720)
home:layout(640)
t.assertEqual(home.depth, 1, "adventure home starts in one native navigation root")
controller:showGame(Model.games[1])
t.assertEqual(home.depth, 2, "detail stays in original navigation root")
controller:showSession(Model.games[1])
t.assertEqual(home.depth, 3, "session stays above detail in original navigation root")
t.assertEqual(controller.window, nil, "component navigation never creates a window")
ns._textFieldTestInput(controller.sessionRefs.input, "look")
t.expect(ns._textFieldTestCommand(controller.sessionRefs.input, "submit"), "return submits typed command")
t.assertEqual(controller.sessionRefs.input.text, "", "successful submission clears composer")
t.expect(controller.sessionRefs.output.text:find("Response to look", 1, true), "native transcript receives model output")
home:pop()
t.assertEqual(home.depth, 2, "ending session returns to detail")
home:pop()
t.assertEqual(home.depth, 1, "back returns to original catalog")
os.exit(t.summary() and 0 or 1)
