_G.__headless = true

local t = require("TestKit")
local ReadingSettings = require("apps.adventure-arena.models.ReadingSettings")

local settings = ReadingSettings.new()
local state = settings:presentation()
t.assertEqual(state.font, "serif", "the reader is a book: New York serif by default")
t.assertEqual(state.fontTitle, "New York", "the default face is named for the reader")
t.assertEqual(state.fontSize, 18, "reading type defaults to 18pt")
t.assertEqual(state.theme, "paper", "the default page is warm paper")
t.assertEqual(state.pageColor, "#FBF9F4|#1C1B1F", "paper follows the system appearance")
t.assertEqual(state.primaryTextColor, "#1D1C1A|#ECE9E2", "ink is near-black, never pure black on white")
t.assertEqual(state.appearance, 0, "paper follows the system appearance")
t.assertEqual(state.spacing, "normal", "normal leading by default")
t.assertEqual(state.lineSpacing, math.floor(18 * 0.32 + 0.5), "leading is a share of the type size")
t.assertEqual(state.alignment, "leading", "ragged right by default")
t.assertEqual(#state.themes, 4, "four pages: Paper, Original, Quiet, Night")
t.expect(state.themes[1].selected and not state.themes[2].selected, "only the current theme is selected")
for _, theme in ipairs(state.themes) do
	t.expect(not theme.page:lower():find("brown", 1, true), "no theme is brown: " .. theme.id)
end

t.expect(settings:setFontIndex(3), "font design can be changed by segmented index")
t.assertEqual(settings:presentation().font, "monospaced", "index 3 is Mono")
t.expect(not settings:setFontIndex(4), "font selection rejects an unknown option")
t.expect(not settings:setFontIndex(1.5), "font selection rejects fractional indices")
t.expect(settings:setFontSize(25.6), "font size accepts numeric changes")
t.assertEqual(settings:presentation().fontSize, 26, "font size rounds to the nearest point")
settings:adjustFontSize(1)
t.assertEqual(settings:presentation().fontSize, 26, "font size clamps at the maximum")
settings:setFontSize(13)
t.assertEqual(settings:presentation().fontSize, 14, "font size clamps at the minimum")
t.expect(not settings:setFontSize("large"), "non-numeric sizes are rejected")

t.expect(settings:setThemeIndex(3), "the night theme is selectable")
state = settings:presentation()
t.assertEqual(state.theme, "night", "index 3 is Night")
t.assertEqual(state.appearance, 2, "night is dark at any time of day")
t.assertEqual(state.pageColor, "#000000", "night is a black page")
t.expect(not settings:setThemeIndex(-1), "theme selection rejects an unknown option")
t.expect(not settings:setThemeIndex(4), "theme selection rejects an index past the last theme")

t.expect(settings:setSpacingIndex(2), "relaxed leading is selectable")
t.assertEqual(settings:presentation().lineSpacing, math.floor(14 * 0.5 + 0.5), "relaxed leading is half the type size")
settings:setJustified(true)
t.assertEqual(settings:presentation().alignment, "justified", "justification is a reading preference")

-- Preferences persist as plain values and restore exactly.
local restored = ReadingSettings.new(settings:snapshot())
t.assertEqual(restored.font, "monospaced", "the face survives a relaunch")
t.assertEqual(restored.fontSize, 14, "the size survives a relaunch")
t.assertEqual(restored.theme, "night", "the theme survives a relaunch")
t.assertEqual(restored.spacing, "relaxed", "the leading survives a relaunch")
t.expect(restored.justified, "justification survives a relaunch")
local defaults = ReadingSettings.new({ font = "comic", theme = "cover", spacing = "huge", fontSize = 99 })
t.assertEqual(defaults.font, "serif", "an unknown saved face falls back to the default")
t.assertEqual(defaults.theme, "paper", "a retired theme falls back to paper")
t.assertEqual(defaults.spacing, "normal", "unknown leading falls back to normal")
t.assertEqual(defaults.fontSize, 26, "a saved size is clamped")

os.exit(t.summary() and 0 or 1)
