_G.__headless = true

local t = require("TestKit")
local ReadingSettings = require("apps.adventure-arena.models.ReadingSettings")

local settings = ReadingSettings.new()
local state = settings:presentation()
t.assertEqual(state.font, "default", "reading settings default to the system font")
t.assertEqual(state.fontSize, 17, "reading settings use the reference default size")
t.assertEqual(state.theme, "cover", "reading opens over the game's cover art by default")
t.expect(state.backdrop, "the cover theme shows the blurred backdrop")
t.assertEqual(state.pageColor, "clear", "the cover theme keeps the page transparent")

t.expect(settings:setFontIndex(3), "font design can be changed by segmented index")
t.assertEqual(settings:presentation().font, "monospaced", "font selection maps to native font design")
t.expect(not settings:setFontIndex(4), "font selection rejects an unknown option")
t.expect(settings:setFontSize(24.4), "font size accepts numeric changes")
t.assertEqual(settings:presentation().fontSize, 24, "font size rounds to the nearest point")
settings:adjustFontSize(1)
t.assertEqual(settings:presentation().fontSize, 24, "font size clamps at the maximum")
settings:setFontSize(13)
t.assertEqual(settings:presentation().fontSize, 14, "font size clamps at the minimum")

t.expect(settings:setThemeIndex(1), "the system theme is selectable")
t.assertEqual(settings:presentation().theme, "system", "index 1 is the system page")
t.expect(not settings:presentation().backdrop, "solid themes hide the backdrop")
t.expect(settings:setThemeIndex(3), "reading theme can be changed by segmented index")
state = settings:presentation()
t.assertEqual(state.theme, "sepia", "theme selection maps to sepia")
t.assertEqual(state.backgroundColor, "#F5E8D1", "sepia uses the reference paper color")
t.assertEqual(state.pageColor, "#F5E8D1", "solid themes paint the page")
t.assertEqual(state.primaryTextColor, "#2B1F14", "sepia uses the reference ink color")
t.expect(not settings:setThemeIndex(-1), "theme selection rejects an unknown option")
t.expect(not settings:setThemeIndex(5), "theme selection rejects an index past the last theme")

os.exit(t.summary() and 0 or 1)
