_G.__headless = true
local t = require("TestKit")
local ns = require("AppKit")
local xml = require("ui.xml")
local sheet, refs = xml.render('<Sheet width="600" height="400"><VStack maxWidth="infinity" maxHeight="infinity"><Label text="Review"/><List ref="list" flexGrow="1" maxWidth="infinity"><Column id="name"/></List><Button ref="done" title="Done"/></VStack></Sheet>', {}, ns)
t.assertEqual(sheet.className, "LuaPanel", "Sheet is an ordinary native NSPanel")
t.assertEqual(sheet.contentView.className, "NSView", "sheet has no translucent visual-effect background")
t.expect(sheet.opaque, "sheet owns an opaque content surface")
t.expect(not sheet.canBecomeMainWindow, "sheet cannot be the application's main window")
t.assertEqual(sheet.size.width, 600, "declarative sheet width")
t.assertEqual(sheet.size.height, 400, "declarative sheet height")
t.expect(refs.list.contentView.clipsToBounds, "native table clips rows to its viewport")
local parent = ns.Window {visible = false, width = 900, height = 700}
ns.presentSheet(sheet, parent)
t.expect(sheet.sheetParent == nil, "headless construction never presents a sheet")
sheet:resize(780, 500); sheet:layout()
t.expect(refs.list.size.width > 600, "sheet content follows native resizing")
ns.dismiss(sheet); parent:close()
local file = assert(io.open('src/main.m')); local source = file:read('*a'); file:close()
t.expect(source:find('if (window.canBecomeMainWindow) [window makeMainWindow]', 1, true), "startup does not promote panels to main windows")
os.exit(t.summary() and 0 or 1)
