_G.__headless = true
local t = require("TestKit")
local ns = require("AppKit")
local xml = require("ui.xml")
local ordinary = xml.render('<Button title="Default"/>', {}, ns)
local small = xml.render('<Button title="Applications" size="11" style="link"/>', {}, ns)
t.assertEqual(small.font.pointSize, 11, "XML passes button typography to AppKit")
t.expect(small.font.pointSize < ordinary.font.pointSize, "font override does not change default buttons")
t.expect(not small.bordered and small.enabled, "typography retains native link behavior")
t.expect(small.frame.size.width >= small.intrinsicContentSize.width, "native button is remeasured for its font")
local row = xml.render('<Button title="Review resource" subtitle="More information" size="15" weight="semibold" style="row" disabled="true"/>', {}, ns)
t.assertEqual(row.titleLabel.font.pointSize, 15, "compound button applies the font to its native title")
t.expect(not row.enabled, "typography preserves disabled state")
t.assertEqual(row.subtitleLabel.stringValue, "More information", "title typography preserves subtitle")
os.exit(t.summary() and 0 or 1)
