local O = require("tests.support.diskmap_operations")
_G.__headless = true
local t = require("TestKit")
local bridge = require("AppKitNative")
local ns = require("AppKit")
local Controller = require("apps.diskmap.Controller")
local Mock = require("apps.diskmap.services.Mock")
local Locations = require("apps.diskmap.models.Locations")
local Marks = require("apps.diskmap.models.Marks")
local Verify = require("apps.diskmap.helpers.Verify")
local service = Mock.new()
local app = Controller.new(service)
app:createWindow()
local container = Locations:find("app-containers")
t.expect(container ~= nil, "the fixture contains sandboxed application data")
app:show("map", {focus = "system-data"})
app.window.size = ns.Size(950, 580)
app.window:layout()
bridge._flushLayout()
t.expect(app.page.refs.mapList.documentView.frame.size.width <= app.page.refs.mapList.contentView.bounds.size.width,
	"map review flags fit the native viewport at the minimum window width")
local map = app.page.request
local index
for at, row in ipairs(map.rows) do if row.id == container.id then index = at - 1 end end
t.expect(index ~= nil, "sandboxed data is in the category list")
t.expect(app.page.refs.mapSelection == nil and app.page.refs.mapScope == nil, "duplicate explanatory and measurement captions are absent")
bridge._pressColumnButton(app.page.refs.mapList, 2, index)
t.expect(Marks:contains(container.path), "a native row flag marks sandboxed data without a suggestion")
t.expect(Marks:find(container.path).reviewOnly, "owner-managed data is flagged for inspection")
t.expect(not Verify.check(Marks:find(container.path), container, service.home, {}), "inspection never authorizes deletion")
app:openReview(container.path)
t.expect(not O(app, "trash").enabled, "review-only items cannot enable bulk Trash")
t.expect(O(app, "inspect").enabled and O(app, "reveal").enabled, "inspection and Finder are available on the review page")
app.page.actions.inspect()
t.assertEqual(app.destination, "folder", "inspection opens the actual folder contents")
t.assertEqual(app.page.request.path, container.path, "the precise selected folder opens")
app.navigation:back()
t.assertEqual(app.destination, "basket", "Back returns to review")
app.page.actions.remove()
t.assertEqual(Marks:count(), 0, "unflagging changes no other state")
app:show("map", {focus = "system-data"})
app.page.actions.drillRow(nil, nil, {id = container.id})
t.assertEqual(app.destination, "folder", "double-click drills into sandboxed data")
t.assertEqual(app.page.request.path, container.path, "double-click retains the selected path")
t.expect(app.window.attachedSheet == nil, "drill-down presents no sheet")
app.navigation:back()
t.assertEqual(app.destination, "map", "Back returns to the map")
t.assertEqual(app.page.request.focusId, "system-data", "Back restores the map category")
local rows = app.env.rowActions
rows:toggleReview(Locations:find("speech-assets"))
t.expect(Marks:count() > 0, "an aggregate category can flag its individual locations")
local count = Marks:count()
rows:toggleReview(Locations:find("speech-assets"))
t.assertEqual(Marks:count(), 0, "unflagging a category removes its exact flags")
t.expect(count > 1, "a category retains its distinct locations")
local ok = app.env.basket:toggle({path = "/System/Library", name = "System Library"})
t.expect(ok and Marks:find("/System/Library").reviewOnly, "protected storage can be flagged independently of deletion")
t.expect(not app.env.basket:toggle({path = "/bad/../path"}), "malformed paths are still refused")
app.env.basket:toggle({path = "/", name = "Startup Disk"})
t.expect(rows:isIncluded(container.path), "flagging a disk includes its descendant locations")
local included = rows:annotateReview({id = container.id, name = container.name})
t.expect(included.markHelp:find("open review", 1, true), "a covered row explains that its button opens the enclosing flag")
rows:toggleReview(container)
t.assertEqual(app.destination, "basket", "an included row opens its enclosing flag for review")
t.assertEqual(app.page.request.selectedPath, "/", "the enclosing disk remains selected")
t.expect(Marks:contains("/"), "an included row never clears its enclosing flag")
Marks:clear()
app:show("xcode")
local derived = app.page.request.presented.lists.list_derived[1]
bridge._pressColumnButton(app.page.refs.list_derived, 3, 0)
t.assertEqual(Marks:find(derived.path).consequence, require("apps.diskmap.helpers.Xcode").sections[2].consequence,
	"a row flag retains the same specific consequence as its menu action")
app.page.actions.markRow(nil, nil, derived)
t.assertEqual(Marks:count(), 0, "clicking the row flag again removes only that flag")
app:dispose()
os.exit(t.summary() and 0 or 1)
