_G.__headless = true
local t = require("TestKit")
local ns = require("AppKit")
local Mock = require("apps.diskmap.services.Mock")
local Controller = require("apps.diskmap.Controller")
local app = Controller.new(Mock.new())
app:createWindow()
local home = app.env.model.home
t.assertEqual(app:badges().basket, nil, "nothing is flagged at first, so the sidebar row has no count")
app.env.basket:toggle({path = home .. "/Downloads/a.zip", name = "a.zip", bytes = 10})
app.env.basket:toggle({path = home .. "/Downloads/b.zip", name = "b.zip", bytes = 20})
t.assertEqual(app:badges().basket, "2", "the Flagged row counts the flagged items")
t.assertEqual(app.navigation.badges.basket, "2", "and the sidebar shows the count as soon as it changes")
app:show("overview")
app:openReview(home .. "/Downloads/b.zip")
t.assertEqual(app.destination, "basket", "Review opens the basket page")
t.assertEqual(app.env:page("basket").selected.path, home .. "/Downloads/b.zip", "on the item asked for")
t.expect(app.navigation:back(), "Back leaves the basket page")
t.assertEqual(app.destination, "overview", "for the page before it")
t.expect(app.navigation:forward(), "Forward returns to the basket")
t.assertEqual(app.destination, "basket", "the page again")
app.env.basket:toggle({path = home .. "/Downloads/a.zip"})
t.assertEqual(app.navigation.badges.basket, "1", "unflagging lowers the count")
os.exit(t.summary() and 0 or 1)
