_G.__headless = true
local t = require("TestKit")
local ns = require("AppKit")
local bridge = require("AppKitNative")
local xml = require("ui.xml")
local outline = xml.render('<OutlineView header="false" rowHeight="48" style="fullWidth"><Column id="name" subtitleKey="subtitle" imageKey="icon" imageSize="28" /><Column id="size" width="110" alignment="right" /></OutlineView>', {}, ns)
local rows = {{id = "a", name = "Developer", subtitle = "Tools and environments", icon = "hammer", expanded = true, children = {{id = "b", name = "Xcode", size = "1 GB"}}}}
outline:replaceRows(rows)
outline.size = ns.Size(500, 250); outline:layout(500)
t.assertEqual(outline.rowCount, 2, "semantic category initially expanded")
local cell = bridge._tableCell(outline, 0, 0)
t.assertEqual(cell.secondaryTextField.stringValue, "Tools and environments", "outline shares native subtitle cell")
t.expect(cell.imageView.image ~= nil, "row-bound SF Symbol")
outline:selectRow(1)
rows[1].expanded = false; rows[1].name = "Changed"
outline:replaceRows(rows)
t.assertEqual(outline.rowCount, 2, "replace preserves user expansion by identity")
t.assertEqual(outline.documentView.selectedRow, 1, "replace preserves selection")
local frames = bridge._tableCellFrames(outline, 0)
t.expect(frames[1].x - frames.disclosureMaxX >= 8, "native disclosure leaves breathing space before content")
t.expect(frames[2].maxX <= 501, "outline columns fit native viewport")
t.assertEqual(frames.disclosureMidY, frames.rowMidY, "native disclosure centers on the whole subtitle row")
t.expect(cell.textField.frame.origin.x - cell.imageView.frame.origin.x - cell.imageView.frame.size.width >= 8,
	"native image cells leave readable icon-to-title spacing")
outline.documentView.rowHeight = 64
outline:layout(500)
local tallFrames = bridge._tableCellFrames(outline, 0)
t.assertEqual(tallFrames.disclosureMidY, tallFrames.rowMidY, "disclosure follows changed native row height")
t.assertEqual(outline.rowCount, 2, "row height does not change expansion")
rows[1].subtitle = nil; rows[1].icon = nil
outline:replaceRows(rows)
t.assertEqual(bridge._tableCell(outline, 0, 0).secondaryTextField.stringValue, "", "reused cells clear subtitle")
t.expect(bridge._tableCell(outline, 0, 0).imageView.image == nil, "reused cells clear icon")
outline:replaceRows({{id = "new", name = "Collapsed", children = {{id = "child", name = "Match"}}}})
t.assertEqual(outline.rowCount, 1, "new category defaults collapsed")
outline:replaceRows({{id = "new", name = "Collapsed", forceExpanded = true, children = {{id = "child", name = "Match"}}}})
t.assertEqual(outline.rowCount, 2, "search can reveal a matching descendant")
local progress = ns.ProgressView {value = 0.68}
t.expect(not progress.indeterminate, "determinate progress respects value")
t.assertEqual(progress.doubleValue, 0.68, "progress round trip")
local group = xml.render('<GroupBox><Label text="Native group" /></GroupBox>', {}, ns)
t.assertEqual(group.className, "NSBox", "GroupBox uses AppKit control")
local root, refs = xml.render('<VStack><VStack ref="dynamic"/><Label ref="sibling" text="After"/></VStack>', {}, ns)
root.size = ns.Size(400, 300); root:layout(400)
refs.dynamic:add(xml.render('<Label text="New content" fixedHeight="80"/>', {}, ns))
refs.dynamic:layout()
t.expect(refs.dynamic.frame.size.height >= 80, "nested layout remeasures parent")
t.expect(refs.sibling.frame.origin.y + refs.sibling.frame.size.height <= refs.dynamic.frame.origin.y, "sibling moves after content growth")
local wrapped = xml.render('<VStack><Label ref="label" text="Long native text must wrap at its final proposed width" lines="3" fillWidth="true" /></VStack>', {}, ns)
wrapped.size = ns.Size(100, 100); wrapped:layout(100)
t.expect(wrapped.subviews[1].cell.wraps, "final label proposal restores native wrapping")
local badged = xml.render('<OutlineView><Column id="name" imageKey="icon" badgeColorKey="color" appIconKey="appIcon" imageSize="32" /></OutlineView>', {}, ns)
badged:replaceRows({{id = "badge", name = "Siri", icon = "waveform", color = "systemPurple"}})
local image = bridge._tableCell(badged, 0, 0).imageView
t.assertEqual(image.badgeColorName, "systemPurple", "category badge binds semantic color")
t.expect(not image.resolvedAppIcon, "ordinary category uses a symbol badge")
badged:replaceRows({{id = "badge", name = "Finder", icon = "folder", appIcon = "com.apple.finder"}})
image = bridge._tableCell(badged, 0, 0).imageView
t.expect(image.resolvedAppIcon, "installed app artwork comes from NSWorkspace")
t.expect(image.contentTintColor == nil, "real app artwork retains its colors")
badged:replaceRows({{id = "badge", name = "Missing app", icon = "folder", color = "systemTeal", appIcon = "invalid.diskmap.missing"}})
image = bridge._tableCell(badged, 0, 0).imageView
t.expect(not image.resolvedAppIcon and image.image ~= nil, "missing application falls back to symbol")
t.assertEqual(image.badgeColorName, "systemTeal", "reused cell updates badge")
local colored = ns.List {columns = {{id = "name", cell = {color = "color"}}}, data = {{name = "Brown", color = "systemBrown"}}}
local coloredCell = bridge._tableCell(colored, 0, 0)
t.assertEqual(coloredCell.textField.textColor.description, ns._systemColor("systemBrown").description, "table colors use the same semantic palette as standalone views")
local standalone = xml.render('<SystemImage name="mic.fill" size="32" badgeColor="systemBlue" appIcon="invalid.diskmap.missing"/>', {}, ns)
t.assertEqual(standalone.badgeColorName, "systemBlue", "standalone and table icons share badge API")
t.expect(not standalone.resolvedAppIcon, "standalone fallback retains badge")
t.assertSize(standalone, 32, 32, "badge has square intrinsic geometry")
standalone.appBundleId = "com.apple.finder"
t.expect(standalone.resolvedAppIcon, "standalone resolves app artwork")
standalone.appBundleId = "invalid.diskmap.missing"
t.expect(not standalone.resolvedAppIcon and standalone.image.template, "standalone mutation restores original symbol")
os.exit(t.summary() and 0 or 1)
