return {
	-- Files layered over the binary fixture for Large Files, File Types,
	-- Applications and the new catalog entries. `usedDaysAgo` dates each file's
	-- last use; fixture files use `fileAges` or `defaultAgeDays`.
	["defaultAgeDays"] = 12,
	["fileAges"] = {
		["~/Downloads/Old macOS Installer.dmg"] = 540,
		["~/Downloads/Design Assets.zip"] = 210,
		["~/Documents/Tax Archive.zip"] = 820,
		["~/mock-archive.tar"] = 1100,
		["~/Desktop/Launch Recording.mov"] = 400,
		["~/.Trash/Previous Mock Project/Project.xcarchive"] = 700,
	},
	["extraItems"] = {
		{path = "~/Library/iTunes/iPhone Software Updates/iPhone17,1_26.0_23A341_Restore.ipsw", bytes = 5400000000, usedDaysAgo = 380},
		{path = "~/.ollama/models/blobs/sha256-6a0746a1ec1a", bytes = 3800000000, usedDaysAgo = 95},
		{path = "~/.cache/huggingface/hub/models--mock--vision/blobs/model.safetensors", bytes = 2400000000, usedDaysAgo = 510},
		{path = "~/Library/Caches/ms-playwright/chromium-1140/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework", bytes = 1250000000, usedDaysAgo = 300},
		{path = "~/Library/Developer/CoreSimulator/Caches/dyld/23A339/dyld_sim_shared_cache_arm64e", bytes = 1800000000, usedDaysAgo = 20},
		{path = "~/Library/Containers/com.mock.VideoStudio/Data/Library/Caches/render.cache", bytes = 2200000000, usedDaysAgo = 30},
		{path = "~/Library/Containers/com.mock.RemovedEditor/Data/Library/Caches/thumbnails.db", bytes = 1200000000, usedDaysAgo = 640},
		{path = "~/Library/Application Support/com.mock.OldGame/saves.dat", bytes = 900000000, usedDaysAgo = 900},
		{path = "~/Library/Messages/Attachments/4f/15/IMG_0412.MOV", bytes = 1600000000, usedDaysAgo = 760},
		{path = "~/Downloads/ubuntu-24.04-desktop-arm64.iso", bytes = 2600000000, usedDaysAgo = 700},
		{path = "~/Downloads/Zoom Installer.pkg", bytes = 180000000, usedDaysAgo = 450},
		{path = "/opt/homebrew/var/log/mock-service.log", bytes = 1100000000, usedDaysAgo = 2},
	},
	-- Installed applications as Launch Services and Spotlight report them.
	["applications"] = {
		["/Applications/Mock Video Studio.app"] = {bundleId = "com.mock.VideoStudio", version = "4.2", lastUsedDaysAgo = 30},
		["/Applications/Mock Notes.app"] = {bundleId = "com.mock.Notes", version = "1.8", lastUsedDaysAgo = 2},
		["~/Applications/Mock Game.app"] = {bundleId = "com.mock.Game", version = "2.0", lastUsedDaysAgo = 410},
	},
	-- `diskutil info -plist /` and `diskutil apfs list -plist`, abridged.
	["volumes"] = {
		["info"] = {
			["DeviceIdentifier"] = "disk3s1s1", ["DeviceNode"] = "/dev/disk3s1s1", ["VolumeName"] = "Mock HDD",
			["FilesystemName"] = "APFS", ["FilesystemUserVisibleName"] = "APFS", ["SolidState"] = true,
			["SMARTStatus"] = "Verified", ["Internal"] = true, ["Encryption"] = true, ["FileVault"] = true,
			["BusProtocol"] = "Apple Fabric", ["APFSContainerReference"] = "disk3", ["Sealed"] = "Yes",
		},
		["apfs"] = {
			["Containers"] = {{
				["ContainerReference"] = "disk3", ["CapacityCeiling"] = 245107195904, ["CapacityFree"] = 16900000000,
				["Volumes"] = {
					{["Name"] = "Mock HDD", ["Roles"] = {"System"}, ["CapacityInUse"] = 11800000000, ["DeviceIdentifier"] = "disk3s1"},
					{["Name"] = "Preboot", ["Roles"] = {"Preboot"}, ["CapacityInUse"] = 7300000000, ["DeviceIdentifier"] = "disk3s2"},
					{["Name"] = "Recovery", ["Roles"] = {"Recovery"}, ["CapacityInUse"] = 1100000000, ["DeviceIdentifier"] = "disk3s3"},
					{["Name"] = "Data", ["Roles"] = {"Data"}, ["CapacityInUse"] = 204600000000, ["DeviceIdentifier"] = "disk3s5"},
					{["Name"] = "VM", ["Roles"] = {"VM"}, ["CapacityInUse"] = 2100000000, ["DeviceIdentifier"] = "disk3s6"},
					{["Name"] = "Update", ["Roles"] = {"Update"}, ["CapacityInUse"] = 1300000000, ["DeviceIdentifier"] = "disk3s4"},
				},
			}},
		},
		["external"] = {
			{["name"] = "Backup Drive", ["path"] = "/Volumes/Backup Drive", ["totalBytes"] = 2000000000000, ["freeBytes"] = 612000000000, ["filesystem"] = "APFS", ["removable"] = true},
		},
	},
	["snapshotCount"] = 2,
	["snapshotDates"] = {
		"com.apple.TimeMachine.20260915-091500.local",
		"com.apple.TimeMachine.20260922-184200.local",
	},
	["discovery"] = {
		{
			["id"] = "mock-video-studio",
			["name"] = "Mock Video Studio.app",
			["subtitle"] = "Installed application",
			["parentId"] = "apps-system",
			["path"] = "/Applications/Mock Video Studio.app",
			["policy"] = "Review",
			["action"] = "finder",
			["reviewThreshold"] = 1000000000,
			["consequence"] = "Review this synthetic application in Mock HDD. No application is installed on this Mac.",
			["icon"] = "app.fill",
			["color"] = "systemBlue",
		},
		{
			["id"] = "mock-notes-app",
			["name"] = "Mock Notes.app",
			["subtitle"] = "Installed application",
			["parentId"] = "apps-system",
			["path"] = "/Applications/Mock Notes.app",
			["policy"] = "Review",
			["action"] = "finder",
			["reviewThreshold"] = 1000000000,
			["consequence"] = "Review this synthetic application in Mock HDD. No application is installed on this Mac.",
			["icon"] = "app.fill",
			["color"] = "systemBlue",
		},
		{
			["id"] = "mock-game-app",
			["name"] = "Mock Game.app",
			["subtitle"] = "Installed application",
			["parentId"] = "apps-user",
			["path"] = "~/Applications/Mock Game.app",
			["policy"] = "Review",
			["action"] = "finder",
			["reviewThreshold"] = 1000000000,
			["consequence"] = "Review this synthetic application in Mock HDD. No application is installed on this Mac.",
			["icon"] = "app.fill",
			["color"] = "systemBlue",
		},
		{
			["id"] = "mock-node-modules",
			["name"] = "Node modules · MockProject",
			["subtitle"] = "Installed JavaScript dependencies for a project; review before removing",
			["parentId"] = "developer",
			["path"] = "~/Developer/MockProject/node_modules",
			["policy"] = "Review",
			["action"] = "finder",
			["reviewThreshold"] = 500000000,
			["icon"] = "folder",
			["color"] = "systemOrange",
		},
		{
			["id"] = "mock-cargo-target",
			["name"] = "Rust build output · MockProject",
			["subtitle"] = "Generated Cargo artifacts for a project; review before removing",
			["parentId"] = "developer",
			["path"] = "~/Developer/MockProject/target",
			["policy"] = "Review",
			["action"] = "finder",
			["reviewThreshold"] = 500000000,
			["icon"] = "folder",
			["color"] = "systemOrange",
		},
	},
	-- `xcrun simctl runtime list -j` and the Software Update preferences, as
	-- macOS reports them. Mock actions change only this in-memory copy.
	["simulatorRuntimes"] = {
		["5B0E6C62-9E4B-4C57-9B63-2D5F3A4E7A11"] = {
			["identifier"] = "5B0E6C62-9E4B-4C57-9B63-2D5F3A4E7A11",
			["runtimeIdentifier"] = "com.apple.CoreSimulator.SimRuntime.iOS-26-0",
			["platformIdentifier"] = "com.apple.platform.iphonesimulator",
			["version"] = "26.0", ["build"] = "23A339", ["kind"] = "Disk Image", ["state"] = "Ready",
			["deletable"] = true, ["sizeBytes"] = 8420000000, ["lastUsedAt"] = "2026-09-20T16:20:00Z",
		},
		["9C4A1F0B-3D2E-4B8A-8F61-7E5D9C0B2A34"] = {
			["identifier"] = "9C4A1F0B-3D2E-4B8A-8F61-7E5D9C0B2A34",
			["runtimeIdentifier"] = "com.apple.CoreSimulator.SimRuntime.iOS-18-4",
			["platformIdentifier"] = "com.apple.platform.iphonesimulator",
			["version"] = "18.4", ["build"] = "22E238", ["kind"] = "Disk Image", ["state"] = "Ready",
			["deletable"] = true, ["sizeBytes"] = 7910000000, ["lastUsedAt"] = "2025-11-02T09:00:00Z",
		},
		["E2F7B1C8-6A40-4D93-A5B2-1C9E8F3D6B70"] = {
			["identifier"] = "E2F7B1C8-6A40-4D93-A5B2-1C9E8F3D6B70",
			["runtimeIdentifier"] = "com.apple.CoreSimulator.SimRuntime.watchOS-26-0",
			["platformIdentifier"] = "com.apple.platform.watchsimulator",
			["version"] = "26.0", ["build"] = "23R341", ["kind"] = "Disk Image", ["state"] = "Ready",
			["deletable"] = true, ["sizeBytes"] = 4260000000,
		},
	},
	["softwareUpdate"] = {
		["AutomaticDownload"] = true,
		["LastSuccessfulDate"] = "2026-09-24 08:12:00 +0000",
		["RecommendedUpdates"] = {
			{["Display Name"] = "macOS Tahoe 26.1", ["Display Version"] = "26.1", ["Identifier"] = "MSU_UPDATE_25B78_patch_26.1"},
		},
	},
	["simulators"] = {
		["devices"] = {
			["com.apple.CoreSimulator.SimRuntime.iOS-26-0"] = {
				{
					["name"] = "iPhone 17 Pro",
					["udid"] = "11111111-2222-4333-8444-555555555555",
					["state"] = "Shutdown",
					["isAvailable"] = true,
					["lastUsedAt"] = "2026-09-20T16:20:00Z",
					["dataPath"] = "~/Library/Developer/CoreSimulator/Devices/11111111-2222-4333-8444-555555555555/data",
					["dataPathSize"] = 8800000000,
				},
				{
					["name"] = "iPad mini (A17 Pro)",
					["udid"] = "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee",
					["state"] = "Shutdown",
					["isAvailable"] = true,
					["lastUsedAt"] = "2026-09-18T08:10:00Z",
					["dataPath"] = "~/Library/Developer/CoreSimulator/Devices/aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee/data",
					["dataPathSize"] = 2400000000,
				},
			},
		},
		["runtimes"] = {
			{
				["identifier"] = "com.apple.CoreSimulator.SimRuntime.iOS-26-0",
				["name"] = "iOS 26.0",
				["version"] = "26.0",
				["isAvailable"] = true,
			},
		},
	},
}
