return {
	["snapshotCount"] = 2,
	["snapshotDates"] = {
		"com.apple.TimeMachine.20260915-091500.local",
		"com.apple.TimeMachine.20260922-184200.local",
	},
	["discovery"] = {
		{
			["id"] = "mock-video-studio",
			["name"] = "Mock Video Studio.app",
			["subtitle"] = "Installed application",
			["parentId"] = "apps-system",
			["path"] = "/Applications/Mock Video Studio.app",
			["policy"] = "Review",
			["action"] = "finder",
			["reviewThreshold"] = 1000000000,
			["consequence"] = "Review this synthetic application in Mock HDD. No application is installed on this Mac.",
			["icon"] = "app.fill",
			["color"] = "systemBlue",
		},
		{
			["id"] = "mock-notes-app",
			["name"] = "Mock Notes.app",
			["subtitle"] = "Installed application",
			["parentId"] = "apps-system",
			["path"] = "/Applications/Mock Notes.app",
			["policy"] = "Review",
			["action"] = "finder",
			["reviewThreshold"] = 1000000000,
			["consequence"] = "Review this synthetic application in Mock HDD. No application is installed on this Mac.",
			["icon"] = "app.fill",
			["color"] = "systemBlue",
		},
		{
			["id"] = "mock-game-app",
			["name"] = "Mock Game.app",
			["subtitle"] = "Installed application",
			["parentId"] = "apps-user",
			["path"] = "~/Applications/Mock Game.app",
			["policy"] = "Review",
			["action"] = "finder",
			["reviewThreshold"] = 1000000000,
			["consequence"] = "Review this synthetic application in Mock HDD. No application is installed on this Mac.",
			["icon"] = "app.fill",
			["color"] = "systemBlue",
		},
		{
			["id"] = "mock-node-modules",
			["name"] = "Node modules · MockProject",
			["subtitle"] = "Installed JavaScript dependencies for a project; review before removing",
			["parentId"] = "developer",
			["path"] = "~/Developer/MockProject/node_modules",
			["policy"] = "Review",
			["action"] = "finder",
			["reviewThreshold"] = 500000000,
			["icon"] = "folder",
			["color"] = "systemOrange",
		},
		{
			["id"] = "mock-cargo-target",
			["name"] = "Rust build output · MockProject",
			["subtitle"] = "Generated Cargo artifacts for a project; review before removing",
			["parentId"] = "developer",
			["path"] = "~/Developer/MockProject/target",
			["policy"] = "Review",
			["action"] = "finder",
			["reviewThreshold"] = 500000000,
			["icon"] = "folder",
			["color"] = "systemOrange",
		},
	},
	["simulators"] = {
		["devices"] = {
			["com.apple.CoreSimulator.SimRuntime.iOS-26-0"] = {
				{
					["name"] = "iPhone 17 Pro",
					["udid"] = "11111111-2222-4333-8444-555555555555",
					["state"] = "Shutdown",
					["isAvailable"] = true,
					["lastUsedAt"] = "2026-09-20T16:20:00Z",
					["dataPath"] = "~/Library/Developer/CoreSimulator/Devices/11111111-2222-4333-8444-555555555555/data",
					["dataPathSize"] = 8800000000,
				},
				{
					["name"] = "iPad mini (A17 Pro)",
					["udid"] = "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee",
					["state"] = "Shutdown",
					["isAvailable"] = true,
					["lastUsedAt"] = "2026-09-18T08:10:00Z",
					["dataPath"] = "~/Library/Developer/CoreSimulator/Devices/aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee/data",
					["dataPathSize"] = 2400000000,
				},
			},
		},
		["runtimes"] = {
			{
				["identifier"] = "com.apple.CoreSimulator.SimRuntime.iOS-26-0",
				["name"] = "iOS 26.0",
				["version"] = "26.0",
				["isAvailable"] = true,
			},
		},
	},
}
