local Model = require("apps.diskmap.Model")
local ListPage = require("apps.diskmap.models.ListPage")
local Projects = require("apps.diskmap.models.Projects")

local LAYOUT = {
	summary = "Build data your projects can recreate.", summaryId = "projectsSummary",
	buttons = {{id = "addFolder", title = "Add Folder…", systemImage = "plus", action = "addFolder", help = "Search another folder for projects"}},
	sections = {{title = "Build folders", detailId = "projectRoots",
		filters = {id = "filter", options = Projects.filters},
		buttons = {{id = "markStale", title = "Mark Old Build Data", systemImage = "plus.circle", action = "markStale",
			help = "Mark build data of projects with a clean git tree, untouched for three months"}},
		empties = {{id = "projectsEmpty", title = "No Build Folders Found", systemImage = "folder.badge.gearshape",
			description = "Projects appear here once Diskmap finds node_modules, target, .build and similar folders beside their project files."}},
		panelId = "projectsList",
		list = {id = "projects", menu = "rowMenu", activate = "reveal", detailColumn = true}}},
	footnote = {text = "Only folders a project's tools create (node_modules, target, .build, …) are listed. Projects with uncommitted or unpushed work are never marked in bulk."},
}

local WAITING = {title = "Projects Not Found Yet", systemImage = "folder.badge.gearshape", description = "Build folders are listed when the scan finishes."}

local function groups(page, filter, query)
	return Projects.groups(page.storage, page.info, os.time(), filter, query)
end

-- A project is marked when all of its generated folders are.
local function isMarked(page, group)
	for _, artifact in ipairs(group.artifacts) do
		if not page.actions:isMarked(artifact.path) then return false end
	end
	return #group.artifacts > 0
end

-- Whether every generated folder is covered by a mark, and the enclosing
-- marked folder if one covers them from above.
local function included(page, group)
	local enclosing
	for _, artifact in ipairs(group.artifacts) do
		local item, exact = page.actions:covering(artifact.path)
		if not item then return false end
		if not exact then enclosing = enclosing or item end
	end
	return #group.artifacts > 0, enclosing
end

local function mark(page, group)
	local review, marked = page.actions.review, isMarked(page, group)
	for _, artifact in ipairs(group.artifacts) do
		if (marked and page.actions:isMarked(artifact.path)) or (not marked and not page.actions:covering(artifact.path)) then
			review:toggle({path = artifact.path, name = artifact.name .. " · " .. group.name, bytes = artifact.bytes,
				source = "Projects", consequence = "Generated by the project's tools and recreated by its next build or install."
					.. (group.dirty and " This project has uncommitted or unpushed work; its sources are not touched." or "")})
		end
	end
end

-- Old build data of a project whose git tree is clean.
local function stale(page, query)
	local found = {}
	for _, group in ipairs(groups(page, Projects.filters[2], query)) do
		if type(group.git) == "table" and group.git.clean and not included(page, group) then table.insert(found, group) end
	end
	return found
end

local function rootsText(page)
	local roots = {"~/Developer"}
	for _, root in ipairs(page.storage.projectRoots or {}) do table.insert(roots, Model.tilde(root, page.storage.home)) end
	return table.concat(roots, ", ")
end

-- Git state and age are read one project at a time, then the page is drawn
-- again. A visit that ended meanwhile bumps the generation.
local function loadInfo(page)
	local service = page.services.service
	if type(service.projectInfo) ~= "function" or page.loadingInfo then return end
	local queue = {}
	for _, group in ipairs(groups(page, Projects.filters[1])) do
		if not page.info[group.path] then table.insert(queue, group.path) end
	end
	if #queue == 0 then return end
	page.loadingInfo = true
	local generation = page.generation
	local function step(index)
		if generation ~= page.generation then return end
		if index > #queue then page.loadingInfo = false; page.services.refresh(); return end
		service.projectInfo(queue[index], function(info)
			page.info[queue[index]] = info or {loaded = true}
			step(index + 1)
		end)
	end
	step(1)
end

-- The Projects page: generated build folders found beside their project
-- markers, grouped by project with git state and age. Marking a project marks
-- its generated folders, never its sources.
return ListPage.class(function()
	return {id = "projects", layout = LAYOUT,
	load = function(page) page.generation = (page.generation or 0) + 1; page.info = page.info or {}; loadInfo(page) end,
	unload = function(page) page.generation = page.generation + 1; page.loadingInfo = false end,
	-- A project's menu marks all of its build folders at once; its sources are
	-- never offered.
	menu = function(page, group)
		local actions, service = page.actions, page.services.service
		local all, enclosing = included(page, group)
		if all and enclosing then
			return {{title = "Included through Marked Folder — Review…", systemImage = "folder.badge.checkmark",
				action = function() actions.handlers.review(enclosing.path) end}, actions:reveal(group.path), actions:copyPath(group.path)}
		end
		local marked = isMarked(page, group)
		local items = {{title = marked and "Unmark Build Data" or "Mark Build Data for Cleanup", systemImage = marked and "minus.circle" or "plus.circle",
			action = function() mark(page, group) end}}
		for _, artifact in ipairs(group.artifacts) do
			table.insert(items, {title = "Show " .. artifact.name .. " (" .. artifact.size .. ")", systemImage = "folder",
				action = function() service.reveal(artifact.path) end})
		end
		table.insert(items, {separator = true})
		table.insert(items, actions:reveal(group.path))
		table.insert(items, actions:copyPath(group.path))
		return items
	end,
	actions = {
		markStale = function(page)
			for _, group in ipairs(stale(page)) do mark(page, group) end
		end,
		addFolder = function(page)
			local storage, service = page.storage, page.services.service
			if type(service.pickFolder) ~= "function" then return end
			local path = service.pickFolder("Choose a Folder with Projects")
			if not path then return end
			storage.projectRoots = storage.projectRoots or {}
			for _, root in ipairs(storage.projectRoots) do if root == path then return end end
			table.insert(storage.projectRoots, path)
			if service.saveFolders then service.saveFolders("projects", storage.projectRoots) end
			page.services.rescan()
		end,
		-- The sidebar's badge: the build data found, whether or not the page was opened.
		badge = function(page)
			local bytes = 0
			for _, group in ipairs(groups(page, Projects.filters[1])) do bytes = bytes + group.bytes end
			return bytes > 0 and Model.size(bytes) or nil
		end,
	}, present = function(model, state, page)
		page.info = page.info or {}
		local query = state.query or ""
		-- Nothing is listed until the scan has found the projects and git has
		-- told their state, one project at a time.
		local waiting = page.services.service.projectInfo ~= nil
		if model.scan.running then return {waiting = WAITING} end
		if waiting then
			for _, group in ipairs(groups(page, Projects.filters[1])) do
				if not page.info[group.path] then return {computing = "Reading the state of your projects…"} end
			end
		end
		-- Rows are the groups themselves, so menus receive a project's
		-- artifacts. A project is marked when all its build folders are.
		local rows = groups(page, Projects.filters[page.filterIndex], query)
		for _, group in ipairs(rows) do
			group.id, group.detail = group.path, group.gitText
			group.subtitle = Model.tilde(group.path, model.home) .. " · " .. group.artifactText .. " · " .. group.ageText
			group.icon, group.color = "folder.fill", group.dirty and "systemOrange" or "systemGreen"
			if isMarked(page, group) then
				group.icon, group.color, group.subtitle = "checkmark.circle.fill", "systemBlue", "Marked for cleanup · " .. group.subtitle
			elseif included(page, group) then
				group.icon, group.color, group.subtitle = "folder.badge.checkmark", "systemBlue", "Included through marked folder · " .. group.subtitle
			end
		end
		local all, bytes = groups(page, Projects.filters[1], query), 0
		for _, group in ipairs(all) do bytes = bytes + group.bytes end
		return {lists = {projects = page.actions:annotate(rows)}, hidden = {projectsEmpty = #all > 0, projectsList = #all == 0},
			disabled = {markStale = #stale(page, query) == 0}, texts = {projectRoots = "Project folders: " .. rootsText(page) .. ".",
			projectsSummary = #all == 0 and "No project build folders found yet. Add the folders where you keep code."
				or (Model.size(bytes) .. " of build data in " .. Model.plural(#all, "project"))}}
	end}
end)
