-- House blocks: four to the floor at 118-128 BPM. A round kick, claps on two
-- and four, open hats on the off-beats, a bass that leaves the kick its
-- room (off-beat, bumpy, walking, acid) and chords comped the way house
-- pianists and organists play them. Flavours: deep, classic, disco, piano,
-- organ, tribal, acid, french. Pitch is in scale steps (0 root, 2 third,
-- 4 fifth, 6 seventh, 7 octave), so every line holds under minor, dorian,
-- mixolydian and major, and under the genre's four-chord loops.
-- House mostly arrives by layers, not risers: the fx here are a few risers
-- the arranger may use before a return, plus impacts, crashes, downlifters
-- and sweeps.
return {
	----------------------------------------------------------------------
	-- DRUMS. The main kit loop. Low energies are DJ tools: kick, hats and a
	-- shaker, nothing tonal. Higher ones add claps, rides, congas, cowbell.
	----------------------------------------------------------------------
	{id = "house.drums.001", role = "drums", bars = 1, energy = 0.2, density = 0.1, brightness = 0.35,
		tags = {"fourfloor", "minimal", "mixable", "sparse", "straight"},
		lanes = {{"kick", "X...X...X...X..."}}},
	{id = "house.drums.002", role = "drums", bars = 1, energy = 0.28, density = 0.2, brightness = 0.55,
		tags = {"fourfloor", "minimal", "mixable", "sparse", "offbeat"},
		lanes = {{"kick", "X...X...X...X..."}, {"openHat", "..x...x...x...x.", gain = 0.4}}},
	{id = "house.drums.003", role = "drums", bars = 2, energy = 0.34, density = 0.3, brightness = 0.6,
		tags = {"fourfloor", "mixable", "offbeat", "straight"},
		lanes = {{"kick", "X...X...X...X..."}, {"openHat", "..x...x...x...x.", gain = 0.45},
			{"shaker", "x.x.x.x.x.x.x.xo|x.x.x.x.x.x.xoxo", gain = 0.3}}},
	{id = "house.drums.004", role = "drums", bars = 2, energy = 0.38, density = 0.3, brightness = 0.5,
		tags = {"fourfloor", "mixable", "deep", "swung"}, flavours = {"deep", "tribal"},
		lanes = {{"kick", "X...X...X...X...", gain = 0.95}, {"rim", "............x...|.......x....x...", gain = 0.4},
			{"hat", "..x...x...x...x.", gain = 0.45}, {"conga", "...x......x.....", gain = 0.35}}},
	{id = "house.drums.005", role = "drums", bars = 1, energy = 0.42, density = 0.4, brightness = 0.6,
		tags = {"fourfloor", "mixable", "offbeat", "driving"},
		lanes = {{"kick", "X...X...X...X..."}, {"clap", "....o.......o...", gain = 0.6},
			{"openHat", "..x...x...x...x.", gain = 0.45}, {"hat", "x.x.x.x.x.x.x.x.", gain = 0.22}}},
	{id = "house.drums.006", role = "drums", bars = 2, energy = 0.46, density = 0.45, brightness = 0.6,
		tags = {"fourfloor", "mixable", "shuffle", "swung"}, flavours = {"deep", "classic", "piano"},
		lanes = {{"kick", "X...X...X...X..."}, {"snap", "....x.......x...", gain = 0.65},
			{"hat", "x.xxx.xxx.xxx.xx", gain = 0.28}, {"openHat", "..x...x...x...x.", gain = 0.4},
			{"rim", ".............x..|......x.........", gain = 0.3}}},
	{id = "house.drums.007", role = "drums", bars = 1, energy = 0.55, density = 0.5, brightness = 0.6,
		tags = {"fourfloor", "straight", "offbeat", "driving"},
		lanes = {{"kick", "X...X...X...X..."}, {"clap", "....X.......X...", gain = 0.85},
			{"openHat", "..x...x...x...x.", gain = 0.45}, {"shaker", "xoxoxoxoxoxoxoxo", gain = 0.3, when = "energy"}}},
	{id = "house.drums.008", role = "drums", bars = 2, energy = 0.6, density = 0.55, brightness = 0.55,
		tags = {"fourfloor", "swung", "deep"}, flavours = {"deep", "piano"},
		lanes = {{"kick", "X...X...X...X...", gain = 0.95}, {"snap", "....x.......x...", gain = 0.7},
			{"rim", "............x...|.......x....x...", gain = 0.4}, {"hat", "..x...x...x...x.", gain = 0.5},
			{"shaker", "x.xxx.xxx.xxx.xx", gain = 0.28, when = "energy"}, {"conga", "...x......x.....", gain = 0.4, when = "complexity"}}},
	{id = "house.drums.009", role = "drums", bars = 2, energy = 0.68, density = 0.65, brightness = 0.6,
		tags = {"fourfloor", "driving", "shuffle", "syncopated"}, flavours = {"classic", "organ", "acid"},
		lanes = {{"kick", "X...X...X...X...|X...X...X...X..x"}, {"clap", "....X.......X...", gain = 0.85},
			{"hat", "x.xxx.xxx.xxx.xx", gain = 0.3}, {"openHat", "..x...x...x...x.", gain = 0.45},
			{"ghost", ".......g.....g..", when = "complexity"}, {"cowbell", "......x.....x...", gain = 0.35, when = "energy"}}},
	{id = "house.drums.010", role = "drums", bars = 2, energy = 0.72, density = 0.7, brightness = 0.65,
		tags = {"fourfloor", "swung", "playful", "driving"}, flavours = {"disco", "french"},
		lanes = {{"kick", "X...X...X...X..."}, {"clap", "....X.......X...", gain = 0.85},
			{"openHat", "..x...x...x...x.", gain = 0.55}, {"hat", "xo.oxo.oxo.oxo.o", gain = 0.3},
			{"tambourine", "x.x.x.x.x.x.x.x.", gain = 0.4, when = "energy"},
			{"cowbell", "x..x..x...x.x...|x..x..x...x..x..", gain = 0.3, when = "complexity"}}},
	{id = "house.drums.011", role = "drums", bars = 2, energy = 0.74, density = 0.75, brightness = 0.55,
		tags = {"fourfloor", "driving", "rhythmic", "busy"}, flavours = {"tribal"},
		lanes = {{"kick", "X...X...X...X..."}, {"clap", "....x.......x...", gain = 0.7},
			{"conga", "..x..x.x..x..x.x|..x..x.x.x..x.x.", gain = 0.55}, {"tomLow", "......x.......x.", gain = 0.45},
			{"shaker", "xoxoxoxoxoxoxoxo", gain = 0.35}, {"clave", "x..x..x...x.x...", gain = 0.3, when = "complexity"}}},
	{id = "house.drums.012", role = "drums", bars = 2, energy = 0.8, density = 0.75, brightness = 0.65,
		tags = {"fourfloor", "driving", "straight", "offbeat"}, flavours = {"classic", "organ", "acid"},
		lanes = {{"kick", "X...X...X...X...|X...X...X.x.X..."}, {"clap", "....X.......X...", gain = 0.9},
			{"hat", "x.xxx.xxx.xxx.xx", gain = 0.32}, {"openHat", "..x...x...x...x.", gain = 0.45},
			{"ride", "x.o.x.o.x.o.x.o.", gain = 0.3, light = false}, {"tomMid", ".............x.x", gain = 0.4, when = "complexity"}}},
	{id = "house.drums.013", role = "drums", bars = 4, energy = 0.86, density = 0.8, brightness = 0.65,
		tags = {"fourfloor", "driving", "busy", "offbeat"},
		lanes = {{"kick", "X...X...X...X..."}, {"clap", "....X.......X...", gain = 0.9},
			{"openHat", "..x...x...x...x.", gain = 0.5}, {"hat", "x.xxx.xxx.xxx.xx|x.xxx.xxx.xxx.xo|x.xxx.xxx.xxx.xx|xoxxx.xxxoxxx.xx", gain = 0.3},
			{"ride", "x.o.x.o.x.o.x.o.", gain = 0.3, light = false},
			{"conga", ".......x..x....x|......x..x...x..", gain = 0.45, when = "complexity"},
			{"clap", "................|................|................|..........x.x.x.", gain = 0.7, when = "energy"}}},
	{id = "house.drums.014", role = "drums", bars = 4, energy = 0.95, density = 0.9, brightness = 0.7,
		tags = {"fourfloor", "driving", "busy", "euphoric", "syncopated"}, flavours = {"classic", "disco", "french"},
		lanes = {{"kick", "X...X...X...X..."}, {"clap", "....X.......X...", gain = 0.9},
			{"openHat", "..x...x...x...x.", gain = 0.55}, {"hat", "xo.oxo.oxo.oxo.o", gain = 0.3},
			{"tambourine", "x.x.x.x.x.x.x.x.", gain = 0.4}, {"shaker", "xoxoxoxoxoxoxoxo", gain = 0.3},
			{"cowbell", "x..x..x...x.x...|x..x..x...x..x..|x..x..x...x.x...|x..x..x...x.xxx.", gain = 0.3},
			{"snare", "................|................|................|............x.x.", gain = 0.6, when = "energy"}}},

	----------------------------------------------------------------------
	-- TOPS. A second layer over the kit: shakers, bongos, a ride, a loop
	-- of congas. Never a kick.
	----------------------------------------------------------------------
	{id = "house.tops.001", role = "tops", bars = 1, energy = 0.3, density = 0.3, brightness = 0.8,
		tags = {"straight", "minimal", "sparse", "mixable"},
		lanes = {{"shaker", "x.x.x.x.x.x.x.x.", gain = 0.4}}},
	{id = "house.tops.002", role = "tops", bars = 2, energy = 0.5, density = 0.55, brightness = 0.8,
		tags = {"shuffle", "swung", "mixable"},
		lanes = {{"shaker", "xoxoxoxoxoxoxoxo", gain = 0.4}, {"tambourine", "....x.......x...", gain = 0.5}}},
	{id = "house.tops.003", role = "tops", bars = 2, energy = 0.55, density = 0.55, brightness = 0.55,
		tags = {"rhythmic", "swung", "mixable"}, flavours = {"tribal", "deep", "disco"},
		lanes = {{"conga", "x.xo.xo.x.xo.xo.|x.xo.xo.xoxo.xo."}, {"shaker", "..x...x...x...x.", gain = 0.5}}},
	{id = "house.tops.004", role = "tops", bars = 2, energy = 0.6, density = 0.6, brightness = 0.8,
		tags = {"offbeat", "driving", "straight"},
		lanes = {{"hat", "x.xxx.xxx.xxx.xx", gain = 0.28}, {"ride", "x.o.x.o.x.o.x.o.", gain = 0.3},
			{"cowbell", "..........x.....|......x.....x...", gain = 0.35}}},
	{id = "house.tops.005", role = "tops", bars = 2, energy = 0.7, density = 0.75, brightness = 0.6,
		tags = {"rhythmic", "busy", "syncopated"}, flavours = {"tribal"},
		lanes = {{"conga", "..x..x.x..x..x.x|..x..x.x.x..x.x."}, {"clave", "x..x..x...x.x...", gain = 0.35},
			{"tomHigh", "...........x..x.|..x........x....", gain = 0.4}}},
	{id = "house.tops.006", role = "tops", bars = 1, energy = 0.8, density = 0.8, brightness = 0.85,
		tags = {"driving", "busy", "playful"}, flavours = {"disco", "french", "classic"},
		lanes = {{"tambourine", "x.x.x.x.x.x.x.x.", gain = 0.45}, {"hat", "xo.oxo.oxo.oxo.o", gain = 0.28},
			{"shaker", "xoxoxoxoxoxoxoxo", gain = 0.3}}},
	{id = "house.tops.007", role = "tops", bars = 4, energy = 0.4, density = 0.35, brightness = 0.6,
		tags = {"sparse", "deep", "swung", "mixable"}, flavours = {"deep", "piano"},
		lanes = {{"rim", "............x...|.......x....x...|............x...|..x.....x.......", gain = 0.35},
			{"conga", "...x......x.....|...x.......x....", gain = 0.35}, {"shaker", "..x...x...x...x.", gain = 0.35}}},

	----------------------------------------------------------------------
	-- BASS. House bass leaves the kick alone: it lives on the off-beat
	-- ("and" of each beat, steps 2 6 10 14), bumps around it, or walks.
	----------------------------------------------------------------------
	-- The off-beat organ bass and its relatives.
	{id = "house.bass.001", role = "bass", bars = 1, energy = 0.5, density = 0.25, brightness = 0.35,
		tags = {"offbeat", "pedal", "driving", "minimal"},
		notes = "2:0:1.5 6:0:1.5 10:0:1.5 14:0:1.5"},
	{id = "house.bass.002", role = "bass", bars = 2, energy = 0.55, density = 0.3, brightness = 0.35,
		tags = {"offbeat", "driving", "warm"}, flavours = {"classic", "organ", "piano"},
		notes = "2:0:1.5 6:0:1.5 10:0:1.5 14:0:1.5 | 2:0:1.5 6:0:1.5 10:0:1.5 14:4:1.5"},
	{id = "house.bass.003", role = "bass", bars = 1, energy = 0.65, density = 0.45, brightness = 0.4,
		tags = {"offbeat", "octave", "driving"}, flavours = {"classic", "organ"},
		notes = "2:0:1 4:7:0.5 6:0:1 10:0:1 12:7:0.5 14:0:1"},
	{id = "house.bass.004", role = "bass", bars = 2, energy = 0.6, density = 0.4, brightness = 0.35,
		tags = {"syncopated", "driving", "warm"},
		notes = "0:0:1.5 3:0:1.5? 6:7:1.5 10:0:1.5 14:4:1.5? | 0:0:1.5 3:0:1.5? 6:7:1.5 10:0:1.5 14:6:1.5?"},
	-- Disco: octave bounce, a walk.
	{id = "house.bass.005", role = "bass", bars = 1, energy = 0.75, density = 0.7, brightness = 0.45,
		tags = {"octave", "driving", "playful", "rolling"}, flavours = {"disco", "french"},
		notes = "2:0:1 3:7:1 6:0:1 7:7:1 10:0:1 11:7:1 14:0:1 15:7:1"},
	{id = "house.bass.006", role = "bass", bars = 2, energy = 0.7, density = 0.6, brightness = 0.45,
		tags = {"walking", "playful", "warm", "stepwise"}, flavours = {"disco", "french", "classic"},
		notes = "0:0:2 3:0:1 6:2:2 8:4:2 11:4:1? 14:6:2 | 0:0:2 3:0:1 6:2:2 8:3:2 11:2:1? 14:1:2"},
	{id = "house.bass.007", role = "bass", bars = 1, energy = 0.7, density = 0.55, brightness = 0.45,
		tags = {"octave", "pluck", "playful", "syncopated"}, flavours = {"french", "disco"},
		notes = "0:0:1 2:7:1 3:0:1 6:7:1 8:0:1 10:7:1 11:0:1 14:4:1"},
	-- Garage and piano house: a held root, then a figure on the fifth.
	{id = "house.bass.008", role = "bass", bars = 1, energy = 0.6, density = 0.4, brightness = 0.4,
		tags = {"syncopated", "warm", "soulful", "leap"}, flavours = {"piano", "organ", "classic"},
		notes = "0:0:3 4:0:1? 7:7:2 10:6:2 13:4:2"},
	{id = "house.bass.009", role = "bass", bars = 2, energy = 0.62, density = 0.5, brightness = 0.4,
		tags = {"syncopated", "soulful", "warm"}, flavours = {"piano", "organ", "deep"},
		notes = "0:0:3 4:0:1? 7:7:2 10:6:2 13:4:2 | 0:0:3 4:4:1? 7:4:2 10:2:2 13:0:2"},
	-- Bump.
	{id = "house.bass.010", role = "bass", bars = 2, energy = 0.68, density = 0.55, brightness = 0.4,
		tags = {"syncopated", "driving", "bumpy"}, flavours = {"classic", "organ", "deep"},
		notes = "0:0:2 3:0:2 6:0:2? 8:6:2 11:4:2 14:2:2+ | 0:0:2 3:0:2 6:0:2? 8:7:2 11:6:2 14:4:2+"},
	{id = "house.bass.011", role = "bass", bars = 1, energy = 0.58, density = 0.45, brightness = 0.4,
		tags = {"syncopated", "bumpy", "warm"}, flavours = {"organ", "classic"},
		notes = "0:0:2 3:0:1 5:0:1 8:7:2 11:4:1 14:0:2"},
	-- Deep and tribal: long low notes and a one-note throb.
	{id = "house.bass.012", role = "bass", bars = 2, energy = 0.38, density = 0.2, brightness = 0.15,
		tags = {"sub", "deep", "sparse", "warm"}, flavours = {"deep", "tribal"},
		notes = "0:0:6 7:0:1? 10:6:2 12:4:3"},
	{id = "house.bass.013", role = "bass", bars = 1, energy = 0.3, density = 0.15, brightness = 0.1,
		tags = {"sub", "pedal", "sparse", "deep", "minimal"}, flavours = {"deep", "tribal"}, octave = 0,
		notes = "0:0:12"},
	{id = "house.bass.014", role = "bass", bars = 2, energy = 0.5, density = 0.4, brightness = 0.25,
		tags = {"sub", "rolling", "hypnotic", "dark", "deep"}, flavours = {"tribal", "deep"},
		notes = "2:0:1.5 5:0:1 6:0:1 10:0:1.5 13:0:1 14:7:1 | 2:0:1.5 5:0:1 6:0:1 10:0:1.5 13:0:1 14:6:1"},
	{id = "house.bass.015", role = "bass", bars = 4, energy = 0.45, density = 0.35, brightness = 0.25,
		tags = {"sub", "deep", "melancholic", "stepwise"}, flavours = {"deep"},
		notes = "0:0:4 6:0:2 10:6:2 12:4:4 | 2:0:2 6:0:2 10:2:2 14:4:2 | 0:0:4 6:0:2 10:6:2 12:4:4 | 2:0:2 6:2:2 10:1:2 12:0:4"},
	{id = "house.bass.016", role = "bass", bars = 1, energy = 0.8, density = 0.6, brightness = 0.35,
		tags = {"tresillo", "gallop", "dark", "driving", "syncopated"}, flavours = {"tribal"},
		notes = "0:0:2 3:0:2 6:0:2 8:0:1 10:7:1 11:0:1 14:4:1"},
	-- Acid: a 303 figure. Slides, accents, the flat second as a little shiver.
	{id = "house.bass.017", role = "bass", bars = 2, energy = 0.75, density = 0.6, brightness = 0.6,
		tags = {"acid", "hypnotic", "driving", "riff", "rolling"}, flavours = {"acid"}, follow = "key", octave = 0,
		notes = "0:0:1 2:0:1! 3:7:1~ 4:0:1 6:0:1 7:2:1~ 8:0:1! 10:0:1 11:4:1~ 12:0:1 14:7:1 | 0:0:1 2:0:1! 3:7:1~ 4:0:1 6:0:1 7:4:1~ 8:0:1! 10:0:1 11:1b:1~ 12:0:1 14:0:1"},
	{id = "house.bass.018", role = "bass", bars = 1, energy = 0.6, density = 0.5, brightness = 0.55,
		tags = {"acid", "hypnotic", "rolling", "minimal"}, flavours = {"acid"}, follow = "key", octave = 0,
		notes = "0:0:1 1:0:1 2:7:1! 4:0:1 6:0:1~ 7:4:1 8:0:1 10:7:1! 12:0:1 14:2:1"},
	{id = "house.bass.019", role = "bass", bars = 2, energy = 0.85, density = 0.75, brightness = 0.7,
		tags = {"acid", "aggressive", "rolling", "busy", "leap"}, flavours = {"acid"}, follow = "key", octave = 0,
		notes = "0:0:1! 1:0:1 2:7:1~ 3:0:1 4:4:1! 6:0:1 7:0:1 8:7:1~ 9:0:1 10:0:1! 11:2:1 12:4:1~ 14:0:1 15:7:1 | 0:0:1! 1:0:1 2:7:1~ 3:0:1 4:4:1! 6:0:1 7:0:1 8:9:1~ 9:7:1 10:6:1! 11:4:1 12:2:1~ 14:0:1 15:0:1"},

	----------------------------------------------------------------------
	-- PAD. Sustained harmony under the groove; the held pad is the rule,
	-- the breathing pad pulses slowly.
	----------------------------------------------------------------------
	{id = "house.pad.001", role = "pad", bars = 4, energy = 0.2, density = 0.1, brightness = 0.3,
		tags = {"held", "ambient", "dreamy", "deep", "sparse"}, hold = true},
	{id = "house.pad.002", role = "pad", bars = 2, energy = 0.4, density = 0.2, brightness = 0.45,
		tags = {"held", "warm", "chordal"}, comp = "0:16"},
	{id = "house.pad.003", role = "pad", bars = 2, energy = 0.5, density = 0.3, brightness = 0.5,
		tags = {"chordal", "warm", "soulful", "rhythmic"}, flavours = {"deep", "disco", "piano", "classic"},
		comp = "0:10 10:6"},
	{id = "house.pad.004", role = "pad", bars = 1, energy = 0.55, density = 0.35, brightness = 0.5,
		tags = {"chordal", "euphoric", "offbeat"}, flavours = {"classic", "disco", "french"},
		comp = "2:4 6:4 10:4 14:2"},
	{id = "house.pad.005", role = "pad", bars = 2, energy = 0.75, density = 0.5, brightness = 0.7,
		tags = {"chordal", "euphoric", "bright", "held"}, flavours = {"disco", "french", "piano"},
		comp = "0:6 6:2! 8:6 14:2!"},

	----------------------------------------------------------------------
	-- KEYS. The comping rhythms of house pianists, organists and electric
	-- piano players: a chord on the "and" of a beat, held across, answered.
	----------------------------------------------------------------------
	{id = "house.keys.001", role = "keys", bars = 2, energy = 0.4, density = 0.2, brightness = 0.45,
		tags = {"sparse", "soulful", "deep", "syncopated"}, flavours = {"deep", "piano"},
		comp = "0:3 3:5 10:5"},
	{id = "house.keys.002", role = "keys", bars = 1, energy = 0.5, density = 0.3, brightness = 0.5,
		tags = {"syncopated", "soulful", "warm", "chordal"}, flavours = {"deep", "classic", "piano"},
		comp = "0:3 3:3 6:4 10:5"},
	{id = "house.keys.003", role = "keys", bars = 1, energy = 0.6, density = 0.4, brightness = 0.55,
		tags = {"syncopated", "chordal", "rhythmic", "playful"},
		comp = "0:2 3:2 6:2 10:2 13:3"},
	{id = "house.keys.004", role = "keys", bars = 2, energy = 0.7, density = 0.6, brightness = 0.65,
		tags = {"syncopated", "bright", "euphoric", "chordal", "busy"}, flavours = {"piano", "classic"},
		comp = "0:3 3:3 6:2 8:2 11:3 13:1 14:2"},
	{id = "house.keys.005", role = "keys", bars = 2, energy = 0.65, density = 0.45, brightness = 0.5,
		tags = {"offbeat", "chordal", "driving", "rhythmic"}, flavours = {"organ", "classic"},
		comp = "2:2 6:2 10:2 13:1 14:2"},
	{id = "house.keys.006", role = "keys", bars = 4, energy = 0.35, density = 0.2, brightness = 0.4,
		tags = {"held", "soulful", "melancholic", "sparse", "dreamy"}, flavours = {"deep", "piano"},
		comp = "0:6 6:10"},
	{id = "house.keys.007", role = "keys", bars = 1, energy = 0.85, density = 0.65, brightness = 0.7,
		tags = {"bright", "driving", "chordal", "syncopated", "euphoric"}, flavours = {"piano"},
		comp = "0:2! 3:2 6:2! 8:2 11:2! 14:2!"},
	{id = "house.keys.008", role = "keys", bars = 1, energy = 0.7, density = 0.5, brightness = 0.6,
		tags = {"rhythmic", "playful", "syncopated", "chordal"}, flavours = {"disco", "french"},
		comp = "0:1 2:1 3:1 6:1 8:1 10:1 11:1 14:1"},

	----------------------------------------------------------------------
	-- STAB. Short chords: the classic house hit, the organ stab, the horn.
	----------------------------------------------------------------------
	{id = "house.stab.001", role = "stab", bars = 1, energy = 0.5, density = 0.25, brightness = 0.55,
		tags = {"syncopated", "sparse", "chordal"},
		comp = "3:1 6:1 10:1"},
	{id = "house.stab.002", role = "stab", bars = 1, energy = 0.6, density = 0.3, brightness = 0.55,
		tags = {"syncopated", "chordal", "driving"}, flavours = {"classic", "organ", "acid"},
		comp = "3:1 6:1 11:1"},
	{id = "house.stab.003", role = "stab", bars = 1, energy = 0.55, density = 0.3, brightness = 0.5,
		tags = {"offbeat", "chordal", "driving"}, flavours = {"organ", "classic"},
		comp = "2:1 6:1 10:1 14:1"},
	{id = "house.stab.004", role = "stab", bars = 2, energy = 0.7, density = 0.45, brightness = 0.6,
		tags = {"syncopated", "chordal", "bumpy"}, flavours = {"classic", "organ"},
		comp = "3:1 6:1 10:1 13:1 14:1"},
	{id = "house.stab.005", role = "stab", bars = 1, energy = 0.75, density = 0.5, brightness = 0.7,
		tags = {"playful", "syncopated", "chordal", "stab"}, flavours = {"disco", "french"},
		comp = "0:1! 3:1 6:1! 10:1 12:1 14:1"},
	{id = "house.stab.006", role = "stab", bars = 2, energy = 0.45, density = 0.2, brightness = 0.4,
		tags = {"dark", "hypnotic", "minimal", "sparse", "stab"}, flavours = {"tribal", "acid", "deep"},
		comp = "3:2 11:2"},
	{id = "house.stab.007", role = "stab", bars = 1, energy = 0.9, density = 0.65, brightness = 0.75,
		tags = {"euphoric", "busy", "bright", "chordal", "driving"}, flavours = {"classic", "piano"},
		comp = "0:1! 3:1 4:1 6:1! 8:1 10:1 11:1 14:2!"},
	{id = "house.stab.008", role = "stab", bars = 2, energy = 0.65, density = 0.35, brightness = 0.5,
		tags = {"soulful", "chordal", "sparse", "warm", "syncopated"}, flavours = {"deep", "piano"},
		comp = "3:2 6:1 11:2"},

	----------------------------------------------------------------------
	-- ARP. Chord tones run in time; house arps are gentle and often only
	-- play eighths, with the sixteenths held for Complexity.
	----------------------------------------------------------------------
	{id = "house.arp.001", role = "arp", energy = 0.35, density = 0.3, brightness = 0.7,
		tags = {"arpeggio", "dreamy", "sparse", "stepwise"}, flavours = {"deep", "piano"},
		order = {1, 2, 3, 4, 3, 2}, rate = 2, gate = 0.8, mask = "XxXxXxXxXxXxXxXx"},
	{id = "house.arp.002", role = "arp", energy = 0.5, density = 0.45, brightness = 0.7,
		tags = {"arpeggio", "driving", "straight", "pluck"},
		order = {1, 3, 2, 4}, rate = 2, gate = 0.6, mask = "XXXXXXXXXXXXXXXX"},
	{id = "house.arp.003", role = "arp", energy = 0.6, density = 0.55, brightness = 0.75,
		tags = {"arpeggio", "syncopated", "pluck", "playful"}, flavours = {"classic", "disco", "french"},
		order = {1, 2, 3, 4, 3, 2, 1, 3}, rate = 2, gate = 0.5, mask = "XX.XXX.XXX.XXX.X"},
	{id = "house.arp.004", role = "arp", energy = 0.7, density = 0.7, brightness = 0.8,
		tags = {"arpeggio", "driving", "busy", "bright", "euphoric"},
		order = {1, 2, 3, 4}, rate = 1, gate = 0.5, mask = "XXxXXxXxXXxXXxXx", octave = 1},
	{id = "house.arp.005", role = "arp", energy = 0.45, density = 0.35, brightness = 0.6,
		tags = {"arpeggio", "offbeat", "pluck", "rhythmic"}, flavours = {"deep", "disco", "tribal"},
		order = {2, 3, 4, 3}, rate = 4, gate = 0.8, mask = "XXXXXXXXXXXXXXXX"},
	{id = "house.arp.006", role = "arp", energy = 0.8, density = 0.6, brightness = 0.85,
		tags = {"arpeggio", "leap", "euphoric", "bright"}, flavours = {"piano", "classic", "french"},
		order = {1, 3, 4, 2, 4, 3}, rate = 2, gate = 0.55, mask = "XXXXXXXXXXXXXXXX", octave = 2},
	{id = "house.arp.007", role = "arp", energy = 0.55, density = 0.4, brightness = 0.55,
		tags = {"arpeggio", "hypnotic", "dark", "minimal", "rhythmic"}, flavours = {"tribal", "acid"},
		order = {1, 1, 3, 1, 4, 1}, rate = 2, gate = 0.4, mask = "XxXxXxXxXxXxXxX."},
	{id = "house.arp.008", role = "arp", energy = 0.65, density = 0.5, brightness = 0.7,
		tags = {"arpeggio", "stepwise", "rolling", "warm"}, flavours = {"deep", "classic", "organ"},
		order = {4, 3, 2, 1, 2, 3}, rate = 2, gate = 0.7, mask = "XXxXXxXXxXXxXXxX"},

	----------------------------------------------------------------------
	-- LEAD. The tune. Hooks of 1, 2 and 4 bars: a riff that holds still
	-- under the chords ("key") or a melody that follows them.
	----------------------------------------------------------------------
	-- Short riffs.
	{id = "house.lead.001", role = "lead", bars = 1, energy = 0.5, density = 0.3, brightness = 0.55,
		tags = {"riff", "rhythmic", "syncopated", "playful", "hook"}, follow = "key",
		notes = "0:4:1 3:4:1 6:6:1 8:4:2 11:2:2 14:4:2"},
	{id = "house.lead.002", role = "lead", bars = 2, energy = 0.6, density = 0.4, brightness = 0.6,
		tags = {"riff", "stepwise", "playful", "hook"}, follow = "key", flavours = {"classic", "organ", "acid"},
		notes = "0:0:2 3:2:2 6:3:2 10:4:3 14:6:2 | 0:4:3 3:3:2 6:2:2 10:0:4"},
	{id = "house.lead.003", role = "lead", bars = 2, energy = 0.7, density = 0.5, brightness = 0.7,
		tags = {"riff", "offbeat", "bright", "hook", "rhythmic"}, follow = "key", flavours = {"classic", "disco", "french"},
		notes = "2:7:2 6:6:2 10:4:2 14:6:2 | 2:7:2 6:9:2 10:7:2 14:4:2"},
	{id = "house.lead.004", role = "lead", bars = 1, energy = 0.4, density = 0.2, brightness = 0.45,
		tags = {"vocal", "held", "soulful", "deep", "sparse"}, flavours = {"deep", "piano"},
		notes = "0:4:8 8:6:6~"},
	-- Two-bar calls and answers.
	{id = "house.lead.005", role = "lead", bars = 2, energy = 0.55, density = 0.35, brightness = 0.55,
		tags = {"hook", "answer", "stepwise", "soulful"}, flavours = {"piano", "deep", "classic"},
		notes = "0:7:3 3:6:1 4:4:4 8:2:2 | 0:4:2 2:2:2 4:0:6"},
	{id = "house.lead.006", role = "lead", bars = 2, energy = 0.65, density = 0.45, brightness = 0.6,
		tags = {"hook", "leap", "euphoric", "bright"}, flavours = {"piano", "classic", "french"},
		notes = "0:0:2 2:4:2 4:7:4 8:6:2 10:4:2 12:7:4 | 0:9:4 4:7:2 6:4:2 8:2:8"},
	{id = "house.lead.007", role = "lead", bars = 2, energy = 0.5, density = 0.25, brightness = 0.4,
		tags = {"vocal", "stepwise", "melancholic", "dreamy", "hook"}, flavours = {"deep", "piano"},
		notes = "0:4:8 8:6:6~ | 0:7:10 12:6:4~"},
	-- Four-bar hooks.
	{id = "house.lead.008", role = "lead", bars = 4, energy = 0.7, density = 0.5, brightness = 0.65,
		tags = {"hook", "euphoric", "stepwise", "anthem", "bright"}, flavours = {"piano", "classic", "disco"},
		notes = "0:4:6 6:5:2 8:4:4 12:2:4 | 0:4:6 6:5:2 8:6:4 12:7:4 | 0:8:6 6:7:2 8:6:4 12:4:4 | 0:4:4 4:2:4 8:0:8"},
	{id = "house.lead.009", role = "lead", bars = 4, energy = 0.6, density = 0.4, brightness = 0.6,
		tags = {"hook", "stepwise", "dreamy", "soulful"}, flavours = {"deep", "piano", "french"},
		notes = "0:2:4 4:4:2 6:2:2 8:0:8 | 0:2:4 4:4:2 6:6:2 8:4:8 | 0:7:4 4:6:2 6:4:2 8:2:8 | 0:4:4 4:2:2 6:0:2 8:0:8"},
	{id = "house.lead.010", role = "lead", bars = 4, energy = 0.8, density = 0.7, brightness = 0.7,
		tags = {"hook", "riff", "rhythmic", "playful", "syncopated"}, follow = "key", flavours = {"classic", "organ", "disco"},
		notes = "0:4:1 2:4:1 3:4:2 6:6:2 8:4:2 11:2:2 14:4:2 | 0:4:1 2:4:1 3:4:2 6:7:2 8:6:2 11:4:4 | 0:4:1 2:4:1 3:4:2 6:6:2 8:4:2 11:2:2 14:4:2 | 0:2:1 2:2:1 3:2:2 6:3:2 8:0:6"},
	{id = "house.lead.011", role = "lead", bars = 4, energy = 0.45, density = 0.2, brightness = 0.5,
		tags = {"hook", "held", "melancholic", "stepwise", "sparse"}, flavours = {"deep", "tribal", "acid"},
		notes = "0:4:8 8:3:8 | 0:2:8 8:0:8 | 0:4:8 8:3:8 | 0:2:6 8:1:4 12:0:4"},
	{id = "house.lead.012", role = "lead", bars = 4, energy = 0.75, density = 0.6, brightness = 0.75,
		tags = {"hook", "arpeggio", "euphoric", "bright", "leap"}, flavours = {"piano", "french", "classic"},
		notes = "0:0:2 2:2:2 4:4:2 6:7:2 8:4:2 10:2:2 12:4:4 | 0:0:2 2:2:2 4:4:2 6:7:2 8:9:4 12:7:4 | 0:0:2 2:2:2 4:4:2 6:7:2 8:4:2 10:2:2 12:4:4 | 0:7:2 2:4:2 4:2:2 6:0:2 8:0:8"},
	{id = "house.lead.013", role = "lead", bars = 2, energy = 0.85, density = 0.6, brightness = 0.8,
		tags = {"riff", "bright", "euphoric", "rhythmic", "hook"}, follow = "key", flavours = {"classic", "french", "disco"},
		notes = "0:7:1 1:7:1 2:9:2 4:7:2 6:4:2 8:7:1 9:7:1 10:9:2 12:11:4 | 0:7:1 1:7:1 2:9:2 4:7:2 6:4:2 8:2:4 12:4:4"},
	{id = "house.lead.014", role = "lead", bars = 1, energy = 0.7, density = 0.5, brightness = 0.5,
		tags = {"acid", "riff", "hypnotic", "rhythmic"}, follow = "key", flavours = {"acid"},
		notes = "0:7:1 2:7:1~ 3:9:1 4:7:1 6:4:1 8:7:1 10:6:1~ 11:7:1 12:4:2 14:2:2"},
	{id = "house.lead.015", role = "lead", bars = 2, energy = 0.35, density = 0.2, brightness = 0.4,
		tags = {"sparse", "dark", "hypnotic", "minimal", "hook"}, flavours = {"tribal", "deep", "acid"},
		notes = "0:4:2 6:3:2 | 0:4:2 6:2:2 10:0:4"},

	----------------------------------------------------------------------
	-- COUNTER. Answers the lead in its gaps: short, soft, a step away.
	----------------------------------------------------------------------
	{id = "house.counter.001", role = "counter", bars = 2, energy = 0.4, density = 0.2, brightness = 0.55,
		tags = {"answer", "sparse", "stepwise", "dreamy"},
		notes = "10:4:2 13:2:3 | 12:0:4"},
	{id = "house.counter.002", role = "counter", bars = 2, energy = 0.5, density = 0.3, brightness = 0.6,
		tags = {"answer", "rhythmic", "playful", "syncopated"}, flavours = {"tribal", "disco", "french"},
		notes = "6:4:1 8:2:1 10:4:2 | 6:4:1 8:6:1 10:4:2"},
	{id = "house.counter.003", role = "counter", bars = 4, energy = 0.55, density = 0.3, brightness = 0.6,
		tags = {"answer", "stepwise", "warm", "soulful"}, flavours = {"deep", "piano", "classic"},
		notes = "8:7:2 10:6:2 12:4:4 | | 8:7:2 10:6:2 12:4:2 14:2:2 | 8:0:8"},
	{id = "house.counter.004", role = "counter", bars = 1, energy = 0.7, density = 0.5, brightness = 0.7,
		tags = {"answer", "leap", "bright", "rhythmic", "hook"}, flavours = {"classic", "disco", "french"},
		notes = "3:7:1 5:6:1 6:4:1 11:2:1 13:4:1 14:7:2"},
	{id = "house.counter.005", role = "counter", bars = 2, energy = 0.45, density = 0.35, brightness = 0.45,
		tags = {"answer", "hypnotic", "minimal", "dark"}, flavours = {"tribal", "acid"},
		notes = "3:0:1 7:2:1 11:0:1 14:4:1 | 3:0:1 7:2:1 11:3:1 14:2:1"},

	----------------------------------------------------------------------
	-- TEXTURE. Long held voices for air under the groove, in semitones
	-- above the root.
	----------------------------------------------------------------------
	{id = "house.texture.001", role = "texture", energy = 0.15, density = 0.1, brightness = 0.4,
		tags = {"ambient", "dreamy", "held"}, voices = {0, 7}, every = 4},
	{id = "house.texture.002", role = "texture", energy = 0.2, density = 0.15, brightness = 0.3,
		tags = {"ambient", "dark", "deep", "held"}, flavours = {"deep", "tribal", "acid"}, voices = {0, 12}, every = 8},
	{id = "house.texture.003", role = "texture", energy = 0.3, density = 0.2, brightness = 0.6,
		tags = {"ambient", "warm", "dreamy", "soulful"}, flavours = {"deep", "piano", "french"}, voices = {0, 4, 7, 11}, every = 4},
	{id = "house.texture.004", role = "texture", energy = 0.25, density = 0.15, brightness = 0.35,
		tags = {"ambient", "dark", "hypnotic", "minimal"}, flavours = {"tribal", "acid"}, voices = {0, 5}, every = 2},
	{id = "house.texture.005", role = "texture", energy = 0.4, density = 0.25, brightness = 0.7,
		tags = {"ambient", "bright", "euphoric", "held"}, flavours = {"classic", "disco", "french", "piano"}, voices = {7, 12, 16}, every = 4},

	----------------------------------------------------------------------
	-- FX. House builds by layers more than by noise, so there are a few
	-- risers, short ones for the bar before a return and one long one.
	----------------------------------------------------------------------
	{id = "house.fx.001", role = "fx", bars = 4, energy = 0.5, density = 0.4, brightness = 0.8,
		tags = {"riser"}, kind = "riser"},
	{id = "house.fx.002", role = "fx", bars = 8, energy = 0.7, density = 0.5, brightness = 0.9,
		tags = {"riser", "euphoric"}, kind = "riser", flavours = {"classic", "piano", "disco"}},
	{id = "house.fx.003", role = "fx", bars = 2, energy = 0.4, density = 0.3, brightness = 0.7,
		tags = {"riser", "deep", "sparse"}, kind = "riser", flavours = {"deep", "tribal", "acid", "french"}},
	{id = "house.fx.004", role = "fx", bars = 1, energy = 0.6, density = 0.3, brightness = 0.5,
		tags = {"impact"}, kind = "impact"},
	{id = "house.fx.005", role = "fx", bars = 1, energy = 0.8, density = 0.4, brightness = 0.4,
		tags = {"impact", "dark"}, kind = "impact", flavours = {"tribal", "acid", "classic"}},
	{id = "house.fx.006", role = "fx", bars = 1, energy = 0.5, density = 0.3, brightness = 0.9,
		tags = {"crash", "bright"}, kind = "crash"},
	{id = "house.fx.007", role = "fx", bars = 4, energy = 0.4, density = 0.3, brightness = 0.6,
		tags = {"downlifter", "deep"}, kind = "downlifter"},
	{id = "house.fx.008", role = "fx", bars = 2, energy = 0.5, density = 0.3, brightness = 0.5,
		tags = {"downlifter", "ambient"}, kind = "downlifter", flavours = {"deep", "tribal", "french"}},
	{id = "house.fx.009", role = "fx", bars = 8, energy = 0.45, density = 0.3, brightness = 0.7,
		tags = {"riser", "dreamy", "ambient"}, kind = "riser", flavours = {"deep", "piano", "french"}},
	{id = "house.fx.010", role = "fx", bars = 1, energy = 0.35, density = 0.2, brightness = 0.7,
		tags = {"crash", "sparse"}, kind = "crash", flavours = {"deep", "piano"}},
}
