local ns = require("AppKit")
local Template = require("ui.template")
local Model = require("apps.diskmap.Model")
local Recommendations = require("apps.diskmap.models.Recommendations")
local Controller = {}; Controller.__index = Controller

-- The Clean Up page. `actions` builds resource menus; `tips` presents
-- contextual guidance; `handlers.open(id)` opens a category,
-- `handlers.show(page, filter)` another page and `handlers.apps()` returns
-- the Applications summary once it is known.
function Controller.new(model, actions, tips, handlers)
	return setmetatable({model = model, actions = actions, tips = tips, handlers = handlers}, Controller)
end

function Controller:elsewhereMenu(row)
	return {{title = "Open " .. (row.detail or "Page"), systemImage = "arrow.right.circle",
		action = function() self.handlers.show(row.page, row.filter) end}}
end

function Controller:mount(host, state)
	local resourceMenu = function(_, _, row) return self.actions:resource(row.id) end
	local openResource = function(_, _, row)
		local resource = row and self.model.resources:find(row.id)
		local parent = resource and resource:getParent()
		if parent then self.handlers.open(parent.id) end
	end
	self.template = Template.new(host, "apps/diskmap/views/Cleanup.etlua", ns)
	local _, refs = self.template:update({actions = {
		menu_rebuildable = resourceMenu, menu_review = resourceMenu, menu_checked = resourceMenu,
		open_rebuildable = openResource, open_review = openResource, open_checked = openResource,
		menu_elsewhere = function(_, _, row) return self:elsewhereMenu(row) end,
		open_elsewhere = function(_, _, row) if row then self.handlers.show(row.page, row.filter) end end,
	}})
	self.refs = refs
	self.tipPanel = self.template:child("tips", "apps/diskmap/views/Tips.etlua")
	self:update(state)
	return refs
end

function Controller:update(state)
	local refs = self.refs
	if not refs then return end
	local data = Recommendations.presentation(self.model, state and state.query, self.handlers.apps())
	for _, id in ipairs({"rebuildable", "review", "elsewhere", "checked"}) do
		refs["list_" .. id]:replaceRows(data[id])
		refs["section_" .. id].hidden = #data[id] == 0
	end
	refs.summary.text = data.summary
	refs.rebuildableTileValue.text = Model.size(data.rebuildableBytes)
	refs.rebuildableTileDetail.text = #data.rebuildable .. (#data.rebuildable == 1 and " location" or " locations") .. " regenerated by their owners"
	refs.reviewTileValue.text = Model.size(data.reviewBytes)
	refs.reviewTileDetail.text = #data.review .. (#data.review == 1 and " location" or " locations") .. " that may hold your work"
	refs.checkedTileValue.text = tostring(data.known)
	refs.checkedTileDetail.text = "Known space hogs checked · " .. data.absent .. " not on this Mac"
	local tips = self.tips:presentation(state and state.disk)
	self.tipPanel:update(tips)
end

function Controller:dispose()
	if self.template then self.template:dispose() end
	self.template, self.refs, self.tipPanel = nil, nil, nil
end

return Controller
