local ns = require("AppKit")
local Template = require("ui.template")
local Model = require("apps.diskmap.Model")
local Projects = require("apps.diskmap.models.Projects")
local Controller = {}; Controller.__index = Controller

-- The Projects page: generated build folders found beside their project
-- markers, grouped by project with git state and age. Marking a project marks
-- its generated folders, never its sources. `rescan()` rediscovers after the
-- search folders change.
function Controller.new(model, service, actions, rescan)
	return setmetatable({model = model, service = service, actions = actions, review = actions.review, rescan = rescan, generation = 0,
		info = {}, filterIndex = 1}, Controller)
end

local function display(path, home)
	if home and path:sub(1, #home + 1) == home .. "/" then return "~" .. path:sub(#home + 1) end
	return path
end

function Controller:rootsText()
	local roots = {display(self.model.home .. "/Developer", self.model.home)}
	for _, root in ipairs(self.model.projectRoots or {}) do table.insert(roots, display(root, self.model.home)) end
	return "Searching " .. table.concat(roots, ", ") .. " for projects and the build folders they create."
end

function Controller:mount(host, state)
	self.generation = self.generation + 1
	self.query, self.filterIndex = state.query or "", 1
	self.template = Template.new(host, "apps/diskmap/views/Projects.etlua", ns)
	local _, refs = self.template:update({filters = Projects.filters, roots = self:rootsText(),
		summary = "Build data your projects can recreate.", actions = {
		filter = function(index) self.filterIndex = (index or 0) + 1; self:show() end,
		menu = function(_, _, row) return self:menu(row) end,
		reveal = function(_, _, row) if row then self.service.reveal(row.path) end end,
		markStale = function() self:markStale() end,
		addFolder = function() self:addFolder() end,
	}})
	self.refs = refs
	self:show()
	self:loadInfo()
	return refs
end

function Controller:groups(filter)
	return Projects.groups(self.model, self.info, os.time(), filter or Projects.filters[self.filterIndex], self.query)
end

-- A project is marked when all of its generated folders are.
function Controller:isMarked(group)
	for _, artifact in ipairs(group.artifacts) do
		if not self.review:isMarked(artifact.path) then return false end
	end
	return #group.artifacts > 0
end

function Controller:mark(group)
	if not group then return end
	local marked = self:isMarked(group)
	for _, artifact in ipairs(group.artifacts) do
		if self.review:isMarked(artifact.path) == marked then
			self.review:toggle({path = artifact.path, name = artifact.name .. " · " .. group.name, bytes = artifact.bytes,
				source = "Projects", consequence = "Generated by the project's tools and recreated by its next build or install."
					.. (group.dirty and " This project has uncommitted or unpushed work; its sources are not touched." or "")})
		end
	end
end

-- A project's menu marks all of its build folders at once; its sources are
-- never offered.
function Controller:menu(group)
	local marked = self:isMarked(group)
	local items = {{title = marked and "Unmark Build Data" or "Mark Build Data for Cleanup", systemImage = marked and "minus.circle" or "plus.circle",
		action = function() self:mark(group) end}}
	for _, artifact in ipairs(group.artifacts) do
		table.insert(items, {title = "Show " .. artifact.name .. " (" .. artifact.size .. ")", systemImage = "folder",
			action = function() self.service.reveal(artifact.path) end})
	end
	table.insert(items, {separator = true})
	table.insert(items, self.actions:reveal(group.path))
	table.insert(items, self.actions:copyPath(group.path))
	return items
end

function Controller:markStale()
	for _, group in ipairs(self:groups(Projects.filters[2])) do
		if type(group.git) == "table" and group.git.clean and not self:isMarked(group) then self:mark(group) end
	end
end

function Controller:addFolder()
	if type(self.service.pickFolder) ~= "function" then return end
	local path = self.service.pickFolder("Choose a Folder with Projects")
	if not path then return end
	self.model.projectRoots = self.model.projectRoots or {}
	for _, root in ipairs(self.model.projectRoots) do if root == path then return end end
	table.insert(self.model.projectRoots, path)
	if self.service.saveFolders then self.service.saveFolders("projects", self.model.projectRoots) end
	if self.refs then self.refs.projectRoots.text = self:rootsText() end
	self.rescan()
end

function Controller:show()
	if not self.refs then return end
	-- Rows are the groups themselves, so menus receive a project's
	-- artifacts. A project is marked when all its build folders are.
	local rows = self:groups()
	for _, group in ipairs(rows) do
		group.id, group.detail = group.path, group.gitText
		group.subtitle = Projects.location(group.path, self.model.home) .. " · " .. group.artifactText .. " · " .. group.ageText
		group.icon, group.color = "folder.fill", group.dirty and "systemOrange" or "systemGreen"
		if self:isMarked(group) then
			group.icon, group.color, group.subtitle = "checkmark.circle.fill", "systemBlue", "Marked for cleanup · " .. group.subtitle
		end
	end
	self.refs.projects:replaceRows(self.actions:annotate(rows))
	local all, bytes, stale = self:groups(Projects.filters[1]), 0, false
	for _, group in ipairs(all) do bytes = bytes + group.bytes end
	for _, group in ipairs(self:groups(Projects.filters[2])) do
		if type(group.git) == "table" and group.git.clean and not self:isMarked(group) then stale = true end
	end
	self.refs.markStale.enabled = stale
	self.refs.projectsEmpty.hidden = #all > 0
	self.refs.projectsList.hidden = #all == 0
	self.refs.projectsSummary.text = #all == 0 and "No project build folders found yet. Add the folders where you keep code."
		or (Model.size(bytes) .. " of build data in " .. Model.plural(#all, "project"))
end

function Controller:marksChanged() self:show() end

function Controller:update(state)
	local query = state.query or ""
	if self.query == query and not state.scanChanged then return end
	self.query = query
	self:show()
	self:loadInfo()
end

-- Git state and age are read one project at a time, then the list refreshes.
function Controller:loadInfo()
	if type(self.service.projectInfo) ~= "function" or self.loadingInfo then return end
	local queue = {}
	for _, group in ipairs(self:groups(Projects.filters[1])) do
		if not self.info[group.path] then table.insert(queue, group.path) end
	end
	if #queue == 0 then return end
	self.loadingInfo = true
	local generation = self.generation
	local function step(index)
		if generation ~= self.generation then self.loadingInfo = false; return end
		if index > #queue then self.loadingInfo = false; self:show(); return end
		self.service.projectInfo(queue[index], function(info)
			self.info[queue[index]] = info or {loaded = true}
			step(index + 1)
		end)
	end
	step(1)
end

function Controller:badge()
	local bytes = 0
	for _, group in ipairs(self:groups(Projects.filters[1])) do bytes = bytes + group.bytes end
	return bytes > 0 and Model.size(bytes) or nil
end

function Controller:dispose()
	self.generation = self.generation + 1
	self.loadingInfo = false
	if self.template then self.template:dispose() end
	self.template, self.refs = nil, nil
end

return Controller
