-- Techno blocks: the loops the arranger picks from for the genre's seven
-- flavours (peak, acid, hypnotic, industrial, minimal, melodic, dub).
-- Pitch is in scale steps (0 root, 2 third, 4 fifth, 6 seventh, 7 octave),
-- so every line works in minor, dorian or phrygian and over the genre's
-- usually static chords. See BLOCKS.md.
--
-- NO RISERS: techno builds in plateaus (layers added and removed, filters
-- drifting), not in sweeps, so the arranger never places a riser for this
-- genre. The few fx blocks below are one-shots on a phrase boundary: a
-- crash, an impact and a downlifter that closes a section.
--
-- Bass sits between the kicks: kicks land on steps 0, 4, 8, 12, so the
-- "rolling" rumble lives on 1-3, 5-7 ... and the offbeat bass on 2, 6, 10, 14.
return {
	---------------------------------------------------------------- drums
	-- Mixable openers and closers: kick and a little air, no tune, no bass
	-- needed. A DJ can beat-match on them for 16 bars.
	{id = "techno.drums.001", role = "drums", bars = 1, energy = 0.2, density = 0.1, brightness = 0.3,
		tags = {"fourfloor", "minimal", "mixable", "sparse", "straight"},
		lanes = {{"kick", "X...X...X...X..."}}},
	{id = "techno.drums.002", role = "drums", bars = 1, energy = 0.25, density = 0.2, brightness = 0.5,
		tags = {"fourfloor", "offbeat", "mixable", "sparse"},
		lanes = {{"kick", "X...X...X...X..."}, {"hat", "..x...x...x...x.", gain = 0.4}}},
	{id = "techno.drums.003", role = "drums", bars = 2, energy = 0.32, density = 0.3, brightness = 0.55,
		tags = {"fourfloor", "offbeat", "mixable", "straight"},
		lanes = {{"kick", "X...X...X...X..."}, {"openHat", "..x...x...x...x.", gain = 0.4},
			{"shaker", "x.x.x.x.x.x.x.x.|x.x.x.x.xxx.x.x.", gain = 0.22}}},
	{id = "techno.drums.004", role = "drums", bars = 2, energy = 0.36, density = 0.3, brightness = 0.5,
		tags = {"fourfloor", "minimal", "mixable", "swung"}, flavours = {"minimal", "hypnotic", "acid"},
		lanes = {{"kick", "X...X...X...X..."}, {"rim", "....x.......x...|....x.......x..x", gain = 0.45},
			{"hat", "..x...x...x...x.", gain = 0.4}}},
	{id = "techno.drums.005", role = "drums", bars = 1, energy = 0.42, density = 0.35, brightness = 0.5,
		tags = {"fourfloor", "mixable", "driving"},
		lanes = {{"kick", "X...X...X...X..."}, {"clap", "....x.......x...", gain = 0.7, light = false},
			{"hat", "x.x.x.x.x.x.x.x.", gain = 0.25}, {"openHat", "..x...x...x...x.", gain = 0.4}}},
	-- Dub: a soft kick and one rim on the four, space for the chord to ring.
	{id = "techno.drums.006", role = "drums", bars = 2, energy = 0.28, density = 0.2, brightness = 0.4,
		tags = {"fourfloor", "minimal", "mixable", "sparse", "deep"}, flavours = {"dub", "minimal"},
		lanes = {{"kick", "X...X...X...X...", gain = 0.85}, {"rim", "............x...|....x.......x...", gain = 0.4},
			{"hat", "..x.......x.....|..x.......x...x.", gain = 0.3}}},
	-- Peak and drive: clap on two and four, offbeat open hat, 16th hats.
	{id = "techno.drums.007", role = "drums", bars = 1, energy = 0.55, density = 0.5, brightness = 0.6,
		tags = {"fourfloor", "driving", "offbeat"},
		lanes = {{"kick", "X...X...X...X..."}, {"clap", "....X.......X...", gain = 0.9, light = false},
			{"openHat", "..x...x...x...x.", gain = 0.5}, {"hat", "xx.xxx.xxx.xxx.x", gain = 0.25, when = "energy"}}},
	{id = "techno.drums.008", role = "drums", bars = 3, energy = 0.5, density = 0.45, brightness = 0.5,
		tags = {"fourfloor", "hypnotic", "syncopated"}, flavours = {"hypnotic", "minimal"},
		lanes = {{"kick", "X...X...X...X..."},
			{"rim", "..x..x..x..x..x.|.x..x..x..x..x..|x..x..x..x..x..x", gain = 0.4},
			{"openHat", "..x...x...x...x.", gain = 0.4, light = false},
			{"shaker", "xoxoxoxoxoxoxoxo", gain = 0.3, when = "energy"}}},
	{id = "techno.drums.009", role = "drums", bars = 2, energy = 0.62, density = 0.55, brightness = 0.5,
		tags = {"broken", "driving", "syncopated"}, flavours = {"acid", "peak", "industrial"},
		lanes = {{"kick", "X.....X..X..X...|X.....X..X....x."}, {"clap", "....X.......X...", gain = 0.85, light = false},
			{"hat", "xoxoxoxoxoxoxoxo", gain = 0.3}, {"rim", "...x.....x.....x", gain = 0.4, when = "complexity"}}},
	{id = "techno.drums.010", role = "drums", bars = 2, energy = 0.7, density = 0.6, brightness = 0.65,
		tags = {"fourfloor", "driving", "rolling"}, flavours = {"peak", "melodic"},
		lanes = {{"kick", "X...X...X...X...|X...X...X...X.x."}, {"clap", "....X.......X...", gain = 0.9, light = false},
			{"hat", "xoxoxoxoxoxoxoxo", gain = 0.3}, {"openHat", "..x...x...x...x.", gain = 0.55, light = false},
			{"ride", "x.x.x.x.x.x.x.x.", gain = 0.3, when = "energy"}}},
	{id = "techno.drums.011", role = "drums", bars = 2, energy = 0.8, density = 0.75, brightness = 0.6,
		tags = {"fourfloor", "driving", "busy"}, flavours = {"peak"},
		lanes = {{"kick", "X...X...X...X...|X...X...X...X..x"}, {"clap", "....X.......X...", gain = 0.9},
			{"snare", "....x.......x...|....x.......x.x.", gain = 0.5, light = false},
			{"hat", "xxxxxxxxxxxxxxxx", gain = 0.2}, {"openHat", "..x...x...x...x.", gain = 0.55},
			{"tomLow", "......x......x..|......x....x..x.", gain = 0.4, when = "complexity"}}},
	{id = "techno.drums.012", role = "drums", bars = 2, energy = 0.85, density = 0.7, brightness = 0.5,
		tags = {"fourfloor", "aggressive", "driving", "busy"}, flavours = {"industrial"},
		lanes = {{"kick", "X...X...X...X.x.|X...X...X..xX..."}, {"snare", "....X.......X...", gain = 0.75, light = false},
			{"clap", "....x.......x...", gain = 0.6}, {"hat", "x.x.x.x.x.x.x.x.", gain = 0.4},
			{"openHat", "..x...x...x...x.", gain = 0.4, when = "energy"}, {"tomLow", "......x......x..", gain = 0.5, when = "complexity"}}},
	{id = "techno.drums.013", role = "drums", bars = 1, energy = 0.95, density = 0.8, brightness = 0.55,
		tags = {"fourfloor", "aggressive", "busy", "dark"}, flavours = {"industrial", "peak"},
		lanes = {{"kick", "X..xX..xX..xX..x"}, {"snare", "....X.......X...", gain = 0.8, light = false},
			{"clap", "....X.......X...", gain = 0.7}, {"hat", "xxxxxxxxxxxxxxxx", gain = 0.28},
			{"ride", "..x...x...x...x.", gain = 0.4}, {"tomLow", ".......x.......x", gain = 0.5, when = "complexity"}}},
	{id = "techno.drums.014", role = "drums", bars = 4, energy = 1.0, density = 0.9, brightness = 0.65,
		tags = {"fourfloor", "driving", "busy", "aggressive"}, flavours = {"peak", "industrial"},
		lanes = {{"kick", "X...X...X...X...|X...X...X...X...|X...X...X...X...|X...X...X..xX.x."},
			{"clap", "....X.......X...", gain = 0.9}, {"snare", "....x.......x...|....x.......x...|....x.......x...|....x..x..x.x.xx", gain = 0.5},
			{"hat", "xxxxxxxxxxxxxxxx", gain = 0.22}, {"openHat", "..x...x...x...x.", gain = 0.55},
			{"ride", "x.x.x.x.x.x.x.x.", gain = 0.3}, {"tomLow", "......x......x..|......x......x..|......x......x..|.x.x.x.x.xxxxxxx", gain = 0.45}}},
	-- Acid: a shuffled, swung groove with a ghosted clap, to leave room for the 303.
	{id = "techno.drums.015", role = "drums", bars = 2, energy = 0.58, density = 0.5, brightness = 0.55,
		tags = {"fourfloor", "swung", "shuffle", "driving"}, flavours = {"acid", "hypnotic"},
		lanes = {{"kick", "X...X...X...X..."}, {"clap", "....X.......X...|....X.......X..g", gain = 0.8, light = false},
			{"hat", "x.xxx.xxx.xxx.xx", gain = 0.25}, {"openHat", "..x...x...x...x.", gain = 0.45},
			{"rim", "...g..g...g..g.g", gain = 0.4, when = "complexity"}}},
	{id = "techno.drums.016", role = "drums", bars = 2, energy = 0.4, density = 0.35, brightness = 0.45,
		tags = {"fourfloor", "minimal", "swung", "sparse"}, flavours = {"minimal", "dub", "melodic"},
		lanes = {{"kick", "X...X...X...X...", gain = 0.9}, {"hat", "..x...x...x...x.", gain = 0.35},
			{"snap", "....x.......x...", gain = 0.5, light = false}, {"shaker", "x.xxx.xxx.xxx.xx", gain = 0.2, when = "energy"}}},

	---------------------------------------------------------------- tops
	-- A second layer over the kick loop: shakers, hats, percussion loops.
	{id = "techno.tops.001", role = "tops", bars = 1, energy = 0.3, density = 0.4, brightness = 0.8,
		tags = {"straight", "minimal", "mixable"},
		lanes = {{"shaker", "xoxoxoxoxoxoxoxo", gain = 0.3}}},
	{id = "techno.tops.002", role = "tops", bars = 2, energy = 0.42, density = 0.45, brightness = 0.8,
		tags = {"offbeat", "driving", "mixable"},
		lanes = {{"openHat", "..x...x...x...x.", gain = 0.45}, {"hat", "x.x.x.x.x.x.x.x.|x.x.x.x.x.x.xxx.", gain = 0.25}}},
	{id = "techno.tops.003", role = "tops", bars = 2, energy = 0.45, density = 0.5, brightness = 0.55,
		tags = {"syncopated", "minimal", "rhythmic"}, flavours = {"minimal", "hypnotic", "acid"},
		lanes = {{"conga", "..x..x.x..x.x..x|..x..x.x.x..x.x."}, {"tambourine", "..x...x...x...x.", gain = 0.5}}},
	{id = "techno.tops.004", role = "tops", bars = 2, energy = 0.4, density = 0.4, brightness = 0.7,
		tags = {"syncopated", "minimal", "rhythmic", "playful"}, flavours = {"minimal", "acid"},
		lanes = {{"clave", "x..x..x...x.x...|x..x...x..x.x..."}, {"cowbell", "......x.......x.", gain = 0.5},
			{"shaker", "xoxoxoxoxoxoxoxo", gain = 0.4}}},
	{id = "techno.tops.005", role = "tops", bars = 2, energy = 0.5, density = 0.45, brightness = 0.4,
		tags = {"hypnotic", "syncopated", "dark"}, flavours = {"hypnotic", "minimal", "peak"},
		lanes = {{"tomLow", "...x..x......x..|...x..x...x..x.."}, {"tomMid", ".........x......|.........x.....x", gain = 0.8},
			{"rim", "..x...x...x...x.", gain = 0.5}}},
	{id = "techno.tops.006", role = "tops", bars = 1, energy = 0.68, density = 0.7, brightness = 0.9,
		tags = {"driving", "rolling", "busy"}, flavours = {"peak", "industrial", "acid"},
		lanes = {{"hat", "xxxxxxxxxxxxxxxx", gain = 0.25}, {"ride", "..x...x...x...x.", gain = 0.4}}},
	{id = "techno.tops.007", role = "tops", bars = 2, energy = 0.62, density = 0.55, brightness = 0.6,
		tags = {"syncopated", "driving", "swung"}, flavours = {"peak", "acid", "melodic"},
		lanes = {{"rim", "...x..x....x..x.|...x..x....x.xx.", gain = 0.45}, {"clave", "x.....x...x.....", gain = 0.35},
			{"tambourine", "..x...x...x...x.", gain = 0.4}}},
	{id = "techno.tops.008", role = "tops", bars = 2, energy = 0.8, density = 0.8, brightness = 0.75,
		tags = {"aggressive", "busy", "driving"}, flavours = {"industrial", "peak"},
		lanes = {{"hat", "x.x.x.x.x.x.x.x.|xxxxxxxxxxxxxxxx", gain = 0.3}, {"tomLow", "...x..x......x..|...x..x...xxxxxx", gain = 0.45},
			{"snare", "................|............x.xx", gain = 0.4}}},
	{id = "techno.tops.009", role = "tops", bars = 4, energy = 0.35, density = 0.3, brightness = 0.6,
		tags = {"dub", "sparse", "mixable", "deep"}, flavours = {"dub", "melodic", "minimal"},
		lanes = {{"shaker", "x.xxx.xxx.xxx.xx|x.xxx.xxx.xxx.xx|x.xxx.xxx.xxx.xx|x.xxx.xxx.xxxxxx", gain = 0.2},
			{"rim", "................|............x...|................|....x.......x..."}}},

	---------------------------------------------------------------- bass
	-- Offbeat sub: one note on the "and" of each beat, between the kicks.
	{id = "techno.bass.001", role = "bass", bars = 1, energy = 0.45, density = 0.3, brightness = 0.1,
		tags = {"sub", "offbeat", "driving", "dark"}, excludes = {"rolling"},
		notes = "2:0:2 6:0:2 10:0:2 14:0:2"},
	-- The root alone: breakdown bass, dub pedal.
	{id = "techno.bass.002", role = "bass", bars = 2, energy = 0.25, density = 0.1, brightness = 0.1,
		tags = {"sub", "pedal", "sparse", "deep"}, flavours = {"dub", "hypnotic", "melodic"},
		notes = "0:0:14 | 0:0:10 12:0:4"},
	-- The rumble: a short note after each kick, the kick's tail turned into a line.
	{id = "techno.bass.003", role = "bass", bars = 1, energy = 0.7, density = 0.55, brightness = 0.15,
		tags = {"sub", "rolling", "driving", "dark", "pedal"}, flavours = {"peak", "industrial", "hypnotic"}, excludes = {"offbeat"},
		notes = "1:0:3 5:0:3 9:0:3 13:0:3"},
	{id = "techno.bass.004", role = "bass", bars = 1, energy = 0.8, density = 0.8, brightness = 0.25,
		tags = {"sub", "rolling", "driving", "aggressive"}, flavours = {"peak", "industrial"}, excludes = {"offbeat"},
		notes = "1:0:1 2:0:1 3:0:1 5:0:1 6:0:1 7:0:1 9:0:1 10:0:1 11:0:1 13:0:1 14:0:1 15:0:1"},
	{id = "techno.bass.005", role = "bass", bars = 2, energy = 0.65, density = 0.5, brightness = 0.2,
		tags = {"sub", "rolling", "driving", "hypnotic", "dark"}, flavours = {"peak", "hypnotic"}, excludes = {"offbeat"},
		notes = "1:0:3 5:0:3 9:0:3 13:0:3 | 1:0:3 5:0:3 9:0:3 12:6:1 13:0:3 15:7:1"},
	-- Acid: 303-style sixteenths with slides and accents; the tune of the track.
	{id = "techno.bass.006", role = "bass", bars = 2, energy = 0.75, density = 0.75, brightness = 0.7,
		tags = {"acid", "riff", "driving", "syncopated"}, flavours = {"acid"},
		notes = "0:0:1 2:0:1 3:7:1! 4:0:1~ 6:0:1 7:2:1 9:0:1 10:4:1!~ 12:3:1 14:0:1 15:7:1 | 0:0:1 2:0:1 3:7:1! 4:0:1~ 6:0:1 8:0:1 10:6:1! 11:4:1~ 13:2:1 14:0:2"},
	{id = "techno.bass.007", role = "bass", bars = 1, energy = 0.6, density = 0.6, brightness = 0.65,
		tags = {"acid", "hypnotic", "rhythmic"}, flavours = {"acid", "hypnotic"},
		notes = "0:0:1 1:0:1 3:0:1! 4:7:1~ 6:0:1 7:0:1 9:0:1! 10:2:1~ 12:0:1 14:0:1"},
	{id = "techno.bass.008", role = "bass", bars = 4, energy = 0.85, density = 0.8, brightness = 0.75,
		tags = {"acid", "riff", "aggressive", "leap"}, flavours = {"acid"},
		notes = "0:0:1 2:0:1 3:0:1 4:7:1!~ 6:0:1 7:0:1 9:3:1 10:0:1 12:7:1! 14:0:1 15:0:1 | 0:0:1 2:0:1 3:0:1 4:7:1!~ 6:0:1 7:6:1 9:4:1~ 10:3:1 12:2:1 14:0:2 | 0:0:1 2:0:1 3:0:1 4:7:1!~ 6:0:1 7:0:1 9:3:1 10:0:1 12:7:1! 14:0:1 15:0:1 | 0:0:1 3:2:1 4:0:1 6:3:1~ 7:4:1 9:6:1! 10:7:1~ 12:4:2 14:2:1 15:0:1"},
	{id = "techno.bass.009", role = "bass", bars = 2, energy = 0.4, density = 0.3, brightness = 0.55,
		tags = {"acid", "sparse", "minimal", "playful"}, flavours = {"acid", "minimal"},
		notes = "0:0:2 3:0:1! 6:7:1~ 10:0:2 | 0:0:2 3:0:1! 6:4:1~ 8:2:1 12:0:3"},
	-- Stomp and minor riffs on the grid.
	{id = "techno.bass.010", role = "bass", bars = 2, energy = 0.7, density = 0.6, brightness = 0.3,
		tags = {"stab", "riff", "driving", "syncopated"}, flavours = {"peak", "industrial", "minimal"},
		notes = "0:0:1 2:0:1 3:0:1? 6:7:1! 8:0:1 10:0:1 11:0:1? 14:6:1"},
	{id = "techno.bass.011", role = "bass", bars = 2, energy = 0.78, density = 0.65, brightness = 0.35,
		tags = {"riff", "dark", "aggressive", "syncopated"}, flavours = {"industrial", "peak"},
		notes = "2:0:1 3:0:1 6:0:1 7:2:1? 10:0:1 11:0:1 14:6:1 15:4:1+ | 2:0:1 3:0:1 6:0:1 7:2:1? 10:0:1 11:3:1 13:2:1 14:0:2"},
	{id = "techno.bass.012", role = "bass", bars = 2, energy = 0.5, density = 0.4, brightness = 0.2,
		tags = {"sub", "pedal", "hypnotic", "deep"}, flavours = {"hypnotic", "dub", "minimal"},
		notes = "0:0:6 10:0:2? 14:6:2 | 0:0:6 10:4:2? 13:2:3"},
	-- Minimal: a short pulse that moves one note every other bar.
	{id = "techno.bass.013", role = "bass", bars = 2, energy = 0.45, density = 0.45, brightness = 0.3,
		tags = {"pluck", "minimal", "rhythmic", "syncopated"}, flavours = {"minimal"},
		notes = "0:0:1 3:0:1 6:0:1 8:0:1 11:0:1? 14:0:1 | 0:0:1 3:0:1 6:2:1 8:0:1 11:0:1? 14:4:1"},
	{id = "techno.bass.014", role = "bass", bars = 2, energy = 0.55, density = 0.5, brightness = 0.3,
		tags = {"pluck", "offbeat", "melodic", "warm"}, flavours = {"melodic", "minimal"}, excludes = {"rolling"},
		notes = "2:0:2 6:0:2 10:0:2 14:4:2 | 2:0:2 6:0:2 10:2:2 14:4:2"},
	{id = "techno.bass.015", role = "bass", bars = 4, energy = 0.6, density = 0.5, brightness = 0.3,
		tags = {"pluck", "melodic", "walking", "warm", "offbeat"}, flavours = {"melodic"},
		notes = "2:0:2 6:0:2 10:0:2 14:7:2 | 2:0:2 6:0:2 10:2:2 14:4:2 | 2:0:2 6:0:2 10:0:2 14:7:2 | 2:6:2 6:4:2 10:3:2 14:2:2"},
	{id = "techno.bass.016", role = "bass", bars = 1, energy = 0.35, density = 0.25, brightness = 0.15,
		tags = {"sub", "sparse", "pedal", "minimal"},
		notes = "0:0:3 6:0:2 10:0:3"},

	---------------------------------------------------------------- pad
	-- Held chords are the wash under the plateau; the comp ones pulse in time.
	{id = "techno.pad.001", role = "pad", bars = 4, energy = 0.2, density = 0.1, brightness = 0.3,
		tags = {"held", "ambient", "dark", "deep"}, hold = true},
	{id = "techno.pad.002", role = "pad", bars = 4, energy = 0.35, density = 0.15, brightness = 0.45,
		tags = {"held", "dreamy", "warm"}, flavours = {"melodic", "dub", "hypnotic"}, hold = true},
	{id = "techno.pad.003", role = "pad", bars = 1, energy = 0.5, density = 0.3, brightness = 0.5,
		tags = {"chordal", "melancholic", "offbeat"}, flavours = {"melodic", "peak"},
		comp = "0:6 8:6"},
	{id = "techno.pad.004", role = "pad", bars = 1, energy = 0.7, density = 0.4, brightness = 0.6,
		tags = {"chordal", "tense", "driving", "syncopated"}, flavours = {"peak", "industrial"},
		comp = "0:3 3:3? 8:3 11:3?"},
	{id = "techno.pad.005", role = "pad", bars = 8, energy = 0.4, density = 0.1, brightness = 0.35,
		tags = {"held", "ambient", "hypnotic", "dark"}, flavours = {"hypnotic", "dub", "industrial"}, hold = true},

	---------------------------------------------------------------- keys
	-- Keys: slow chordal figures, the melodic flavour's harmony and dub chords.
	{id = "techno.keys.001", role = "keys", bars = 1, energy = 0.3, density = 0.2, brightness = 0.5,
		tags = {"chordal", "sparse", "warm", "deep"}, flavours = {"dub", "melodic", "hypnotic"},
		comp = "0:4 6:6"},
	{id = "techno.keys.002", role = "keys", bars = 1, energy = 0.45, density = 0.3, brightness = 0.55,
		tags = {"chordal", "offbeat", "soulful"}, flavours = {"dub", "minimal", "melodic"},
		comp = "3:3 11:3"},
	{id = "techno.keys.003", role = "keys", bars = 1, energy = 0.55, density = 0.4, brightness = 0.6,
		tags = {"chordal", "syncopated", "melancholic"}, flavours = {"melodic"},
		comp = "0:3 6:2 10:4!"},
	{id = "techno.keys.004", role = "keys", bars = 1, energy = 0.65, density = 0.5, brightness = 0.6,
		tags = {"chordal", "rhythmic", "driving"}, flavours = {"peak", "melodic", "acid"},
		comp = "0:2 3:2 6:2 10:2! 14:2"},
	{id = "techno.keys.005", role = "keys", bars = 1, energy = 0.4, density = 0.2, brightness = 0.45,
		tags = {"chordal", "held", "dreamy", "sparse"}, flavours = {"melodic", "dub"},
		comp = "0:6 8:6"},
	{id = "techno.keys.006", role = "keys", bars = 1, energy = 0.8, density = 0.6, brightness = 0.7,
		tags = {"chordal", "bright", "euphoric", "syncopated"}, flavours = {"melodic", "peak"},
		comp = "0:2 2:2 6:2 8:2 10:2! 14:2"},

	---------------------------------------------------------------- stab
	-- The dub chord, thrown into the delay: one or two hits a bar.
	{id = "techno.stab.001", role = "stab", bars = 1, energy = 0.25, density = 0.1, brightness = 0.5,
		tags = {"chordal", "sparse", "deep", "hypnotic"}, flavours = {"dub", "hypnotic"},
		comp = "3:1"},
	{id = "techno.stab.002", role = "stab", bars = 1, energy = 0.35, density = 0.15, brightness = 0.5,
		tags = {"chordal", "sparse", "deep", "dub"}, flavours = {"dub"},
		comp = "10:1"},
	{id = "techno.stab.003", role = "stab", bars = 1, energy = 0.45, density = 0.3, brightness = 0.5,
		tags = {"chordal", "offbeat", "hypnotic", "syncopated"}, flavours = {"hypnotic", "dub", "minimal"},
		comp = "3:1 9:1 12:1"},
	{id = "techno.stab.004", role = "stab", bars = 1, energy = 0.55, density = 0.4, brightness = 0.6,
		tags = {"chordal", "offbeat", "driving"},
		comp = "2:1 6:1 10:1 14:1"},
	{id = "techno.stab.005", role = "stab", bars = 1, energy = 0.6, density = 0.4, brightness = 0.65,
		tags = {"rhythmic", "syncopated", "tense", "driving"}, flavours = {"peak", "industrial", "acid"},
		comp = "0:1 3:1 6:1 10:1! 14:1?"},
	{id = "techno.stab.006", role = "stab", bars = 1, energy = 0.7, density = 0.5, brightness = 0.7,
		tags = {"rhythmic", "aggressive", "dark", "driving"}, flavours = {"industrial", "peak"},
		comp = "0:1! 3:1 7:1 10:1! 12:1 14:1?"},
	{id = "techno.stab.007", role = "stab", bars = 1, energy = 0.5, density = 0.3, brightness = 0.55,
		tags = {"rhythmic", "hypnotic", "syncopated", "minimal"}, flavours = {"minimal", "hypnotic"},
		comp = "3:1 7:1? 11:1?"},
	{id = "techno.stab.008", role = "stab", bars = 1, energy = 0.85, density = 0.65, brightness = 0.8,
		tags = {"rhythmic", "aggressive", "bright", "busy"}, flavours = {"peak", "industrial"},
		comp = "0:1! 2:1 3:1 6:1 8:1! 10:1 11:1 14:1"},
	{id = "techno.stab.009", role = "stab", bars = 1, energy = 0.65, density = 0.45, brightness = 0.6,
		tags = {"chordal", "soulful", "offbeat", "playful"}, flavours = {"minimal", "melodic", "acid"},
		comp = "2:2 6:1 10:2 14:1?"},

	---------------------------------------------------------------- arp
	-- Arps: chord tones in order; the mask lets Complexity open the gaps.
	{id = "techno.arp.001", role = "arp", bars = 1, energy = 0.4, density = 0.4, brightness = 0.7,
		tags = {"arpeggio", "hypnotic", "stepwise", "ambient"}, flavours = {"hypnotic", "dub", "minimal"},
		order = {1, 2, 3, 2}, rate = 2, gate = 0.5, mask = "XXXXXXXXXXXXXXXX", octave = 2},
	{id = "techno.arp.002", role = "arp", bars = 1, energy = 0.55, density = 0.6, brightness = 0.75,
		tags = {"arpeggio", "driving", "hypnotic"}, flavours = {"peak", "hypnotic", "melodic"},
		order = {1, 2, 3, 4, 3, 2}, rate = 1, gate = 0.5, mask = "XXxxXXxxXXxxXXxx", octave = 1},
	{id = "techno.arp.003", role = "arp", bars = 1, energy = 0.5, density = 0.4, brightness = 0.7,
		tags = {"arpeggio", "syncopated", "playful"}, flavours = {"minimal", "acid"},
		order = {1, 3, 2, 4}, rate = 2, gate = 0.4, mask = "X.xXx.XxX.xXx.Xx", octave = 1},
	{id = "techno.arp.004", role = "arp", bars = 2, energy = 0.7, density = 0.75, brightness = 0.8,
		tags = {"arpeggio", "rolling", "tense", "busy"}, flavours = {"peak", "industrial", "acid"},
		order = {1, 1, 3, 1, 4, 3, 2, 3}, rate = 1, gate = 0.45, mask = "XXXxXXxxXXXxXxXX", octave = 1},
	{id = "techno.arp.005", role = "arp", bars = 1, energy = 0.35, density = 0.25, brightness = 0.6,
		tags = {"arpeggio", "sparse", "dreamy", "stepwise"}, flavours = {"melodic", "dub"},
		order = {1, 2, 3, 4, 3, 2, 1, 2}, rate = 4, gate = 0.9, mask = "X...X...X...X...", octave = 2},
	{id = "techno.arp.006", role = "arp", bars = 1, energy = 0.62, density = 0.55, brightness = 0.7,
		tags = {"arpeggio", "euphoric", "leap", "melancholic"}, flavours = {"melodic", "peak"},
		order = {1, 3, 4, 3, 4, 2, 4, 3}, rate = 1, gate = 0.6, mask = "XxXxXxXxXxXxXxXx", octave = 1},
	{id = "techno.arp.007", role = "arp", bars = 1, energy = 0.8, density = 0.9, brightness = 0.85,
		tags = {"arpeggio", "aggressive", "busy", "dark"}, flavours = {"industrial", "peak"},
		order = {1, 4, 1, 3, 1, 4, 2, 3}, rate = 1, gate = 0.35, mask = "XXXXXXXXXXXXXXXX", octave = 1},
	{id = "techno.arp.008", role = "arp", bars = 2, energy = 0.3, density = 0.3, brightness = 0.65,
		tags = {"arpeggio", "hypnotic", "sparse", "minimal"}, flavours = {"hypnotic", "minimal"},
		order = {1, 3, 2}, rate = 2, gate = 0.6, mask = "X.XxX.XxX.XxX.Xx", octave = 2},

	---------------------------------------------------------------- lead
	-- Short one-note and two-note hooks that nag (hypnotic, peak), then longer
	-- melodies for the melodic flavour. All stay on chord and scale steps.
	{id = "techno.lead.001", role = "lead", bars = 1, energy = 0.5, density = 0.3, brightness = 0.6,
		tags = {"hook", "hypnotic", "rhythmic", "minimal"}, flavours = {"peak", "hypnotic", "industrial"},
		notes = "0:0:1 3:0:1 6:0:1 10:0:1"},
	{id = "techno.lead.002", role = "lead", bars = 2, energy = 0.6, density = 0.4, brightness = 0.65,
		tags = {"hook", "rhythmic", "syncopated", "tense"}, flavours = {"peak", "industrial"},
		notes = "0:0:1 3:0:1 6:0:1 10:0:1 12:2:1 | 0:0:1 3:0:1 6:0:1 10:0:1 12:3:1 14:2:1"},
	{id = "techno.lead.003", role = "lead", bars = 2, energy = 0.7, density = 0.45, brightness = 0.7,
		tags = {"hook", "leap", "dark", "driving"}, flavours = {"peak", "industrial"},
		notes = "0:0:1 2:7:1! 4:0:1 7:6:1 10:4:1 12:0:2 | 0:0:1 2:7:1! 4:0:1 7:6:1 10:4:1 12:6:2"},
	{id = "techno.lead.004", role = "lead", bars = 1, energy = 0.8, density = 0.5, brightness = 0.8,
		tags = {"hook", "aggressive", "rhythmic", "riff"}, flavours = {"peak", "industrial"},
		notes = "0:0:1! 1:0:1 3:7:1 6:6:1 8:0:1! 9:0:1 11:7:1 14:4:1"},
	{id = "techno.lead.005", role = "lead", bars = 4, energy = 0.45, density = 0.3, brightness = 0.55,
		tags = {"hook", "hypnotic", "stepwise", "dreamy"}, flavours = {"hypnotic", "minimal", "dub"},
		notes = "0:0:3 6:2:2 10:0:2 | 0:0:3 6:2:2 10:3:2 | 0:0:3 6:2:2 10:0:2 | 0:0:3 6:3:2 10:2:4"},
	{id = "techno.lead.006", role = "lead", bars = 2, energy = 0.4, density = 0.25, brightness = 0.6,
		tags = {"hook", "sparse", "playful", "minimal", "answer"}, flavours = {"minimal", "acid"},
		notes = "2:0:1 5:2:1 10:4:1 | 3:2:1 6:0:1 13:4:1"},
	{id = "techno.lead.007", role = "lead", bars = 4, energy = 0.65, density = 0.4, brightness = 0.6,
		tags = {"hook", "stepwise", "melancholic", "euphoric"}, flavours = {"melodic"},
		notes = "0:4:4 4:2:4 8:0:4 12:2:2 | 0:3:4 4:2:4 8:0:6 | 0:4:4 4:6:4 8:7:4 12:6:2 | 0:4:4 4:3:4 8:2:6"},
	{id = "techno.lead.008", role = "lead", bars = 4, energy = 0.75, density = 0.5, brightness = 0.7,
		tags = {"hook", "leap", "euphoric", "melancholic"}, flavours = {"melodic"},
		notes = "0:0:2 3:2:1 4:4:4 10:7:2 | 0:6:2 3:4:1 4:2:4 10:3:2 | 0:0:2 3:2:1 4:4:4 10:7:2 | 0:6:2 3:7:1 4:9:6 12:7:2"},
	{id = "techno.lead.009", role = "lead", bars = 2, energy = 0.55, density = 0.45, brightness = 0.7,
		tags = {"hook", "stepwise", "rhythmic", "melancholic"}, flavours = {"melodic", "acid"},
		notes = "0:2:2 2:3:2 4:4:4 8:3:2 10:2:2 | 0:0:2 2:2:2 4:3:4 8:2:4 12:0:2"},
	{id = "techno.lead.010", role = "lead", bars = 1, energy = 0.3, density = 0.15, brightness = 0.55,
		tags = {"hook", "held", "sparse", "dreamy", "ambient"}, flavours = {"melodic", "dub", "hypnotic"},
		notes = "0:4:12"},
	{id = "techno.lead.011", role = "lead", bars = 2, energy = 0.9, density = 0.7, brightness = 0.85,
		tags = {"hook", "aggressive", "riff", "busy", "tense"}, flavours = {"peak", "industrial"},
		notes = "0:0:1! 1:0:1 2:0:1 4:7:1 6:6:1 7:4:1 8:0:1! 9:0:1 10:0:1 12:2:1 14:3:1 | 0:0:1! 1:0:1 2:0:1 4:7:1 6:6:1 7:4:1 8:0:1! 9:0:1 10:3:1 12:2:1 14:0:2"},
	{id = "techno.lead.012", role = "lead", bars = 2, energy = 0.5, density = 0.4, brightness = 0.7,
		tags = {"hook", "acid", "rhythmic", "syncopated"}, flavours = {"acid", "peak"},
		notes = "0:0:1 3:0:1 4:7:1!~ 6:0:1 9:0:1 10:2:1~ 12:4:2 | 0:0:1 3:0:1 4:7:1!~ 6:0:1 9:0:1 10:3:1~ 12:2:2"},
	{id = "techno.lead.013", role = "lead", bars = 4, energy = 0.35, density = 0.2, brightness = 0.5,
		tags = {"hook", "sparse", "hypnotic", "minimal", "stepwise"}, flavours = {"minimal", "hypnotic"},
		notes = "4:0:2 8:2:2 | 4:0:2 8:2:2 12:3:2 | 4:0:2 8:2:2 | 4:3:2 8:2:2 12:0:2"},

	---------------------------------------------------------------- counter
	-- Answers: sparse, high, often on the beat the lead leaves empty.
	{id = "techno.counter.001", role = "counter", bars = 2, energy = 0.3, density = 0.15, brightness = 0.75,
		tags = {"answer", "sparse", "dreamy", "minimal"}, flavours = {"minimal", "hypnotic", "dub"},
		notes = "10:4:2 | 6:2:2 12:4:3"},
	{id = "techno.counter.002", role = "counter", bars = 2, energy = 0.45, density = 0.3, brightness = 0.75,
		tags = {"answer", "playful", "syncopated", "minimal"}, flavours = {"minimal", "acid"},
		notes = "7:4:1 9:2:1 11:4:1 14:7:1 | 7:4:1 9:3:1 11:2:1 13:0:3"},
	{id = "techno.counter.003", role = "counter", bars = 4, energy = 0.5, density = 0.3, brightness = 0.7,
		tags = {"answer", "stepwise", "melancholic"}, flavours = {"melodic"},
		notes = "8:4:4 | 8:3:2 12:2:4 | 8:4:4 | 8:3:2 10:2:2 12:0:4"},
	{id = "techno.counter.004", role = "counter", bars = 1, energy = 0.6, density = 0.4, brightness = 0.8,
		tags = {"answer", "rhythmic", "tense"}, flavours = {"peak", "industrial", "acid"},
		notes = "5:7:1 7:6:1 11:7:1 13:4:1 15:6:1"},
	{id = "techno.counter.005", role = "counter", bars = 2, energy = 0.7, density = 0.5, brightness = 0.85,
		tags = {"answer", "leap", "euphoric", "bright"}, flavours = {"melodic", "peak"},
		notes = "8:7:2 10:6:2 12:4:4 | 8:7:2 10:9:2 12:7:4"},
	{id = "techno.counter.006", role = "counter", bars = 1, energy = 0.4, density = 0.2, brightness = 0.65,
		tags = {"answer", "sparse", "hypnotic"},
		notes = "6:2:1 9:4:1 14:2:1"},

	---------------------------------------------------------------- texture
	-- Drones and washes in semitones above the key: root and fifth, the minor
	-- third for sadness, the b2 for phrygian menace.
	{id = "techno.texture.001", role = "texture", bars = 4, energy = 0.2, density = 0.1, brightness = 0.3,
		tags = {"ambient", "dark", "deep", "held"}, voices = {0, 7}, every = 4},
	{id = "techno.texture.002", role = "texture", bars = 4, energy = 0.3, density = 0.15, brightness = 0.45,
		tags = {"ambient", "dreamy", "melancholic", "held"}, flavours = {"melodic", "dub", "hypnotic"}, voices = {0, 3, 7}, every = 4},
	{id = "techno.texture.003", role = "texture", bars = 8, energy = 0.4, density = 0.1, brightness = 0.35,
		tags = {"ambient", "tense", "dark", "held"}, flavours = {"industrial", "peak", "hypnotic"}, voices = {0, 1, 7}, every = 8},
	{id = "techno.texture.004", role = "texture", bars = 4, energy = 0.25, density = 0.1, brightness = 0.6,
		tags = {"ambient", "deep", "hypnotic", "held"}, flavours = {"dub", "minimal"}, voices = {0, 12}, every = 2},
	{id = "techno.texture.005", role = "texture", bars = 4, energy = 0.5, density = 0.2, brightness = 0.5,
		tags = {"ambient", "dark", "aggressive", "held"}, flavours = {"industrial"}, voices = {0, 6, 12}, every = 4},

	---------------------------------------------------------------- fx
	-- One-shots on a phrase boundary; no risers (see the head of the file).
	{id = "techno.fx.001", role = "fx", bars = 1, energy = 0.7, density = 0.1, brightness = 0.9,
		tags = {"crash"}, kind = "crash"},
	{id = "techno.fx.002", role = "fx", bars = 1, energy = 0.8, density = 0.1, brightness = 0.3,
		tags = {"impact", "dark"}, kind = "impact"},
	{id = "techno.fx.003", role = "fx", bars = 4, energy = 0.4, density = 0.1, brightness = 0.5,
		tags = {"downlifter", "deep"}, kind = "downlifter"},
}
