#include <lua.h>
#include <lauxlib.h>

#ifndef LUA_MODULE_OPEN
#error "LUA_MODULE_OPEN must name the luaopen_* entry point"
#endif

#ifndef LUA_MODULE_BYTES
#error "LUA_MODULE_BYTES must name the embedded Lua byte array"
#endif

#ifndef LUA_MODULE_LENGTH
#error "LUA_MODULE_LENGTH must name the embedded Lua byte-array length"
#endif

#ifndef LUA_MODULE_HEADER
#error "LUA_MODULE_HEADER must name the generated byte-array header"
#endif

#ifndef LUA_MODULE_CHUNK_NAME
#error "LUA_MODULE_CHUNK_NAME must identify the embedded Lua source"
#endif

#include LUA_MODULE_HEADER

/*
 * Public framework modules are native Lua modules even though their
 * declarative conveniences remain authored in Lua. Embedding that source
 * keeps require("AppKit") atomic: Lua loads one dylib, and the dylib returns
 * the fully assembled API table produced by the framework's Lua chunk.
 */
int LUA_MODULE_OPEN(lua_State *L) {
	int status = luaL_loadbufferx(
		L,
		(const char *)LUA_MODULE_BYTES,
		(size_t)LUA_MODULE_LENGTH,
		LUA_MODULE_CHUNK_NAME,
		"t");
	if (status != LUA_OK) {
		return lua_error(L);
	}

	status = lua_pcall(L, 0, 1, 0);
	if (status != LUA_OK) {
		return lua_error(L);
	}
	return 1;
}
