-- File kinds by extension, the way Finder's Kind column and disk analyzers
-- such as Disk Inventory X and WinDirStat group them. Extensions are
-- lowercase and without the dot. Package formats that are folders on disk
-- (.app, .photoslibrary, .xcarchive) never appear here: the scanner reports
-- the files inside them. `advice` is what people most often do about each
-- kind when a disk fills up.
return {
	{id = "video", name = "Videos", icon = "film.fill", color = "systemPink",
		extensions = {"mov", "mp4", "m4v", "mkv", "avi", "webm", "mts", "m2ts", "mpg", "mpeg", "wmv", "flv", "3gp", "braw", "r3d", "mxf", "prores"},
		advice = "Screen recordings and exported edits are often the largest forgotten files. Move finished footage to an external drive or delete exports you can render again."},
	{id = "images", name = "Photos & images", icon = "photo.fill", color = "systemOrange",
		extensions = {"heic", "heif", "jpg", "jpeg", "png", "gif", "tif", "tiff", "webp", "bmp", "raw", "cr2", "cr3", "nef", "arw", "orf", "rw2", "dng", "psd", "psb", "ai", "svg", "exr", "avif", "jxl"},
		advice = "Photos library originals are managed in Photos; loose RAW and PSD files are usually the ones to archive."},
	{id = "audio", name = "Music & audio", icon = "music.note", color = "systemRed",
		extensions = {"mp3", "m4a", "m4b", "m4p", "aac", "wav", "aif", "aiff", "aifc", "flac", "alac", "caf", "ogg", "opus", "wma", "mid", "midi"},
		advice = "Uncompressed WAV and AIFF recordings are ten times larger than AAC. Sound libraries are managed by GarageBand and Logic."},
	{id = "installers", name = "Disk images & installers", icon = "opticaldiscdrive.fill", color = "systemTeal",
		extensions = {"dmg", "iso", "img", "pkg", "mpkg", "xip", "ipsw", "sparseimage", "cdr", "toast", "msi", "exe", "apk", "ipa"},
		advice = "Once an app is installed its .dmg or .pkg is no longer needed. Installers can be downloaded again."},
	{id = "archives", name = "Archives", icon = "doc.zipper", color = "systemBrown",
		extensions = {"zip", "tar", "gz", "tgz", "bz2", "tbz", "xz", "txz", "7z", "rar", "zst", "lz4", "lzma", "cpgz", "sit", "sitx"},
		advice = "Archives are often downloaded, expanded and forgotten. Keep the expanded copy or the archive, not both."},
	{id = "vms", name = "Virtual machine disks", icon = "desktopcomputer", color = "systemIndigo",
		extensions = {"vmdk", "vdi", "vhd", "vhdx", "hdd", "hds", "qcow2", "qcow", "raw", "utm", "ova", "ovf", "vmem", "vmsn"},
		advice = "Guest disks grow but rarely shrink. Delete unused machines and snapshots in the owning app, never in Finder."},
	{id = "models", name = "AI models & datasets", icon = "cpu", color = "systemPurple",
		extensions = {"gguf", "ggml", "safetensors", "ckpt", "pt", "pth", "onnx", "mlmodel", "mlpackage", "h5", "hdf5", "tflite", "npz", "npy", "parquet", "arrow", "pkl", "bin"},
		advice = "Model weights are re-downloadable and several gigabytes each. Remove models you no longer run with their tool."},
	{id = "documents", name = "Documents", icon = "doc.text.fill", color = "systemBlue",
		extensions = {"pdf", "doc", "docx", "pages", "key", "numbers", "xls", "xlsx", "ppt", "pptx", "rtf", "rtfd", "txt", "md", "epub", "csv", "odt", "ods", "odp", "tex", "sketch", "fig", "indd"},
		advice = "Documents are rarely large on their own; scanned PDFs and slide decks with video are the exceptions."},
	{id = "databases", name = "Databases & app data", icon = "cylinder.split.1x2.fill", color = "systemGreen",
		extensions = {"db", "sqlite", "sqlite3", "sqlitedb", "realm", "store", "musicdb", "itdb", "ldb", "wal", "shm", "sqlite-wal", "sqlite-shm", "lrcat", "plist"},
		advice = "Databases belong to the apps that write them. Clean them up inside the app; deleting the file corrupts its library."},
	{id = "developer", name = "Code & build products", icon = "hammer.fill", color = "systemMint",
		extensions = {"o", "a", "dylib", "so", "dsym", "pcm", "swiftmodule", "swiftdoc", "jar", "class", "js", "mjs", "cjs", "map", "ts", "wasm", "node", "pyc", "whl", "rlib", "rmeta", "d", "idx", "pack", "xcassets", "car"},
		advice = "Build products and dependency caches are regenerated by builds. Review them on the Developer page."},
	{id = "other", name = "Other files", icon = "doc.fill", color = "systemGray", extensions = {},
		advice = "Files without a recognized extension: app resources, caches and system data."},
}
