-- A field guide to where macOS keeps things and why they grow. Each topic is
-- plain data: `resources` names catalog ids whose live measurements appear
-- beside the text, and `open` names the Diskmap category that manages them.
-- Statements describe current macOS (Big Sur and later) and avoid promising
-- sizes; "typically" figures are orders of magnitude, not measurements.
return {
	{id = "layout", title = "How your disk is organized", icon = "internaldrive", topics = {
		{id = "container", title = "One disk, several volumes", icon = "square.stack.3d.up",
			paths = {"diskutil apfs list"},
			summary = "Your internal disk is one APFS container shared by several volumes.",
			what = "Macintosh HD, Macintosh HD – Data, Preboot, Recovery, VM and Update all live in one APFS container. They draw from the same pool of free space, which is why Disk Utility shows the same free amount for each of them.",
			why = "Space moves between volumes on demand, so a volume's size is simply what it currently uses. Nothing is reserved or wasted by the partition layout.",
			action = "No action needed. Run the command above in Terminal to see every volume and what it uses."},
		{id = "system-volume", title = "Macintosh HD (the system volume)", icon = "lock.shield",
			paths = {"/", "/System"}, resources = {"system", "unix"}, open = "macos",
			summary = "A sealed, read-only snapshot of macOS itself.",
			what = "Since macOS Big Sur the operating system lives on a Signed System Volume: a cryptographically sealed, read-only snapshot. Your Mac boots from that snapshot and verifies it, so nothing can modify macOS files.",
			why = "It holds the operating system and its bundled apps. It changes only when macOS updates, and a new sealed snapshot replaces the old one.",
			action = "Nothing to clean. Its size is fixed by the macOS version you run."},
		{id = "data-volume", title = "Macintosh HD – Data", icon = "person.crop.circle",
			paths = {"/System/Volumes/Data", "/Users", "/Applications", "/Library"},
			summary = "Everything that is yours: apps, files, settings and caches.",
			what = "Your home folder, installed apps, /Library and most of what macOS writes at runtime live on the Data volume. Firmlinks merge it into / so that /Users or /Applications look like ordinary folders at the top of the disk.",
			why = "Every category Diskmap measures, apart from boot, recovery and swap, is on this volume. Because the same folder is reachable by two paths, Diskmap counts each location once.",
			action = "Review it by category in Overview."},
		{id = "library-domains", title = "Three Library folders", icon = "books.vertical",
			paths = {"/System/Library", "/Library", "~/Library"}, resources = {"library-user", "library-shared"},
			summary = "Apple's, the Mac's and yours, in that order.",
			what = "/System/Library belongs to macOS and is read-only. /Library holds resources shared by all accounts, such as fonts, printer drivers, launch agents and app support installed by administrators. ~/Library belongs to your account: settings, caches, app data and containers.",
			why = "Apps store most of their hidden data in ~/Library, which Finder hides by default. That is where most \"mystery\" storage lives.",
			action = "In Finder, choose Go, hold Option and pick Library to open it. Diskmap already breaks it down by owner."},
	}},
	{id = "boot", title = "Boot, recovery and updates", icon = "bolt.shield", topics = {
		{id = "preboot", title = "Preboot", icon = "power",
			paths = {"/System/Volumes/Preboot"}, resources = {"preboot"}, open = "macos",
			summary = "Files your Mac needs before macOS itself can start.",
			what = "Preboot holds boot kernel collections, the FileVault unlock screen and, since macOS Ventura, the cryptexes that carry Safari and the system's shared code cache. Rapid Security Responses update those cryptexes without a full macOS update.",
			why = "Several gigabytes is normal. It grows while a software update is prepared or waiting to install, and it holds a set of boot files for every macOS installed in the container.",
			action = "Never delete anything here: your Mac may stop booting. Install or restart a pending update in System Settings › General › Software Update, and Preboot shrinks once it finishes."},
		{id = "recovery", title = "Recovery", icon = "lifepreserver",
			paths = {"/System/Volumes/Recovery"}, resources = {"recovery"}, open = "macos",
			summary = "The recoveryOS you start when something goes wrong.",
			what = "Recovery can reinstall macOS, restore from Time Machine, repair disks with Disk Utility and change startup security. Apple silicon Macs also keep a fallback recoveryOS in a separate, hidden container.",
			why = "It is a small, complete operating system. macOS updates it together with the main system.",
			action = "Keep it. Without Recovery you cannot reinstall macOS from this Mac."},
		{id = "updates", title = "Where software updates go", icon = "arrow.down.circle",
			paths = {"/System/Library/AssetsV2/com_apple_MobileAsset_MacSoftwareUpdate", "/System/Volumes/Update", "/Applications/Install macOS ….app"},
			resources = {"update-assets"}, open = "system-data",
			summary = "Downloaded, prepared, then installed, in three places.",
			what = "Software Update downloads macOS updates into the system asset store (AssetsV2). While \"Preparing\", it expands them into the Update and Preboot volumes. A full installer from the App Store is a separate \"Install macOS\" app in /Applications.",
			why = "A download that is paused, deferred or failed can stay in the asset store and in Preboot until macOS retries or purges it. That often shows up as unexplained System Data. Before Big Sur, updates went to /Library/Updates.",
			action = "Finish or retry the update in System Settings › General › Software Update. Delete an \"Install macOS\" app once you no longer need it; it can be downloaded again."},
		{id = "vm", title = "Swap and sleep image", icon = "memorychip",
			paths = {"/System/Volumes/VM", "/private/var/vm"}, resources = {"vm"}, open = "macos",
			summary = "Memory that spilled onto the disk.",
			what = "When apps need more memory than your Mac has, macOS compresses memory and then pages it out to swap files on the VM volume. Intel Macs can also keep a sleep image there, about the size of your RAM, for hibernation.",
			why = "Swap grows under memory pressure and does not always shrink straight away.",
			action = "Quit memory-hungry apps or restart to release swap. Never delete swap files by hand."},
		{id = "snapshots", title = "Local snapshots", icon = "clock.arrow.circlepath",
			paths = {"tmutil listlocalsnapshots /"}, resources = {"snapshots"}, open = "backups",
			summary = "Point-in-time copies that keep deleted files' blocks alive.",
			what = "Time Machine takes local APFS snapshots about every hour and keeps them for 24 hours, plus one for your last successful backup. A snapshot still references the blocks of files you have since deleted.",
			why = "That is why deleting a large file sometimes frees nothing at first. Snapshots share blocks with live files, so no file scan can say how much each one holds exclusively.",
			action = "macOS removes snapshots automatically when it needs the space. The Terminal command above lists them."},
		{id = "free-space", title = "Free, available and purgeable", icon = "gauge.with.dots.needle.33percent",
			paths = {},
			summary = "Why Finder and Diskmap can disagree about free space.",
			what = "Diskmap shows the free space reported by the file system. Finder and System Settings show available space, which also includes purgeable data: local snapshots, iCloud files that can be downloaded again, and caches macOS may clear on demand.",
			why = "Purgeable storage is counted as used until macOS actually removes it, so available is usually larger than free.",
			action = "When an app needs room, macOS purges automatically. You can also turn on Optimize Mac Storage in iCloud and Photos settings."},
	}},
	{id = "system-data", title = "System Data, explained", icon = "gearshape.2", topics = {
		{id = "what-is-system-data", title = "What \"System Data\" means", icon = "questionmark.circle",
			paths = {}, open = "system-data",
			summary = "macOS's catch-all for storage it does not name.",
			what = "In System Settings › Storage, System Data is everything that is not in a named category: caches, logs, local snapshots, swap, app support files, developer tools, virtual machines and downloaded system assets.",
			why = "Developers and heavy app users often see tens of gigabytes because Xcode, Docker and AI tools keep their data in places macOS files under System Data.",
			action = "Diskmap splits it by owner. See System Data, Developer and AI agents in Overview."},
		{id = "assets", title = "Downloaded system assets", icon = "square.and.arrow.down.on.square",
			paths = {"/System/Library/AssetsV2"}, resources = {"mobile-assets"}, open = "system-data",
			summary = "Components macOS downloads only when a feature needs them.",
			what = "The MobileAsset store holds speech and Dictation models, Siri and Apple Intelligence models, voices, fonts, dictionaries, translation models, wallpapers, simulator runtimes and pending software updates.",
			why = "Each feature you use downloads its own assets, and some are several gigabytes. Turning a feature off does not guarantee that macOS removes its assets straight away.",
			action = "Manage the feature in System Settings. macOS decides when to remove its assets; do not delete them by hand."},
		{id = "caches", title = "Caches", icon = "externaldrive",
			paths = {"~/Library/Caches", "/Library/Caches"}, resources = {"user-caches", "system-caches"}, open = "system-data",
			summary = "Data apps can rebuild, most of the time.",
			what = "Apps keep downloaded images, compiled code, thumbnails and offline content in their cache folders so they start and load faster.",
			why = "Caches grow until the owning app trims them. Browsers, chat apps, music streaming and creative tools are the usual heavyweights.",
			action = "Clear a cache from the owning app. Deleting whole cache folders can sign you out, lose offline downloads and slow the next launch."},
		{id = "temporary", title = "/private/var/folders", icon = "doc.badge.clock",
			paths = {"/private/var/folders"}, resources = {"temporary"}, open = "system-data",
			summary = "Per-user temporary files and system caches.",
			what = "Each account gets a randomly named folder here for temporary files ($TMPDIR) and caches that services such as Quick Look, fonts and the App Store rebuild.",
			why = "Crashed or long-running apps can leave large temporary files behind.",
			action = "macOS removes stale temporary files, and restarting helps. Do not delete these folders while you are logged in."},
		{id = "logs", title = "Logs and diagnostics", icon = "doc.text.magnifyingglass",
			paths = {"~/Library/Logs", "/Library/Logs", "/private/var/log", "/private/var/db/diagnostics"},
			resources = {"user-logs", "shared-logs", "private-logs"}, open = "system-data",
			summary = "Crash reports and the unified system log.",
			what = "Apps write logs and crash reports to the Logs folders. The unified log in /private/var/db/diagnostics records system activity for Console.",
			why = "macOS rotates its logs automatically. A misbehaving app can still fill its own log folder quickly.",
			action = "Review large app logs by owner. Leave the unified log to macOS."},
	}},
	{id = "apps", title = "Where apps keep your data", icon = "app.badge", topics = {
		{id = "app-support", title = "Application Support", icon = "shippingbox",
			paths = {"~/Library/Application Support"}, resources = {"support"}, open = "system-data",
			summary = "Databases, downloads and state that apps cannot rebuild.",
			what = "Apps keep libraries, databases, downloaded models, plug-ins and saved state here. Unlike caches, much of it cannot be recreated.",
			why = "Chat history, editor workspaces, game data and creative libraries accumulate here for years, including data left behind by apps you deleted.",
			action = "Review folders by owner. Remove leftovers only for apps you have uninstalled and no longer need."},
		{id = "containers", title = "Containers and Group Containers", icon = "cube.transparent",
			paths = {"~/Library/Containers", "~/Library/Group Containers"}, resources = {"app-containers", "group-containers"}, open = "system-data",
			summary = "Private homes for sandboxed apps.",
			what = "Each sandboxed app, including most Apple and App Store apps, gets its own Container with a private Library and Documents. Related apps share a Group Container.",
			why = "Mail, Messages, Photos helpers, Docker and chat apps can keep gigabytes inside their containers.",
			action = "Deleting a container resets that app completely. Manage data from inside the app instead."},
		{id = "ios-backups", title = "iPhone and iPad backups", icon = "iphone",
			paths = {"~/Library/Application Support/MobileSync/Backup"}, resources = {"ios-files"}, open = "ios-files",
			summary = "Full device backups made by Finder.",
			what = "Every local backup of an iPhone or iPad is a folder here. Encrypted backups also include saved passwords and Health data.",
			why = "Each backup can be as large as the data on the device, and old devices keep their backups after you replace them.",
			action = "In Finder, select the device and click Manage Backups to delete the ones you no longer need."},
		{id = "mail-messages", title = "Mail and Messages", icon = "envelope",
			paths = {"~/Library/Mail", "~/Library/Messages/Attachments"}, resources = {"mail-library", "messages-library"}, open = "mail-library",
			summary = "Downloaded mail and every photo you were ever sent.",
			what = "Mail keeps a local copy of your mailboxes and attachments. Messages keeps conversations and attachments unless you tell it otherwise.",
			why = "Years of attachments add up, especially videos in Messages.",
			action = "In Messages settings, set Keep Messages to 1 year or 30 days, or delete large attachments in System Settings › General › Storage. Manage Mail from Mail."},
		{id = "trash", title = "Trash", icon = "trash",
			paths = {"~/.Trash"}, resources = {"trash"}, open = "trash",
			summary = "Moving to Trash frees nothing until you empty it.",
			what = "Items you delete in Finder move to your Trash folder. External drives keep their own hidden .Trashes folder.",
			why = "Trash still uses disk space. Finder can empty it automatically after 30 days if you turn that on.",
			action = "Empty the Trash in Finder, or turn on Remove items from the Trash after 30 days in Finder settings."},
	}},
	{id = "developer", title = "Developer storage", icon = "hammer", topics = {
		{id = "derived-data", title = "DerivedData", icon = "gearshape.2",
			paths = {"~/Library/Developer/Xcode/DerivedData"}, resources = {"derived"}, open = "xcode",
			summary = "Xcode's build products and indexes.",
			what = "Every project you build gets a folder of intermediate files, products, logs and its code index.",
			why = "Folders for old projects and branches are never removed automatically.",
			action = "Safe to remove while Xcode is closed. The next build and indexing take longer."},
		{id = "simulator-devices", title = "Simulator devices", icon = "iphone",
			paths = {"~/Library/Developer/CoreSimulator/Devices"}, resources = {"simulators"}, open = "simulators",
			summary = "Every simulator is a complete device with its own data.",
			what = "Each simulated iPhone, iPad, Watch or Vision Pro has installed apps, settings and data. Devices whose runtime was removed become unavailable but keep their data.",
			why = "Testing across many devices and OS versions leaves dozens of devices behind.",
			action = "Use Manage Devices on the Developer page to erase or delete them, or run xcrun simctl delete unavailable."},
		{id = "simulator-runtimes", title = "Simulator runtimes", icon = "iphone.gen3",
			paths = {"/Library/Developer/CoreSimulator/Images", "/Library/Developer/CoreSimulator/Volumes"}, resources = {"runtime-images", "runtime-bundles", "runtime-assets"}, open = "runtimes",
			summary = "The operating systems simulators run, several gigabytes each.",
			what = "Recent Xcode versions download simulator runtimes as disk images that macOS mounts when needed, separate from Xcode itself.",
			why = "Every iOS, watchOS, tvOS and visionOS version you install stays until you remove it, even after you upgrade Xcode.",
			action = "Remove old runtimes in Xcode › Settings › Components, or with xcrun simctl runtime delete."},
		{id = "device-support", title = "Device support", icon = "cable.connector",
			paths = {"~/Library/Developer/Xcode/iOS DeviceSupport"}, resources = {"devices"}, open = "xcode",
			summary = "Debug symbols copied from your devices.",
			what = "When you connect a device to debug, Xcode copies the symbols for that exact OS version to this folder.",
			why = "Each OS version gets its own folder of several gigabytes, and old versions are never removed.",
			action = "Remove folders for OS versions you no longer debug. Xcode copies them again when needed."},
		{id = "archives", title = "Archives", icon = "archivebox",
			paths = {"~/Library/Developer/Xcode/Archives"}, resources = {"archives"}, open = "xcode",
			summary = "Your shipped builds. Keep them.",
			what = "Archives hold release builds with their debug symbols (dSYMs).",
			why = "Every archive you create stays until you delete it in the Xcode Organizer.",
			action = "Keep archives for versions still in use; you need their dSYMs to symbolicate crash reports."},
		{id = "docker", title = "Docker's virtual disk", icon = "shippingbox.fill",
			paths = {"~/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw"}, resources = {"docker"}, open = "containers",
			summary = "One file that holds every image, container and volume.",
			what = "Docker Desktop runs Linux in a virtual machine whose disk is a single sparse file. Images, containers, build cache and volumes all live inside it.",
			why = "The disk grows as you pull images and build, and may not shrink by itself when you delete them. Volumes can contain databases.",
			action = "Check usage with docker system df and prune from Docker, not Finder. Set a disk limit in Docker Settings › Resources."},
		{id = "homebrew", title = "Homebrew", icon = "mug",
			paths = {"/opt/homebrew", "~/Library/Caches/Homebrew"}, resources = {"brew-install", "brew"}, open = "packages",
			summary = "Installed packages, old versions and downloads.",
			what = "Homebrew installs packages in /opt/homebrew on Apple silicon (/usr/local on Intel) and keeps downloaded bottles in its cache.",
			why = "Upgrades keep older versions and downloads until cleanup runs.",
			action = "Run brew cleanup to remove old versions and downloads, and brew autoremove to drop unused dependencies."},
	}},
}
