-- Diskmap Help: how to use the app, written as task-based topics in the
-- style of Apple's user guides (a question or task as the title, a one-line
-- answer, short numbered steps, then a note). The Storage Guide explains
-- macOS; these topics explain Diskmap. Features and their reasons come from
-- VISION.md. `show` names the page or sheet a topic's button opens;
-- `keywords` widen the Help menu search. The keyboard shortcut topic is
-- generated from the menu bar so it cannot drift from it.
return {
	{id = "start", title = "Get started", icon = "sparkles", topics = {
		{id = "welcome", title = "What Diskmap does", icon = "chart.pie",
			show = "overview", keywords = "about intro overview owner category",
			summary = "Diskmap shows what uses your storage, why it is there and what you can safely do about it.",
			steps = {
				"Diskmap groups storage by what owns it (Xcode, Docker, Photos, an app) rather than by folder, so you never need to know where macOS hides things.",
				"Every location states whether it is rebuildable, needs review, is essential or is managed by macOS, and what happens if you remove it.",
				"Where Diskmap cannot see or attribute storage, it says so instead of guessing.",
			},
			note = "Diskmap reads only names, sizes and dates. It never opens your files."},
		{id = "measure", title = "Measure your storage", icon = "arrow.clockwise",
			command = "refresh", keywords = "scan refresh measure stop progress update",
			summary = "Diskmap measures every category when it opens and whenever you ask.",
			steps = {
				"Open Diskmap. Measuring starts at once, and each page shows its progress.",
				"To measure again after freeing space, choose Storage › Refresh or click Refresh in the toolbar.",
				"To stop a measurement, choose Storage › Stop Measuring or click Stop, which takes Refresh’s place in the toolbar while Diskmap measures.",
				"To keep sizes current, choose Diskmap › Settings and turn on “Refresh while Diskmap is open”.",
			},
			note = "Photos, Music and TV libraries are skipped unless you turn on “Include media libraries” in Settings."},
		{id = "access", title = "Let Diskmap see protected folders", icon = "lock.open",
			command = "privacy", keywords = "full disk access permission privacy protected partial missing",
			summary = "Full Disk Access lets Diskmap measure folders macOS protects, such as Mail and Messages.",
			steps = {
				"Choose Storage › Full Disk Access Settings.",
				"In Privacy & Security, turn on Full Disk Access for Diskmap.",
				"Return to Diskmap and choose Storage › Refresh.",
			},
			note = "Access is optional. Without it, sizes marked “≥” are partial and protected stores are listed as not measured."},
	}},
	{id = "explore", title = "See what uses space", icon = "magnifyingglass", topics = {
		{id = "overview", title = "Read the Overview", icon = "chart.pie.fill",
			show = "overview", keywords = "donut chart categories legend free not attributed",
			summary = "The Overview shows your whole startup disk by category.",
			steps = {
				"The donut shows each category's share; the empty track is free space.",
				"Gray is storage Diskmap measured on the disk but could not attribute to an owner.",
				"Click a category in the legend or the list to see what it contains.",
			}},
		{id = "largest", title = "Find the largest items", icon = "chart.bar.fill",
			show = "largest", keywords = "biggest folders ranked top hundred",
			summary = "Largest Locations ranks the hundred biggest measured locations across every category.",
			steps = {
				"Choose Go › Largest Locations.",
				"Each row names its owner and cleanup status, so you know whether it is yours to remove.",
				"Click More (…) or Control-click a row to show it in Finder, open its category or Keep it.",
			}},
		{id = "files", title = "Find large, forgotten files", icon = "doc.fill",
			show = "files", keywords = "large files old unused year downloads dmg installers archives media video",
			summary = "Large Files lists individual files over 50 MB and when you last used them.",
			steps = {
				"Choose Go › Large Files.",
				"Filter by Unused for a year, Installers & archives or Media to find likely candidates.",
				"To remove a document from your home folder, choose Move to Trash from its row menu and confirm.",
			},
			note = "Files inside Library, hidden tool folders and packages such as a Photos library cannot be trashed here; their owner manages them."},
		{id = "folder", title = "Map any folder or disk", icon = "folder.fill",
			show = "folder", keywords = "folder disk external drive drop dock open sunburst treemap quick look move offload kinds age last used",
			summary = "Folder Map shows everything in a folder or disk you choose, largest first, as rings or rectangles.",
			steps = {
				"Drag a folder or disk from the Finder onto the Diskmap window or its Dock icon, or choose File › Open Folder….",
				"Click a folder in the map or the list to look inside it; click the center or the path above the map to go back.",
				"Color the map by Folders, Kinds of file or Last Used to spot videos, installers or files untouched for years.",
				"Select a file and press Command-Y, or choose Quick Look from its row menu, to preview it.",
				"Choose Move to… from a row menu to offload it to another disk, or Move to Trash to remove it; the map updates at once.",
			},
			note = "Diskmap changes only items in your home folder and on other disks, never system folders or locations you Keep."},
		{id = "kinds", title = "See storage by file type", icon = "square.grid.2x2.fill",
			show = "kinds", keywords = "file types extensions videos disk images ai models virtual machines",
			summary = "File Types groups every measured byte by kind, such as videos, disk images or AI models.",
			steps = {
				"Choose Go › File Types.",
				"Open a kind to see its largest files in Large Files.",
			}},
		{id = "search", title = "Search Diskmap", icon = "magnifyingglass",
			command = "find", keywords = "find filter query",
			summary = "The search field finds locations, files, apps, projects and topics across Diskmap.",
			steps = {
				"Choose Edit › Find › Find… or click the search field in the toolbar.",
				"Type a name or a path such as Docker, Xcode or Photos. The results are grouped by kind.",
				"Open a result to go where Diskmap shows it. Back returns to the results.",
				"Clear the field to return to the page you were on.",
			},
			note = "To search help, use the search field in the Help menu."},
	}},
	{id = "clean", title = "Free up space safely", icon = "sparkles", topics = {
		{id = "labels", title = "What cleanup labels mean", icon = "checkmark.shield",
			show = "cleanup", keywords = "rebuildable review essential system managed safe delete policy",
			summary = "Each location says what it is and who removes it, and Diskmap never adds different kinds together.",
			steps = {
				"Rebuildable: caches and build products Diskmap moves to the Trash or asks their owner to clear; the owner recreates them.",
				"Clear in its app: caches and downloads an app or System Settings removes; the row says where.",
				"Restart: temporary files, swap and update staging macOS clears itself at the next restart or once a pending update completes.",
				"Needs review: data only you can judge, such as backups, downloads, chat media or old simulators.",
				"Essential: data an app needs to work, such as installed simulator runtimes.",
				"System managed: storage macOS controls, such as snapshots and downloaded system assets; context only.",
			},
			note = "Diskmap never sums rebuildable and reviewable storage into one “safe” number."},
		{id = "recommendations", title = "Review cleanup suggestions", icon = "sparkles",
			show = "cleanup", keywords = "clean up recommendations suggestions reclaim checklist",
			summary = "Clean Up lists what you can remove and everything it checked and found fine.",
			steps = {
				"Choose Go › Clean Up or click Clean Up in the toolbar.",
				"Start with Clear now, then what each app clears, then what a restart clears; your decisions come last, ranked by what they could recover.",
				"Open a suggestion to see its locations, the consequence of removing it and how to do it.",
			},
			note = "The checklist at the end shows known space hogs that were measured and are within their limits, so no suggestion also tells you something."},
		{id = "keep", title = "Keep something you need", icon = "checkmark.shield.fill",
			keywords = "keep protect exclude ignore stop keeping",
			summary = "Keep removes a location from suggestions until you change your mind.",
			steps = {
				"Click More (…) or Control-click the row.",
				"Choose Keep. Choose Stop Keeping to undo it.",
			},
			note = "Diskmap remembers what you keep between launches."},
		{id = "owner", title = "Let the owner clean up", icon = "hammer",
			show = "developer", keywords = "simctl npm pip docker prune manage backups owner command",
			summary = "Where a tool manages its own data, Diskmap asks it to clean up instead of deleting folders.",
			steps = {
				"Open the category and choose the action it offers, such as Clear Cache or Delete Unavailable.",
				"Diskmap confirms the measured size, runs the owner's command (for example npm cache clean) and measures again.",
				"For device backups and app data, Diskmap opens the app or setting that manages them.",
			}},
		{id = "trash", title = "Empty the Trash", icon = "trash",
			command = "emptyTrash", keywords = "trash empty delete didn't free space snapshot purgeable",
			summary = "Moving files to the Trash frees nothing until the Trash is emptied.",
			steps = {
				"Choose Storage › Empty Trash….",
				"Check the size and confirm. Finder permanently removes the files and Diskmap measures again.",
			},
			note = "If space still does not return, local Time Machine snapshots may hold the deleted files. See Updates & Snapshots."},
	}},
	{id = "apps", title = "Apps and developer tools", icon = "square.grid.3x3.fill", topics = {
		{id = "leftovers", title = "Find data left by deleted apps", icon = "square.grid.3x3.fill",
			show = "applications", keywords = "uninstall leftovers containers application support orphaned bundle identifier",
			summary = "Applications shows each app with the data it keeps, and data no installed app claims.",
			steps = {
				"Choose Go › Applications.",
				"Filter by Unused for 6 months or Most data to find apps worth removing.",
				"Review Possible leftovers: folders named like an app identifier that no installed app claims.",
			},
			note = "Diskmap never uninstalls apps. Apple's own identifiers are never listed as leftovers."},
		{id = "developer", title = "Reclaim space from Xcode and developer tools", icon = "hammer.fill",
			show = "developer", keywords = "xcode deriveddata device support packages npm cargo docker toolchains virtual machines",
			summary = "Developer groups Xcode, package caches, toolchains, containers and AI tools.",
			steps = {
				"Choose Go › Developer.",
				"DerivedData and package caches are rebuildable; device support, toolchains and virtual machines need review.",
				"Open a location to see its owner's cleanup command.",
			}},
		{id = "simulators", title = "Manage simulators and runtimes", icon = "iphone",
			show = "simulators", keywords = "simulator runtime coresimulator erase delete unavailable",
			summary = "Simulators lists every device and runtime with its size and last use.",
			steps = {
				"Choose Go › Simulators.",
				"Filter by Unavailable or Unused for 90 days, then Erase or Delete devices.",
				"Delete a runtime only after reading which devices it would strand.",
			},
			note = "Diskmap uses simctl, never Finder, so Xcode stays consistent."},
		{id = "ai", title = "Find local AI models", icon = "cpu",
			show = "developer", keywords = "ai models ollama lm studio hugging face gguf safetensors agents codex claude cursor",
			summary = "Local models and AI coding tools can use tens of gigabytes that nothing removes automatically.",
			steps = {
				"Choose Go › Developer and look under AI tools & models.",
				"Remove models with their own tool, for example ollama rm or huggingface-cli delete-cache.",
				"File Types also counts model files such as .gguf and .safetensors.",
			}},
	}},
	{id = "disk", title = "Your Mac's disk", icon = "internaldrive", topics = {
		{id = "disks", title = "Check disk health and volumes", icon = "internaldrive.fill",
			show = "disks", keywords = "smart health filevault apfs volumes first aid disk utility",
			summary = "Disks & Volumes shows drive health, FileVault and every APFS volume.",
			steps = {
				"Choose Go › Disks & Volumes.",
				"To repair a disk, choose Storage › Open Disk Utility and run First Aid.",
			},
			note = "This page is read-only."},
		{id = "updates", title = "Understand updates and snapshots", icon = "arrow.triangle.2.circlepath",
			show = "updates", keywords = "software update install macos snapshots time machine preboot",
			summary = "Updates & Snapshots shows storage held by pending updates and local snapshots.",
			steps = {
				"Choose Go › Updates & Snapshots.",
				"Finish or retry a pending update in Software Update settings to release its downloads.",
				"Local snapshots are removed by macOS when space is needed.",
			}},
		{id = "systemdata", title = "Why System Data is so large", icon = "questionmark.folder",
			show = "guide", keywords = "system data other purgeable caches logs spotlight",
			summary = "Diskmap splits System Data by owner and explains what it cannot see.",
			steps = {
				"Open System Data on the Overview to see caches, logs, developer data and more by owner.",
				"Read Common culprits in the Storage Guide for runaway logs, the Spotlight index and document versions.",
			}},
		{id = "unmeasured", title = "What Diskmap cannot measure", icon = "lock.shield",
			show = "filesystem", keywords = "protected sip system integrity not attributed unreadable apple intelligence full disk access leftovers interrupted update",
			summary = "Some macOS folders refuse every app. Diskmap names them and counts their space as not attributed.",
			steps = {
				"The Overview's What Diskmap could not measure card lists each reason, with how much space is in no category.",
				"Protected by macOS locations, such as the Apple Intelligence models, cannot be read with any permission; Full Disk Access does not help.",
				"Choose Help › macOS Folders to see every macOS folder, what it holds and its size, including where interrupted updates leave data.",
			}},
	}},
	{id = "privacy", title = "Privacy and shortcuts", icon = "hand.raised", topics = {
		{id = "reads", title = "What Diskmap reads", icon = "hand.raised.fill",
			keywords = "privacy contents network data collected",
			summary = "Names, sizes and dates only.",
			steps = {
				"Diskmap measures allocated sizes and reads file names and dates. It never reads file contents.",
				"Measurements stay on your Mac. Diskmap saves only its settings and the locations you Keep.",
			},
			note = "Because contents are never read, Diskmap does not look for duplicate files."},
		{id = "menus", title = "Use row menus", icon = "ellipsis.circle",
			keywords = "context menu more button show in finder copy path",
			summary = "Every list offers the same actions in its More (…) button and when you Control-click a row.",
			steps = {
				"The primary action comes first, then Quick Look, Show in Finder and the owning category.",
				"Keep and Copy Path follow.",
				"Large Files and Folder Map rows also offer Move to…, which moves an item to another folder or disk.",
			}},
		{id = "shortcuts", title = "Keyboard shortcuts", icon = "keyboard",
			keywords = "keyboard shortcuts keys command",
			summary = "Every page and command in the menu bar has a keyboard shortcut."},
	}},
}
